[
        "2009": [
                themeYear: "2009", // folder name
                themeName: "Emergency",
                themeDesc: "Any product related to challenging situations may fit, both life and non-life threatening: pandemic; animal welfare; natural disaster; blackouts; poverty; medical; elderly; emotional; crisis; rescue; home.",
                highlights: [
                        [ linkLabel: "Home page and slide show", linkUrl: "data/2009/homepage/index.html" ],
                        [ linkLabel: "Student tribute", linkUrl: "data/2009/highlights/tributePublic_sm.mov", onClick: "window.open('data/2009/highlights/tributePublic_sm.mov', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Hovercraft, the future is now", linkUrl: "data/2009/highlights/hovercraft_sm.mov", onClick: "window.open('data/2009/highlights/hovercraft_sm.mov', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Gorilla in the classroom", linkUrl: "data/2009/highlights/banana09.mov", onClick: "window.open('data/2009/highlights/banana09.mov', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                ],
                highlightDividerIndexes: [ 1 ],
                sketchMovWidth: 320,
                sketchMovHeight: 256,
                mockMovWidth: 320,
                mockMovHeight: 256,
                techMovWidth: 320,
                techMovHeight: 256,
                finalMovWidth: 320,
                finalMovHeight: 256,
                picWidth: 240, // picHeight is determined dynamically
                projects: [
                        [
                                projId: "aquAIRius", // folder name
                                projName: "aquAIRius",
                                projDesc: "adjustable buoyancy backboard",
                                projColor: "blue",
                                projTeam: "Alexandra Beyer, Hallie Cho, Lisa Schlecht, Shanette Go, Anup Samuel, Christopher Benson, Jordan Meenen, Ryan Morrow, Alice Brooks, Jacqueline Rogoff, Mary DiGenova, Natasha Scolnik, Archimedes Stuk, Ben Burns, Samuel Weiss, Jameslevi Schmidt",
                                projCode: "data/2009/homepage/codeOfEthics/codeOfEthics.html#blue",

                                ideasPic1: "data/2009/ideas/BlueA1.jpg",
                                ideasPic2: "data/2009/ideas/BlueA2.jpg",
                                ideasPic3: "data/2009/ideas/BlueA3.jpg",
                                ideasPic4: "data/2009/ideas/BlueB1.jpg",
                                ideasPic5: "data/2009/ideas/BlueB2.jpg",
                                ideasPic6: "data/2009/ideas/BlueB3.jpg",

                                sketchName1: "Spot-On",
                                sketchName2: "Bedsore",
                                sketchName3: "Variable Buoyancy Backboard",
                                sketchName4: "EasyLift Stretcher",
                                sketchPic1: "data/2009/sketch/photos/blueA1_1.JPG",
                                sketchPic2: "data/2009/sketch/photos/blueA1_2.JPG",
                                sketchPic3: "data/2009/sketch/photos/blueA2_1.JPG",
                                sketchPic4: "data/2009/sketch/photos/blueA2_2.JPG",
                                sketchPic5: "data/2009/sketch/photos/blueB1_1.JPG",
                                sketchPic6: "data/2009/sketch/photos/blueB1_2.JPG",
                                sketchPic7: "data/2009/sketch/photos/blueB2_1.JPG",
                                sketchPic8: "data/2009/sketch/photos/blueB2_2.JPG",
                                sketchMov1: "data/2009/sketch/movies/blueA1.mov",
                                sketchMov2: "data/2009/sketch/movies/blueA2.mov",
                                sketchMov3: "data/2009/sketch/movies/blueB1.mov",
                                sketchMov4: "data/2009/sketch/movies/blueB2.mov",
                                sketchSlide1: "data/2009/sketch/slides/blueA1.pdf",
                                sketchSlide2: "data/2009/sketch/slides/blueA2.pdf",
                                sketchSlide3: "data/2009/sketch/slides/blueB1.pdf",
                                sketchSlide4: "data/2009/sketch/slides/blueB2.pdf",

                                mockName1: "Spot-On",
                                mockName2: "Variable Buoyancy Backboard",
                                mockPic1: "data/2009/mockup/photos/blueA1.JPG",
                                mockPic2: "data/2009/mockup/photos/blueA2.JPG",
                                mockPic3: "data/2009/mockup/photos/blueB1.JPG",
                                mockPic4: "data/2009/mockup/photos/blueB2.JPG",
                                mockMov1: "data/2009/mockup/movies/blueAs.mov",
                                mockMov2: "data/2009/mockup/movies/blueBs.mov",
                                mockSlide1: "data/2009/mockup/slides/blueA.pdf",
                                mockSlide2: "data/2009/mockup/slides/blueB.pdf",

                                assemblyPic1: "data/2009/assembly/blueAssembly.jpg",
                                assemblyContract1: "data/2009/assembly/blueContract.pdf",

                                techPic1: "data/2009/tech/photos/Blue1.JPG",
                                techPic2: "data/2009/tech/photos/Blue2.JPG",
                                techMov1: "data/2009/tech/movies/Blue.mov",
                                techContract1: "data/2009/tech/extras/Blue_product_contract.pdf",

                                finalPic1: "data/2009/final/photos/blue1.JPG",
                                finalPic2: "data/2009/final/photos/blue2.JPG",
                                finalMov1: "data/2009/final/movies/blue.mov",
                                finalSlide1: "data/2009/final/slides/blue.pdf",
                                finalBrochure1: "data/2009/final/extras/blueBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Komera", // folder name
                                projName: "Komera",
                                projDesc: "banana leaf pad assembler",
                                projColor: "yellow",
                                projTeam: "Ariadne Smith, Kamyin Cheng, Nicole Berdy, Adi Asali, Chris Carper, Richard Bates, Justin Schmidt, Tyler Liechty, Laura Aust, Katherine Smyth, Amrita Saigal, Abdulaziz Albahar, Corey Garvey, Robert Kalwarowsky, John Williams, Zachary Rose",
                                projCode: "data/2009/homepage/codeOfEthics/codeOfEthics.html#yellow",

                                ideasPic1: "data/2009/ideas/YellowA1.jpg",
                                ideasPic2: "data/2009/ideas/YellowA2.jpg",
                                ideasPic3: "data/2009/ideas/YellowA3.jpg",
                                ideasPic4: "data/2009/ideas/YellowB1.jpg",
                                ideasPic5: "data/2009/ideas/YellowB2.jpg",
                                ideasPic6: "data/2009/ideas/YellowB3.jpg",

                                sketchName1: "Bloodmobile",
                                sketchName2: "Water Filtration System",
                                sketchName3: "EmergiTent",
                                sketchName4: "Banana Leaf Pad Assembler",
                                sketchPic1: "data/2009/sketch/photos/yellowA1_1.JPG",
                                sketchPic2: "data/2009/sketch/photos/yellowA1_2.JPG",
                                sketchPic3: "data/2009/sketch/photos/yellowA2_1.JPG",
                                sketchPic4: "data/2009/sketch/photos/yellowA2_2.JPG",
                                sketchPic5: "data/2009/sketch/photos/yellowB1_1.JPG",
                                sketchPic6: "data/2009/sketch/photos/yellowB1_2.JPG",
                                sketchPic7: "data/2009/sketch/photos/yellowB2_1.JPG",
                                sketchPic8: "data/2009/sketch/photos/yellowB2_2.JPG",
                                sketchMov1: "data/2009/sketch/movies/yellowA1.mov",
                                sketchMov2: "data/2009/sketch/movies/yellowA2.mov",
                                sketchMov3: "data/2009/sketch/movies/yellowB1.mov",
                                sketchMov4: "data/2009/sketch/movies/yellowB2.mov",
                                sketchSlide1: "data/2009/sketch/slides/yellowA1.pdf",
                                sketchSlide2: "data/2009/sketch/slides/yellowA2.pdf",
                                sketchSlide3: "data/2009/sketch/slides/yellowB1.pdf",
                                sketchSlide4: "data/2009/sketch/slides/yellowB2.pdf",

                                mockName1: "FrostBike",
                                mockName2: "Banana Leaf Pad Assembler",
                                mockPic1: "data/2009/mockup/photos/yellowA1.JPG",
                                mockPic2: "data/2009/mockup/photos/yellowA2.JPG",
                                mockPic3: "data/2009/mockup/photos/yellowB1.JPG",
                                mockPic4: "data/2009/mockup/photos/yellowB2.JPG",
                                mockMov1: "data/2009/mockup/movies/yellowAs.mov",
                                mockMov2: "data/2009/mockup/movies/yellowBs.mov",
                                mockSlide1: "data/2009/mockup/slides/yellowA.pdf",
                                mockSlide2: "data/2009/mockup/slides/yellowB.pdf",

                                assemblyPic1: "data/2009/assembly/yellowAssembly.jpg",
                                assemblyContract1: "data/2009/assembly/yellowContract.pdf",

                                techPic1: "data/2009/tech/photos/Yellow1.JPG",
                                techPic2: "data/2009/tech/photos/Yellow2.JPG",
                                techMov1: "data/2009/tech/movies/Yellow.mov",
                                techContract1: "data/2009/tech/extras/Yellow_product_contract.pdf",

                                finalPic1: "data/2009/final/photos/yellow1.JPG",
                                finalPic2: "data/2009/final/photos/yellow2.JPG",
                                finalMov1: "data/2009/final/movies/yellow.mov",
                                finalSlide1: "data/2009/final/slides/yellow.pdf",
                                finalBrochure1: "data/2009/final/extras/yellowBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "ixa-walker", // folder name
                                projName: "Ixa Walker",
                                projDesc: "ixa walker",
                                projColor: "purple",
                                projTeam: "Jacklyn Holmes, Lisa Tacoronte, Rachel Sharples, Andrew Marecki, Garth Grove, Juan Fernando Rodriguez, Stephen Morton, Julia Day, Mindy Eng, Eric Beecher, Howard Liles, Timothy Robertson II, Adam Goldstein, Luke Cummings, Geng Tan",
                                projCode: "data/2009/homepage/codeOfEthics/codeOfEthics.html#purple",

                                ideasPic1: "data/2009/ideas/PurpleA1.jpg",
                                ideasPic2: "data/2009/ideas/PurpleA2.jpg",
                                ideasPic3: "data/2009/ideas/PurpleA3.jpg",
                                ideasPic4: "data/2009/ideas/PurpleB1.jpg",
                                ideasPic5: "data/2009/ideas/PurpleB2.jpg",
                                ideasPic6: "data/2009/ideas/PurpleB3.jpg",

                                sketchName1: "Organ Vitality System",
                                sketchName2: "Electronic Stethoscope",
                                sketchName3: "Walker Lift",
                                sketchName4: "Inexpensive, Automatic Ventilator",
                                sketchPic1: "data/2009/sketch/photos/purpleA1_1.JPG",
                                sketchPic2: "data/2009/sketch/photos/purpleA1_2.JPG",
                                sketchPic3: "data/2009/sketch/photos/purpleA2_1.JPG",
                                sketchPic4: "data/2009/sketch/photos/purpleA2_2.JPG",
                                sketchPic5: "data/2009/sketch/photos/purpleB1_1.JPG",
                                sketchPic6: "data/2009/sketch/photos/purpleB1_2.JPG",
                                sketchPic7: "data/2009/sketch/photos/purpleB2_1.JPG",
                                sketchPic8: "data/2009/sketch/photos/purpleB2_2.JPG",
                                sketchMov1: "data/2009/sketch/movies/purpleA1.mov",
                                sketchMov2: "data/2009/sketch/movies/purpleA2.mov",
                                sketchMov3: "data/2009/sketch/movies/purpleB1.mov",
                                sketchMov4: "data/2009/sketch/movies/purpleB2.mov",
                                sketchSlide1: "data/2009/sketch/slides/purpleA1.pdf",
                                sketchSlide2: "data/2009/sketch/slides/purpleA2.pdf",
                                sketchSlide3: "data/2009/sketch/slides/purpleB1.pdf",
                                sketchSlide4: "data/2009/sketch/slides/purpleB2.pdf",

                                mockName1: "Organ Vitality System",
                                mockName2: "Lift Rails",
                                mockPic1: "data/2009/mockup/photos/purpleA1.JPG",
                                mockPic2: "data/2009/mockup/photos/purpleA2.JPG",
                                mockPic3: "data/2009/mockup/photos/purpleB1.JPG",
                                mockPic4: "data/2009/mockup/photos/purpleB2.JPG",
                                mockMov1: "data/2009/mockup/movies/purpleAs.mov",
                                mockMov2: "data/2009/mockup/movies/purpleBs.mov",
                                mockSlide1: "data/2009/mockup/slides/purpleA.pdf",
                                mockSlide2: "data/2009/mockup/slides/purpleB.pdf",

                                assemblyPic1: "data/2009/assembly/purpleAssembly.jpg",
                                assemblyContract1: "data/2009/assembly/purpleContract.pdf",

                                techPic1: "data/2009/tech/photos/Purple1.JPG",
                                techPic2: "data/2009/tech/photos/Purple2.JPG",
                                techMov1: "data/2009/tech/movies/Purple.mov",
                                techContract1: "data/2009/tech/extras/Purple_product_contract.pdf",

                                finalPic1: "data/2009/final/photos/purple1.JPG",
                                finalPic2: "data/2009/final/photos/purple2.JPG",
                                finalMov1: "data/2009/final/movies/purple.mov",
                                finalSlide1: "data/2009/final/slides/purple.pdf",
                                finalBrochure1: "data/2009/final/extras/purpleBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "isis-helmet", // folder name
                                projName: "Isis Helmet",
                                projDesc: "isis helmet",
                                projColor: "orange",
                                projTeam: "Jeremy Kuempel, Melissa Kaufman, Katrina Ellison, Minhee Sung, Neha Batra, Corey Harris, Eric Guffey, Joseph Silverman, Erika Sandford, Katharine Binder, Zhechen Hong, Maria Prus, Mark Barineau, Cody Rebholz, James White, Joe Khoury",
                                projCode: "data/2009/homepage/codeOfEthics/codeOfEthics.html#orange",

                                ideasPic1: "data/2009/ideas/OrangeA1.jpg",
                                ideasPic2: "data/2009/ideas/OrangeA2.jpg",
                                ideasPic3: "data/2009/ideas/OrangeA3.jpg",
                                ideasPic4: "data/2009/ideas/OrangeB1.jpg",
                                ideasPic5: "data/2009/ideas/OrangeB2.jpg",
                                ideasPic6: "data/2009/ideas/OrangeB3.jpg",

                                sketchName1: "AutoVest",
                                sketchName2: "StoveSafe",
                                sketchName3: "Helmet 911",
                                sketchName4: "HoseGoes",
                                sketchPic1: "data/2009/sketch/photos/orangeA1_1.JPG",
                                sketchPic2: "data/2009/sketch/photos/orangeA1_2.JPG",
                                sketchPic3: "data/2009/sketch/photos/orangeA2_1.JPG",
                                sketchPic4: "data/2009/sketch/photos/orangeA2_2.JPG",
                                sketchPic5: "data/2009/sketch/photos/orangeB1_1.JPG",
                                sketchPic6: "data/2009/sketch/photos/orangeB1_2.JPG",
                                sketchPic7: "data/2009/sketch/photos/orangeB2_1.JPG",
                                sketchPic8: "data/2009/sketch/photos/orangeB2_2.JPG",
                                sketchMov1: "data/2009/sketch/movies/orangeA1.mov",
                                sketchMov2: "data/2009/sketch/movies/orangeA2.mov",
                                sketchMov3: "data/2009/sketch/movies/orangeB1.mov",
                                sketchMov4: "data/2009/sketch/movies/orangeB2.mov",
                                sketchSlide1: "data/2009/sketch/slides/orangeA1.pdf",
                                sketchSlide2: "data/2009/sketch/slides/orangeA2.pdf",
                                sketchSlide3: "data/2009/sketch/slides/orangeB1.pdf",
                                sketchSlide4: "data/2009/sketch/slides/orangeB2.pdf",

                                mockName1: "StoveSafe",
                                mockName2: "Helmet 9-1-1",
                                mockPic1: "data/2009/mockup/photos/orangeA1.JPG",
                                mockPic2: "data/2009/mockup/photos/orangeA2.JPG",
                                mockPic3: "data/2009/mockup/photos/orangeB1.JPG",
                                mockPic4: "data/2009/mockup/photos/orangeB2.JPG",
                                mockMov1: "data/2009/mockup/movies/orangeAs.mov",
                                mockMov2: "data/2009/mockup/movies/orangeBs.mov",
                                mockSlide1: "data/2009/mockup/slides/orangeA.pdf",
                                mockSlide2: "data/2009/mockup/slides/orangeB.pdf",

                                assemblyPic1: "data/2009/assembly/orangeAssembly.jpg",
                                assemblyContract1: "data/2009/assembly/orangeContract.pdf",

                                techPic1: "data/2009/tech/photos/Orange1.JPG",
                                techPic2: "data/2009/tech/photos/Orange2.JPG",
                                techMov1: "data/2009/tech/movies/Orange.mov",
                                techContract1: "data/2009/tech/extras/Orange_product_contract.pdf",

                                finalPic1: "data/2009/final/photos/orange1.JPG",
                                finalPic2: "data/2009/final/photos/orange2.JPG",
                                finalMov1: "data/2009/final/movies/orange.mov",
                                finalSlide1: "data/2009/final/slides/orange.pdf",
                                finalBrochure1: "data/2009/final/extras/orangeBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "iceTek-scraper", // folder name
                                projName: "iceTek Scraper",
                                projDesc: "mechanical ice scraper",
                                projColor: "silver",
                                projTeam: "Katherine Ray, Michaelle Mayalu, Xuefeng Chen, Daniel Beauboeuf, Ian Rust, Matthew Rosario, Anthony McDonald, Aditi Nagaraj, Kathryn Pesce, Roseleigh Taylor, Adrian Adames, Eric Nielsen, Joshua Siegel, Nicholas Pennycooke, Troy Tamas, Cecilia Scott",
                                projCode: "data/2009/homepage/codeOfEthics/codeOfEthics.html#silver",

                                ideasPic1: "data/2009/ideas/SilverA1.jpg",
                                ideasPic2: "data/2009/ideas/SilverA2.jpg",
                                ideasPic3: "data/2009/ideas/SilverA3.jpg",
                                ideasPic4: "data/2009/ideas/SilverB1.jpg",
                                ideasPic5: "data/2009/ideas/SilverB2.jpg",
                                ideasPic6: "data/2009/ideas/SilverB3.jpg",

                                sketchName1: "GUARD",
                                sketchName2: "Float-EEZE",
                                sketchName3: "Vibrating Ice Scraper",
                                sketchName4: "Rescue Launcher",
                                sketchPic1: "data/2009/sketch/photos/silverA1_1.JPG",
                                sketchPic2: "data/2009/sketch/photos/silverA1_2.JPG",
                                sketchPic3: "data/2009/sketch/photos/silverA2_1.JPG",
                                sketchPic4: "data/2009/sketch/photos/silverA2_2.JPG",
                                sketchPic5: "data/2009/sketch/photos/silverB1_1.JPG",
                                sketchPic6: "data/2009/sketch/photos/silverB1_2.JPG",
                                sketchPic7: "data/2009/sketch/photos/silverB2_1.JPG",
                                sketchPic8: "data/2009/sketch/photos/silverB2_2.JPG",
                                sketchMov1: "data/2009/sketch/movies/silverA1.mov",
                                sketchMov2: "data/2009/sketch/movies/silverA2.mov",
                                sketchMov3: "data/2009/sketch/movies/silverB1.mov",
                                sketchMov4: "data/2009/sketch/movies/silverB2.mov",
                                sketchSlide1: "data/2009/sketch/slides/silverA1.pdf",
                                sketchSlide2: "data/2009/sketch/slides/silverA2.pdf",
                                sketchSlide3: "data/2009/sketch/slides/silverB1.pdf",
                                sketchSlide4: "data/2009/sketch/slides/silverB2.pdf",

                                mockName1: "Mechanical Ice Scraper",
                                mockName2: "Hurricane Shutters",
                                mockPic1: "data/2009/mockup/photos/silverA1.JPG",
                                mockPic2: "data/2009/mockup/photos/silverA2.JPG",
                                mockPic3: "data/2009/mockup/photos/silverB1.JPG",
                                mockPic4: "data/2009/mockup/photos/silverB2.JPG",
                                mockMov1: "data/2009/mockup/movies/silverAs.mov",
                                mockMov2: "data/2009/mockup/movies/silverBs.mov",
                                mockSlide1: "data/2009/mockup/slides/silverA.pdf",
                                mockSlide2: "data/2009/mockup/slides/silverB.pdf",

                                assemblyPic1: "data/2009/assembly/silverAssembly.jpg",
                                assemblyContract1: "data/2009/assembly/silverContract.pdf",

                                techPic1: "data/2009/tech/photos/Silver1.JPG",
                                techPic2: "data/2009/tech/photos/Silver2.JPG",
                                techMov1: "data/2009/tech/movies/Silver.mov",
                                techContract1: "data/2009/tech/extras/Silver_product_contract.pdf",

                                finalPic1: "data/2009/final/photos/silver1.JPG",
                                finalPic2: "data/2009/final/photos/silver2.JPG",
                                finalMov1: "data/2009/final/movies/silver.mov",
                                finalSlide1: "data/2009/final/slides/silver.pdf",
                                finalBrochure1: "data/2009/final/extras/silverBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "ascent", // folder name
                                projName: "Ascent",
                                projDesc: "rollator",
                                projColor: "green",
                                projTeam: "Elizabeth Tsai, Angharad Porteous, Kevin Plumer, Julio Devora, Keja Rowe, Long Lam, Luis Garay, Adnan Esmail, Neeharika Bhartiya, Theresa Dixon, Albert Wang, Claudio Di Leo, Elliott Perez, Kent Willis, Andrew Nanopoulos, Raphael Moyer",
                                projCode: "data/2009/homepage/codeOfEthics/codeOfEthics.html#green",

                                ideasPic1: "data/2009/ideas/GreenA1.jpg",
                                ideasPic2: "data/2009/ideas/GreenA2.jpg",
                                ideasPic3: "data/2009/ideas/GreenA3.jpg",
                                ideasPic4: "data/2009/ideas/GreenB1.jpg",
                                ideasPic5: "data/2009/ideas/GreenB2.jpg",
                                ideasPic6: "data/2009/ideas/GreenB3.jpg",

                                sketchName1: "Stair Descending Stretcher",
                                sketchName2: "Flood Bag",
                                sketchName3: "Damped Stretcher",
                                sketchName4: "The Walker Righter",
                                sketchPic1: "data/2009/sketch/photos/greenA1_1.JPG",
                                sketchPic2: "data/2009/sketch/photos/greenA1_2.JPG",
                                sketchPic3: "data/2009/sketch/photos/greenA2_1.JPG",
                                sketchPic4: "data/2009/sketch/photos/greenA2_2.JPG",
                                sketchPic5: "data/2009/sketch/photos/greenB1_1.JPG",
                                sketchPic6: "data/2009/sketch/photos/greenB1_2.JPG",
                                sketchPic7: "data/2009/sketch/photos/greenB2_1.JPG",
                                sketchPic8: "data/2009/sketch/photos/greenB2_2.JPG",
                                sketchMov1: "data/2009/sketch/movies/greenA1.mov",
                                sketchMov2: "data/2009/sketch/movies/greenA2.mov",
                                sketchMov3: "data/2009/sketch/movies/greenB1.mov",
                                sketchMov4: "data/2009/sketch/movies/greenB2.mov",
                                sketchSlide1: "data/2009/sketch/slides/greenA1.pdf",
                                sketchSlide2: "data/2009/sketch/slides/greenA2.pdf",
                                sketchSlide3: "data/2009/sketch/slides/greenB1.pdf",
                                sketchSlide4: "data/2009/sketch/slides/greenB2.pdf",

                                mockName1: "Stair Stretcher",
                                mockName2: "Walker Lift Assist",
                                mockPic1: "data/2009/mockup/photos/greenA1.JPG",
                                mockPic2: "data/2009/mockup/photos/greenA2.JPG",
                                mockPic3: "data/2009/mockup/photos/greenB1.JPG",
                                mockPic4: "data/2009/mockup/photos/greenB2.JPG",
                                mockMov1: "data/2009/mockup/movies/greenAs.mov",
                                mockMov2: "data/2009/mockup/movies/greenBs.mov",
                                mockSlide1: "data/2009/mockup/slides/greenA.pdf",
                                mockSlide2: "data/2009/mockup/slides/greenB.pdf",

                                assemblyPic1: "data/2009/assembly/greenAssembly.jpg",
                                assemblyContract1: "data/2009/assembly/greenContract.pdf",

                                techPic1: "data/2009/tech/photos/Green1.JPG",
                                techPic2: "data/2009/tech/photos/Green2.JPG",
                                techMov1: "data/2009/tech/movies/Green.mov",
                                techContract1: "data/2009/tech/extras/Green_product_contract.pdf",

                                finalPic1: "data/2009/final/photos/green1.JPG",
                                finalPic2: "data/2009/final/photos/green2.JPG",
                                finalMov1: "data/2009/final/movies/green.mov",
                                finalSlide1: "data/2009/final/slides/green.pdf",
                                finalBrochure1: "data/2009/final/extras/greenBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "airware", // folder name
                                projName: "Airware",
                                projDesc: "breathing apparatus",
                                projColor: "red",
                                projTeam: "Aria Reynolds, Carly Cobbold, Ashley Turza, Giorgio Zampierollo, Chris Peters, Michael Demyttenaere, Rastislav Racz, Jarred Schantz, Ashley Green, Taylor Williamson, Eric Reuland, James Torres, Evan Lampe, Paul Miyazaki, Tylor Hess, Allyson Randolph",
                                projCode: "data/2009/homepage/codeOfEthics/codeOfEthics.html#red",

                                ideasPic1: "data/2009/ideas/RedA1.jpg",
                                ideasPic2: "data/2009/ideas/RedA2.jpg",
                                ideasPic3: "data/2009/ideas/RedA3.jpg",
                                ideasPic4: "data/2009/ideas/RedB1.jpg",
                                ideasPic5: "data/2009/ideas/RedB2.jpg",
                                ideasPic6: "data/2009/ideas/RedB3.jpg",

                                sketchName1: "Lifesaving Belt",
                                sketchName2: "Impact Hardening Wrist Guard",
                                sketchName3: "Shoe Roll-ups",
                                sketchName4: "O-Tube",
                                sketchPic1: "data/2009/sketch/photos/redA1_1.JPG",
                                sketchPic2: "data/2009/sketch/photos/redA1_2.JPG",
                                sketchPic3: "data/2009/sketch/photos/redA2_1.JPG",
                                sketchPic4: "data/2009/sketch/photos/redA2_2.JPG",
                                sketchPic5: "data/2009/sketch/photos/redB1_1.JPG",
                                sketchPic6: "data/2009/sketch/photos/redB1_2.JPG",
                                sketchPic7: "data/2009/sketch/photos/redB2_1.JPG",
                                sketchPic8: "data/2009/sketch/photos/redB2_2.JPG",
                                sketchMov1: "data/2009/sketch/movies/redA1.mov",
                                sketchMov2: "data/2009/sketch/movies/redA2.mov",
                                sketchMov3: "data/2009/sketch/movies/redB1.mov",
                                sketchMov4: "data/2009/sketch/movies/redB2.mov",
                                sketchSlide1: "data/2009/sketch/slides/redA1.pdf",
                                sketchSlide2: "data/2009/sketch/slides/redA2.pdf",
                                sketchSlide3: "data/2009/sketch/slides/redB1.pdf",
                                sketchSlide4: "data/2009/sketch/slides/redB2.pdf",

                                mockName1: "CPR Rescue Can",
                                mockName2: "AirWear",
                                mockPic1: "data/2009/mockup/photos/redA1.JPG",
                                mockPic2: "data/2009/mockup/photos/redA2.JPG",
                                mockPic3: "data/2009/mockup/photos/redB1.JPG",
                                mockPic4: "data/2009/mockup/photos/redB2.JPG",
                                mockMov1: "data/2009/mockup/movies/redAs.mov",
                                mockMov2: "data/2009/mockup/movies/redBs.mov",
                                mockSlide1: "data/2009/mockup/slides/redA.pdf",
                                mockSlide2: "data/2009/mockup/slides/redB.pdf",

                                assemblyPic1: "data/2009/assembly/redAssembly.jpg",
                                assemblyContract1: "data/2009/assembly/redContract.pdf",

                                techPic1: "data/2009/tech/photos/Red1.JPG",
                                techPic2: "data/2009/tech/photos/Red2.JPG",
                                techMov1: "data/2009/tech/movies/Red.mov",
                                techContract1: "data/2009/tech/extras/Red_product_contract.pdf",

                                finalPic1: "data/2009/final/photos/red1.JPG",
                                finalPic2: "data/2009/final/photos/red2.JPG",
                                finalMov1: "data/2009/final/movies/red.mov",
                                finalSlide1: "data/2009/final/slides/red.pdf",
                                finalBrochure1: "data/2009/final/extras/redBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Fortrus", // folder name
                                projName: "Fortrus",
                                projDesc: "litter",
                                projColor: "pink",
                                projTeam: "Stephanie Brown, Jean Theurer, Marguerite Siboni, Adrian Dobson, Arron Acosta, Vu Hong, Yat Ming Victor Li, Robert Boyd, Michelle Ma, Tanya Goldhaber, Akhenaton-Andrew Jones, Yao Luo, Raymond Ma, Kevin A Rustagi, Blake Sessions",
                                projCode: "data/2009/homepage/codeOfEthics/codeOfEthics.html#pink",

                                ideasPic1: "data/2009/ideas/PinkA1.jpg",
                                ideasPic2: "data/2009/ideas/PinkA2.jpg",
                                ideasPic3: "data/2009/ideas/PinkA3.jpg",
                                ideasPic4: "data/2009/ideas/PinkB1.jpg",
                                ideasPic5: "data/2009/ideas/PinkB2.jpg",
                                ideasPic6: "data/2009/ideas/PinkB3.jpg",

                                sketchName1: "Automatic Battering Ram",
                                sketchName2: "Fire Extinguisher Pod",
                                sketchName3: "Metro-Aid",
                                sketchName4: "Flitter",
                                sketchPic1: "data/2009/sketch/photos/pinkA1_1.JPG",
                                sketchPic2: "data/2009/sketch/photos/pinkA1_2.JPG",
                                sketchPic3: "data/2009/sketch/photos/pinkA2_1.JPG",
                                sketchPic4: "data/2009/sketch/photos/pinkA2_2.JPG",
                                sketchPic5: "data/2009/sketch/photos/pinkB1_1.JPG",
                                sketchPic6: "data/2009/sketch/photos/pinkB1_2.JPG",
                                sketchPic7: "data/2009/sketch/photos/pinkB2_1.JPG",
                                sketchPic8: "data/2009/sketch/photos/pinkB2_2.JPG",
                                sketchMov1: "data/2009/sketch/movies/pinkA1.mov",
                                sketchMov2: "data/2009/sketch/movies/pinkA2.mov",
                                sketchMov3: "data/2009/sketch/movies/pinkB1.mov",
                                sketchMov4: "data/2009/sketch/movies/pinkB2.mov",
                                sketchSlide1: "data/2009/sketch/slides/pinkA1.pdf",
                                sketchSlide2: "data/2009/sketch/slides/pinkA2.pdf",
                                sketchSlide3: "data/2009/sketch/slides/pinkB1.pdf",
                                sketchSlide4: "data/2009/sketch/slides/pinkB2.pdf",

                                mockName1: "Fire-out",
                                mockName2: "Flitter",
                                mockPic1: "data/2009/mockup/photos/pinkA1.JPG",
                                mockPic2: "data/2009/mockup/photos/pinkA2.JPG",
                                mockPic3: "data/2009/mockup/photos/pinkB1.JPG",
                                mockPic4: "data/2009/mockup/photos/pinkB2.JPG",
                                mockMov1: "data/2009/mockup/movies/pinkAs.mov",
                                mockMov2: "data/2009/mockup/movies/pinkBs.mov",
                                mockSlide1: "data/2009/mockup/slides/pinkA.pdf",
                                mockSlide2: "data/2009/mockup/slides/pinkB.pdf",

                                assemblyPic1: "data/2009/assembly/pinkAssembly.jpg",
                                assemblyContract1: "data/2009/assembly/pinkContract.pdf",

                                techPic1: "data/2009/tech/photos/Pink1.JPG",
                                techPic2: "data/2009/tech/photos/Pink2.JPG",
                                techMov1: "data/2009/tech/movies/Pink.mov",
                                techContract1: "data/2009/tech/extras/Pink_product_contract.pdf",

                                finalPic1: "data/2009/final/photos/pink1.JPG",
                                finalPic2: "data/2009/final/photos/pink2.JPG",
                                finalMov1: "data/2009/final/movies/pink.mov",
                                finalSlide1: "data/2009/final/slides/pink.pdf",
                                finalBrochure1: "data/2009/final/extras/pinkBrochure.pdf",
                                finalBrochure2: null,
                        ],
                ],
        ],
]