[
        "2006": [
                themeYear: "2006", // folder name
                themeName: "Independent-living ",
                themeDesc: "Any products that extend independent-living for the ill, disabled, elderly, or otherwise may be considered. Target customers may include both developed and developing countries.",
                highlights: [
                        [ linkLabel: "Home page and slide show", linkUrl: "data/2006/homepage/index.html" ],
                        [ linkLabel: "Student tribute", linkUrl: "data/2006/highlights/studentTribute.mov", onClick: "window.open('data/2006/highlights/studentTribute.mov', 'movieWin', 'width=660,height=510,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Archimedes Steam Cannon", linkUrl: "http://web.mit.edu/2.009/www/experiments/steamCannon/ArchimedesSteamCannon.html" ],
                        [ linkLabel: "Demise of the Pony Express", linkUrl: "http://web.mit.edu/2.009/www/experiments/ponyExpress/PonyExpress.html" ],
                ],
                highlightDividerIndexes: [ 1 ],
                sketchMovWidth: 320,
                sketchMovHeight: 256,
                mockMovWidth: 320,
                mockMovHeight: 256,
                techMovWidth: 320,
                techMovHeight: 256,
                finalMovWidth: 320,
                finalMovHeight: 256,
                picWidth: 240, // picHeight is determined dynamically
                projects: [
                        [
                                projId: "Revolution", // folder name
                                projName: "Revolution",
                                projDesc: "a bike for the disabled",
                                projColor: "blue",
                                projTeam: "Andrew Harlan, Albert Hernandez, Courtney N. Greene, Emmanuel Sin, Katherine Rorschach, Mark Cote, Robert Panas, Elysa Wan, Alexander Krull, Diana Sim, Donald Walker, Jorge Renjifo, Nicholas Maietta, Michal Ruchelsman, Helen Tsai, Ulzie Rea",
                                projCode: "data/2006/homepage/codeOfEthics/codeOfEthics.html#blue",

                                ideasPic1: "data/2006/ideas/BlueA1.gif",
                                ideasPic2: "data/2006/ideas/BlueA2.gif",
                                ideasPic3: "data/2006/ideas/BlueA3.gif",
                                ideasPic4: "data/2006/ideas/BlueB1.gif",
                                ideasPic5: "data/2006/ideas/BlueB2.gif",
                                ideasPic6: "data/2006/ideas/BlueB3.gif",
                                
                                sketchName1: "Stabili-Bike",
                                sketchName2: "Super Stair Cart",
                                sketchName3: "Stair Caddy",
                                sketchName4: "Marco Polo Ball",
                                sketchPic1: "data/2006/sketch/photos/blueA1_1.JPG",
                                sketchPic2: "data/2006/sketch/photos/blueA1_2.JPG",
                                sketchPic3: "data/2006/sketch/photos/blueA2_1.JPG",
                                sketchPic4: "data/2006/sketch/photos/blueA2_2.JPG",
                                sketchPic5: "data/2006/sketch/photos/blueB1_1.JPG",
                                sketchPic6: "data/2006/sketch/photos/blueB1_2.JPG",
                                sketchPic7: "data/2006/sketch/photos/blueB2_1.JPG",
                                sketchPic8: "data/2006/sketch/photos/blueB2_2.JPG",
                                sketchMov1: "data/2006/sketch/movies/blueA1.mov",
                                sketchMov2: "data/2006/sketch/movies/blueA2.mov",
                                sketchMov3: "data/2006/sketch/movies/blueB1.mov",
                                sketchMov4: "data/2006/sketch/movies/blueB2.mov",
                                sketchSlide1: "data/2006/sketch/slides/blueA1.pdf",
                                sketchSlide2: "data/2006/sketch/slides/blueA2.pdf",
                                sketchSlide3: "data/2006/sketch/slides/blueB1.pdf",
                                sketchSlide4: "data/2006/sketch/slides/blueB2.pdf",

                                mockName1: "Stabili-bike",
                                mockName2: "Super stair cart",
                                mockPic1: "data/2006/mockup/photos/blueA1.JPG",
                                mockPic2: "data/2006/mockup/photos/blueA2.JPG",
                                mockPic3: "data/2006/mockup/photos/blueB1.JPG",
                                mockPic4: "data/2006/mockup/photos/blueB2.JPG",
                                mockMov1: "data/2006/mockup/movies/blueAs.mov",
                                mockMov2: "data/2006/mockup/movies/blueBs.mov",
                                mockSlide1: "data/2006/mockup/slides/blueA.pdf",
                                mockSlide2: "data/2006/mockup/slides/blueB.pdf",

                                assemblyPic1: "data/2006/assembly/blueAssembly.jpg",
                                assemblyContract1: "data/2006/assembly/blueContract.pdf",

                                techPic1: "data/2006/tech/photos/Blue1.JPG",
                                techPic2: "data/2006/tech/photos/Blue2.JPG",
                                techMov1: "data/2006/tech/movies/Blue.mov",
                                techContract1: null,

                                finalPic1: "data/2006/final/photos/blue1.JPG",
                                finalPic2: "data/2006/final/photos/blue2.JPG",
                                finalMov1: "data/2006/final/movies/blue.mov",
                                finalSlide1: "data/2006/final/slides/blue.pdf",
                                finalBrochure1: null,
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Slope-support", // folder name
                                projName: "Slope support",
                                projDesc: "an uphill wheel chair",
                                projColor: "yellow",
                                projTeam: "Brentan Alexander, David Mendiola, Erik Lampe, Inna Koyrakh, Jin Xu, Logan Munro, Phillip Dawson, Aaron Doody, David Lopez, Harmeet Gill, Moneer Helu, Earl Taylor Roan, Adam Leeb, Zachary Reynolds, Mike Lah",
                                projCode: "data/2006/homepage/codeOfEthics/codeOfEthics.html#yellow",

                                ideasPic1: "data/2006/ideas/YellowA1.gif",
                                ideasPic2: "data/2006/ideas/YellowA2.gif",
                                ideasPic3: "data/2006/ideas/YellowA3.gif",
                                ideasPic4: "data/2006/ideas/YellowB1.gif",
                                ideasPic5: "data/2006/ideas/YellowB2.gif",
                                ideasPic6: "data/2006/ideas/YellowB3.gif",

                                sketchName1: "Uphill wheelchair",
                                sketchName2: "Knob handler",
                                sketchName3: "Viscocise",
                                sketchName4: "RED Rover",
                                sketchPic1: "data/2006/sketch/photos/yellowA1_1.JPG",
                                sketchPic2: "data/2006/sketch/photos/yellowA1_2.JPG",
                                sketchPic3: "data/2006/sketch/photos/yellowA2_1.JPG",
                                sketchPic4: "data/2006/sketch/photos/yellowA2_2.JPG",
                                sketchPic5: "data/2006/sketch/photos/yellowB1_1.JPG",
                                sketchPic6: "data/2006/sketch/photos/yellowB1_2.JPG",
                                sketchPic7: "data/2006/sketch/photos/yellowB2_1.JPG",
                                sketchPic8: "data/2006/sketch/photos/yellowB2_2.JPG",
                                sketchMov1: "data/2006/sketch/movies/yellowA1.mov",
                                sketchMov2: "data/2006/sketch/movies/yellowA2.mov",
                                sketchMov3: "data/2006/sketch/movies/yellowB1.mov",
                                sketchMov4: "data/2006/sketch/movies/yellowB2.mov",
                                sketchSlide1: "data/2006/sketch/slides/yellowA1.pdf",
                                sketchSlide2: "data/2006/sketch/slides/yellowA2.pdf",
                                sketchSlide3: "data/2006/sketch/slides/yellowB1.pdf",
                                sketchSlide4: "data/2006/sketch/slides/yellowB2.pdf",

                                mockName1: "Geared wheel chair",
                                mockName2: "Knob handler",
                                mockPic1: "data/2006/mockup/photos/yellowA1.JPG",
                                mockPic2: "data/2006/mockup/photos/yellowA2.JPG",
                                mockPic3: "data/2006/mockup/photos/yellowB1.JPG",
                                mockPic4: "data/2006/mockup/photos/yellowB2.JPG",
                                mockMov1: "data/2006/mockup/movies/yellowAs.mov",
                                mockMov2: "data/2006/mockup/movies/yellowBs.mov",
                                mockSlide1: "data/2006/mockup/slides/yellowA.pdf",
                                mockSlide2: "data/2006/mockup/slides/yellowB.pdf",

                                assemblyPic1: "data/2006/assembly/yellowAssembly.jpg",
                                assemblyContract1: "data/2006/assembly/yellowContract.pdf",

                                techPic1: "data/2006/tech/photos/Yellow1.JPG",
                                techPic2: "data/2006/tech/photos/Yellow2.JPG",
                                techMov1: "data/2006/tech/movies/Yellow.mov",
                                techContract1: null,

                                finalPic1: "data/2006/final/photos/yellow1.JPG",
                                finalPic2: "data/2006/final/photos/yellow2.JPG",
                                finalMov1: "data/2006/final/movies/yellow.mov",
                                finalSlide1: "data/2006/final/slides/yellow.pdf",
                                finalBrochure1: "data/2006/final/extras/YellowBfront.pdf",
                                finalBrochure2: "data/2006/final/extras/YellowBback.pdf",
                        ],
                        [
                                projId: "Stabili-track", // folder name
                                projName: "Stabili-track",
                                projDesc: "a treadmill for the blind",
                                projColor: "purple",
                                projTeam: "Ashlie Brown, Daniel Hernandez-Stewart, Jessica Huang, Joshwa Wang, Michael Shields, Victoria Harris, Bryan Woodruff, Anirban Mazumdar, Eric Adjorlolo, Daipan Lee, Heejay Kang, Martin Segado, Sarah Shivers, Greg Sanz",
                                projCode: "data/2006/homepage/codeOfEthics/codeOfEthics.html#purple",

                                ideasPic1: "data/2006/ideas/PurpleA1.gif",
                                ideasPic2: "data/2006/ideas/PurpleA2.gif",
                                ideasPic3: "data/2006/ideas/PurpleA3.gif",
                                ideasPic4: "data/2006/ideas/PurpleB1.gif",
                                ideasPic5: "data/2006/ideas/PurpleB2.gif",
                                ideasPic6: "data/2006/ideas/PurpleB3.gif",

                                sketchName1: "Power Stove",
                                sketchName2: "StabiliTrack",
                                sketchName3: "SoloShower",
                                sketchName4: "The Hinthouse",
                                sketchPic1: "data/2006/sketch/photos/purpleA1_1.JPG",
                                sketchPic2: "data/2006/sketch/photos/purpleA1_2.JPG",
                                sketchPic3: "data/2006/sketch/photos/purpleA2_1.JPG",
                                sketchPic4: "data/2006/sketch/photos/purpleA2_2.JPG",
                                sketchPic5: "data/2006/sketch/photos/purpleB1_1.JPG",
                                sketchPic6: "data/2006/sketch/photos/purpleB1_2.JPG",
                                sketchPic7: "data/2006/sketch/photos/purpleB2_1.JPG",
                                sketchPic8: "data/2006/sketch/photos/purpleB2_2.JPG",
                                sketchMov1: "data/2006/sketch/movies/purpleA1.mov",
                                sketchMov2: "data/2006/sketch/movies/purpleA2.mov",
                                sketchMov3: "data/2006/sketch/movies/purpleB1.mov",
                                sketchMov4: "data/2006/sketch/movies/purpleB2.mov",
                                sketchSlide1: "data/2006/sketch/slides/purpleA1.pdf",
                                sketchSlide2: "data/2006/sketch/slides/purpleA2.pdf",
                                sketchSlide3: "data/2006/sketch/slides/purpleB1.pdf",
                                sketchSlide4: "data/2006/sketch/slides/purpleB2.pdf",

                                mockName1: "Stabili-track",
                                mockName2: "Solo shower",
                                mockPic1: "data/2006/mockup/photos/purpleA1.JPG",
                                mockPic2: "data/2006/mockup/photos/purpleA2.JPG",
                                mockPic3: "data/2006/mockup/photos/purpleB1.JPG",
                                mockPic4: "data/2006/mockup/photos/purpleB2.JPG",
                                mockMov1: "data/2006/mockup/movies/purpleAs.mov",
                                mockMov2: "data/2006/mockup/movies/purpleBs.mov",
                                mockSlide1: "data/2006/mockup/slides/purpleA.pdf",
                                mockSlide2: "data/2006/mockup/slides/purpleB.pdf",

                                assemblyPic1: "data/2006/assembly/purpleAssembly.jpg",
                                assemblyContract1: "data/2006/assembly/purpleContract.pdf",

                                techPic1: "data/2006/tech/photos/Purple1.JPG",
                                techPic2: "data/2006/tech/photos/Purple2.JPG",
                                techMov1: "data/2006/tech/movies/Purple.mov",
                                techContract1: null,

                                finalPic1: "data/2006/final/photos/purple1.JPG",
                                finalPic2: "data/2006/final/photos/purple2.JPG",
                                finalMov1: "data/2006/final/movies/purple.mov",
                                finalSlide1: "data/2006/final/slides/purple.pdf",
                                finalBrochure1: "data/2006/final/extras/PurpleBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "U-shower", // folder name
                                projName: "U-shower",
                                projDesc: "a bath and shower seat",
                                projColor: "orange",
                                projTeam: "Alisha Schor, Erica Pavao, Edgar Torres, Lisa Hopeman, Juan Herrera, Kurt Stiehl, Teresa Liu, Brian LaCrosse, Christina Gomez, Marcus Carson, Justin Lai, Janet Lieberman, Miguel Saez, Sharon Prange",
                                projCode: "data/2006/homepage/codeOfEthics/codeOfEthics.html#orange",

                                ideasPic1: "data/2006/ideas/OrangeA1.gif",
                                ideasPic2: "data/2006/ideas/OrangeA2.gif",
                                ideasPic3: "data/2006/ideas/OrangeA3.gif",
                                ideasPic4: "data/2006/ideas/OrangeB1.gif",
                                ideasPic5: "data/2006/ideas/OrangeB2.gif",
                                ideasPic6: "data/2006/ideas/OrangeB3.gif",

                                sketchName1: "Remote Shower Head",
                                sketchName2: "Bathtub Helper",
                                sketchName3: "Tilt-a-Toilet",
                                sketchName4: "One-Handed Scrubber",
                                sketchPic1: "data/2006/sketch/photos/orangeA1_1.JPG",
                                sketchPic2: "data/2006/sketch/photos/orangeA1_2.JPG",
                                sketchPic3: "data/2006/sketch/photos/orangeA2_1.JPG",
                                sketchPic4: "data/2006/sketch/photos/orangeA2_2.JPG",
                                sketchPic5: "data/2006/sketch/photos/orangeB1_1.JPG",
                                sketchPic6: "data/2006/sketch/photos/orangeB1_2.JPG",
                                sketchPic7: "data/2006/sketch/photos/orangeB2_1.JPG",
                                sketchPic8: "data/2006/sketch/photos/orangeB2_2.JPG",
                                sketchMov1: "data/2006/sketch/movies/orangeA1.mov",
                                sketchMov2: "data/2006/sketch/movies/orangeA2.mov",
                                sketchMov3: "data/2006/sketch/movies/orangeB1.mov",
                                sketchMov4: "data/2006/sketch/movies/orangeB2.mov",
                                sketchSlide1: "data/2006/sketch/slides/orangeA1.pdf",
                                sketchSlide2: "data/2006/sketch/slides/orangeA2.pdf",
                                sketchSlide3: "data/2006/sketch/slides/orangeB1.pdf",
                                sketchSlide4: "data/2006/sketch/slides/orangeB2.pdf",

                                mockName1: "Remote control shower head",
                                mockName2: "Tilt-a-toilet",
                                mockPic1: "data/2006/mockup/photos/orangeA1.JPG",
                                mockPic2: "data/2006/mockup/photos/orangeA2.JPG",
                                mockPic3: "data/2006/mockup/photos/orangeB1.JPG",
                                mockPic4: "data/2006/mockup/photos/orangeB2.JPG",
                                mockMov1: "data/2006/mockup/movies/orangeAs.mov",
                                mockMov2: "data/2006/mockup/movies/orangeBs.mov",
                                mockSlide1: "data/2006/mockup/slides/orangeA.pdf",
                                mockSlide2: "data/2006/mockup/slides/orangeB.pdf",

                                assemblyPic1: "data/2006/assembly/orangeAssembly.jpg",
                                assemblyContract1: "data/2006/assembly/orangeContract.pdf",

                                techPic1: "data/2006/tech/photos/Orange1.JPG",
                                techPic2: "data/2006/tech/photos/Orange2.JPG",
                                techMov1: "data/2006/tech/movies/Orange.mov",
                                techContract1: null,

                                finalPic1: "data/2006/final/photos/orange1.JPG",
                                finalPic2: "data/2006/final/photos/orange2.JPG",
                                finalMov1: "data/2006/final/movies/orange.mov",
                                finalSlide1: "data/2006/final/slides/orange.pdf",
                                finalBrochure1: "data/2006/final/extras/OrangeBfront.pdf",
                                finalBrochure2: "data/2006/final/extras/OrangeBback.pdf",
                        ],
                        [
                                projId: "Sure-step", // folder name
                                projName: "Sure step",
                                projDesc: "a braking walker",
                                projColor: "silver",
                                projTeam: "Christopher Coleman, Darragh Buckley, Ellen Cappo, Kevin DiGenova, Alfredo Morales, Michael Wrick, Ruchi Jain, Brendan Englot, Daniel Cunningham, Joseph Johnson, Michael Jensen, Jennifer Sanchez, Tania Ullah, Timothy Koch",
                                projCode: "data/2006/homepage/codeOfEthics/codeOfEthics.html#silver",

                                ideasPic1: "data/2006/ideas/SilverA1.gif",
                                ideasPic2: "data/2006/ideas/SilverA2.gif",
                                ideasPic3: "data/2006/ideas/SilverA3.gif",
                                ideasPic4: "data/2006/ideas/SilverB1.gif",
                                ideasPic5: "data/2006/ideas/SilverB2.gif",
                                ideasPic6: "data/2006/ideas/SilverB3.gif",

                                sketchName1: "Easy-Seater Toilet Assist",
                                sketchName2: "Up-Down Wheelchair",
                                sketchName3: "Medicine Bottles",
                                sketchName4: "Mobility Walker",
                                sketchPic1: "data/2006/sketch/photos/silverA1_1.JPG",
                                sketchPic2: "data/2006/sketch/photos/silverA1_2.JPG",
                                sketchPic3: "data/2006/sketch/photos/silverA2_1.JPG",
                                sketchPic4: "data/2006/sketch/photos/silverA2_2.JPG",
                                sketchPic5: "data/2006/sketch/photos/silverB1_1.JPG",
                                sketchPic6: "data/2006/sketch/photos/silverB1_2.JPG",
                                sketchPic7: "data/2006/sketch/photos/silverB2_1.JPG",
                                sketchPic8: "data/2006/sketch/photos/silverB2_2.JPG",
                                sketchMov1: "data/2006/sketch/movies/silverA1.mov",
                                sketchMov2: "data/2006/sketch/movies/silverA2.mov",
                                sketchMov3: "data/2006/sketch/movies/silverB1.mov",
                                sketchMov4: "data/2006/sketch/movies/silverB2.mov",
                                sketchSlide1: "data/2006/sketch/slides/silverA1.pdf",
                                sketchSlide2: "data/2006/sketch/slides/silverA2.pdf",
                                sketchSlide3: "data/2006/sketch/slides/silverB1.pdf",
                                sketchSlide4: "data/2006/sketch/slides/silverB2.pdf",

                                mockName1: "Up-down wheel chair",
                                mockName2: "Silver walker",
                                mockPic1: "data/2006/mockup/photos/silverA1.JPG",
                                mockPic2: "data/2006/mockup/photos/silverA2.JPG",
                                mockPic3: "data/2006/mockup/photos/silverB1.JPG",
                                mockPic4: "data/2006/mockup/photos/silverB2.JPG",
                                mockMov1: "data/2006/mockup/movies/silverAs.mov",
                                mockMov2: "data/2006/mockup/movies/silverBs.mov",
                                mockSlide1: "data/2006/mockup/slides/silverA.pdf",
                                mockSlide2: "data/2006/mockup/slides/silverB.pdf",

                                assemblyPic1: "data/2006/assembly/silverAssembly.jpg",
                                assemblyContract1: "data/2006/assembly/silverContract.pdf",

                                techPic1: "data/2006/tech/photos/Silver1.JPG",
                                techPic2: "data/2006/tech/photos/Silver2.JPG",
                                techMov1: "data/2006/tech/movies/Silver.mov",
                                techContract1: null,

                                finalPic1: "data/2006/final/photos/silver1.JPG",
                                finalPic2: "data/2006/final/photos/silver2.JPG",
                                finalMov1: "data/2006/final/movies/silver.mov",
                                finalSlide1: "data/2006/final/slides/silver.pdf",
                                finalBrochure1: "data/2006/final/extras/SilverBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Share-chair", // folder name
                                projName: "Share chair",
                                projDesc: "facilitating conversation",
                                projColor: "green",
                                projTeam: "Josh Jiricek, Jesse Marsh, Matthew Zedler, Nicola Tan, Ovid Amadi, Arthur Petron, Cynthia Walker, Etienne Toussaint, Gita Srivastava, Julian Getachew, Mark Egan, Omar R. Hernandez, Stephanie Reed, William Etheridge, Alex Cutting",
                                projCode: "data/2006/homepage/codeOfEthics/codeOfEthics.html#green",

                                ideasPic1: "data/2006/ideas/GreenA1.gif",
                                ideasPic2: "data/2006/ideas/GreenA2.gif",
                                ideasPic3: "data/2006/ideas/GreenA3.gif",
                                ideasPic4: "data/2006/ideas/GreenB1.gif",
                                ideasPic5: "data/2006/ideas/GreenB2.gif",
                                ideasPic6: "data/2006/ideas/GreenB3.gif",

                                sketchName1: "Vibration Music",
                                sketchName2: "Eye to Eye Wheelchair",
                                sketchName3: "Lifting Wheelchair",
                                sketchName4: "ShareChair",
                                sketchPic1: "data/2006/sketch/photos/greenA1_1.JPG",
                                sketchPic2: "data/2006/sketch/photos/greenA1_2.JPG",
                                sketchPic3: "data/2006/sketch/photos/greenA2_1.JPG",
                                sketchPic4: "data/2006/sketch/photos/greenA2_2.JPG",
                                sketchPic5: "data/2006/sketch/photos/greenB1_1.JPG",
                                sketchPic6: "data/2006/sketch/photos/greenB1_2.JPG",
                                sketchPic7: "data/2006/sketch/photos/greenB2_1.JPG",
                                sketchPic8: "data/2006/sketch/photos/greenB2_2.JPG",
                                sketchMov1: "data/2006/sketch/movies/greenA1.mov",
                                sketchMov2: "data/2006/sketch/movies/greenA2.mov",
                                sketchMov3: "data/2006/sketch/movies/greenB1.mov",
                                sketchMov4: "data/2006/sketch/movies/greenB2.mov",
                                sketchSlide1: "data/2006/sketch/slides/greenA1.pdf",
                                sketchSlide2: "data/2006/sketch/slides/greenA2.pdf",
                                sketchSlide3: "data/2006/sketch/slides/greenB1.pdf",
                                sketchSlide4: "data/2006/sketch/slides/greenB2.pdf",

                                mockName1: "Self-powered lifting chair",
                                mockName2: "Share chair",
                                mockPic1: "data/2006/mockup/photos/greenA1.JPG",
                                mockPic2: "data/2006/mockup/photos/greenA2.JPG",
                                mockPic3: "data/2006/mockup/photos/greenB1.JPG",
                                mockPic4: "data/2006/mockup/photos/greenB2.JPG",
                                mockMov1: "data/2006/mockup/movies/greenAs.mov",
                                mockMov2: "data/2006/mockup/movies/greenBs.mov",
                                mockSlide1: "data/2006/mockup/slides/greenA.pdf",
                                mockSlide2: "data/2006/mockup/slides/greenB.pdf",

                                assemblyPic1: "data/2006/assembly/greenAssembly.jpg",
                                assemblyContract1: "data/2006/assembly/greenContract.pdf",

                                techPic1: "data/2006/tech/photos/Green1.JPG",
                                techPic2: "data/2006/tech/photos/Green2.JPG",
                                techMov1: "data/2006/tech/movies/Green.mov",
                                techContract1: null,

                                finalPic1: "data/2006/final/photos/green1.JPG",
                                finalPic2: "data/2006/final/photos/green2.JPG",
                                finalMov1: "data/2006/final/movies/green.mov",
                                finalSlide1: "data/2006/final/slides/green.pdf",
                                finalBrochure1: null,
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Micro-golf", // folder name
                                projName: "Micro-golf",
                                projDesc: "a disability-friendly game",
                                projColor: "red",
                                projTeam: "Atiya Hasan, Brad Schiller, Devin Neal, Heather Felix, Michael Beltran, Allan Reyes, Chris Ruggiero, Sam Berberian, Ryan Bavetta, Chris Bateman, Christine Winiarz, Darren Chun, Matthew Blanco, Terianne Hall, Aron Zingman",
                                projCode: "data/2006/homepage/codeOfEthics/codeOfEthics.html#red",

                                ideasPic1: "data/2006/ideas/RedA1.gif",
                                ideasPic2: "data/2006/ideas/RedA2.gif",
                                ideasPic3: "data/2006/ideas/RedA3.gif",
                                ideasPic4: "data/2006/ideas/RedB1.gif",
                                ideasPic5: "data/2006/ideas/RedB2.gif",
                                ideasPic6: "data/2006/ideas/RedB3.gif",

                                sketchName1: "Golf Ball Launcher",
                                sketchName2: "Mini-golf Table",
                                sketchName3: "Recumbent Tricycle",
                                sketchName4: "Hands-Free Stroller",
                                sketchPic1: "data/2006/sketch/photos/redA1_1.JPG",
                                sketchPic2: "data/2006/sketch/photos/redA1_2.JPG",
                                sketchPic3: "data/2006/sketch/photos/redA2_1.JPG",
                                sketchPic4: "data/2006/sketch/photos/redA2_2.JPG",
                                sketchPic5: "data/2006/sketch/photos/redB1_1.JPG",
                                sketchPic6: "data/2006/sketch/photos/redB1_2.JPG",
                                sketchPic7: "data/2006/sketch/photos/redB2_1.JPG",
                                sketchPic8: "data/2006/sketch/photos/redB2_2.JPG",
                                sketchMov1: "data/2006/sketch/movies/redA1.mov",
                                sketchMov2: "data/2006/sketch/movies/redA2.mov",
                                sketchMov3: "data/2006/sketch/movies/redB1.mov",
                                sketchMov4: "data/2006/sketch/movies/redB2.mov",
                                sketchSlide1: "data/2006/sketch/slides/redA1.pdf",
                                sketchSlide2: "data/2006/sketch/slides/redA2.pdf",
                                sketchSlide3: "data/2006/sketch/slides/redB1.pdf",
                                sketchSlide4: "data/2006/sketch/slides/redB2.pdf",

                                mockName1: "Mini-golf table",
                                mockName2: "Hands-free stroller",
                                mockPic1: "data/2006/mockup/photos/redA1.JPG",
                                mockPic2: "data/2006/mockup/photos/redA2.JPG",
                                mockPic3: "data/2006/mockup/photos/redB1.JPG",
                                mockPic4: "data/2006/mockup/photos/redB2.JPG",
                                mockMov1: "data/2006/mockup/movies/redAs.mov",
                                mockMov2: "data/2006/mockup/movies/redBs.mov",
                                mockSlide1: "data/2006/mockup/slides/redA.pdf",
                                mockSlide2: "data/2006/mockup/slides/redB.pdf",

                                assemblyPic1: "data/2006/assembly/redAssembly.jpg",
                                assemblyContract1: "data/2006/assembly/redContract.pdf",

                                techPic1: "data/2006/tech/photos/Red1.JPG",
                                techPic2: "data/2006/tech/photos/Red2.JPG",
                                techMov1: "data/2006/tech/movies/Red.mov",
                                techContract1: null,

                                finalPic1: "data/2006/final/photos/red1.JPG",
                                finalPic2: "data/2006/final/photos/red2.JPG",
                                finalMov1: "data/2006/final/movies/red.mov",
                                finalSlide1: "data/2006/final/slides/red.pdf",
                                finalBrochure1: "data/2006/final/extras/RedBrochure.pdf",
                                finalBrochure2: null,
                        ],
                ],
        ],
]