[
        "2008": [
                themeYear: "2008", // folder name
                themeName: "Home",
                themeDesc: "Any product related to a home environment or activities within a home is potentially within scope. Target customers may include those living in developed or developing countries.",
                highlights: [
                        [ linkLabel: "Home page and slide show", linkUrl: "data/2008/homepage/index.html" ],
                        [ linkLabel: "Student tribute", linkUrl: "data/2008/highlights/studentTribute-NOnames.mov", onClick: "window.open('data/2008/highlights/studentTribute-NOnames.mov', 'movieWin', 'width=340,height=290,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Walking on water", linkUrl: "data/2008/highlights/WOW!.mov", onClick: "window.open('data/2008/highlights/WOW!.mov', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Gorilla in the classroom", linkUrl: "data/2008/highlights/largebanana.mov", onClick: "window.open('data/2008/highlights/largebanana.mov', 'movieWin', 'width=500,height=410,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "TechTV video about 6dot braille labeler", linkUrl: "http://techtv.mit.edu/collections/lemelson-mit/videos/4932-braille-labeler-invention" ],
                ],
                highlightDividerIndexes:  [ 1 ],
                sketchMovWidth: 320,
                sketchMovHeight: 256,
                mockMovWidth: 320,
                mockMovHeight: 256,
                techMovWidth: 320,
                techMovHeight: 256,
                finalMovWidth: 320,
                finalMovHeight: 256,
                picWidth: 240, // picHeight is determined dynamically
                projects: [
                        [
                                projId: "DOTit", // folder name
                                projName: "DOTit",
                                projDesc: "electric Braille labeler",
                                projColor: "blue",
                                projTeam: "Andrew Bishara, Adelaide Calbry-Muzyka, Kwame Hall, Josh Karges, Michelle Lustrino, Nicole O'Keeffe, Sam Phillips, Sarah Shieh, Xiao Wei Chen, Isa Castro, Wenxian Hong, Jennifer Moore, Karina Pikhart, Rachel Tatem, Jodie Wu",
                                projCode: "data/2008/homepage/codeOfEthics/codeOfEthics.html#blue",

                                ideasPic1: "data/2008/ideas/BlueA1.jpg",
                                ideasPic2: "data/2008/ideas/BlueA2.jpg",
                                ideasPic3: "data/2008/ideas/BlueA3.jpg",
                                ideasPic4: "data/2008/ideas/BlueB1.jpg",
                                ideasPic5: "data/2008/ideas/BlueB2.jpg",
                                ideasPic6: "data/2008/ideas/BlueB3.jpg",

                                sketchName1: "StairWalker",
                                sketchName2: "Wheelchair helper",
                                sketchName3: "ejectAoven",
                                sketchName4: "liftAcart",
                                sketchPic1: "data/2008/sketch/photos/blueA1_1.JPG",
                                sketchPic2: "data/2008/sketch/photos/blueA1_2.JPG",
                                sketchPic3: "data/2008/sketch/photos/blueA2_1.JPG",
                                sketchPic4: "data/2008/sketch/photos/blueA2_2.JPG",
                                sketchPic5: "data/2008/sketch/photos/blueB1_1.JPG",
                                sketchPic6: "data/2008/sketch/photos/blueB1_2.JPG",
                                sketchPic7: "data/2008/sketch/photos/blueB2_1.JPG",
                                sketchPic8: "data/2008/sketch/photos/blueB2_2.JPG",
                                sketchMov1: "data/2008/sketch/movies/blueA1.mov",
                                sketchMov2: "data/2008/sketch/movies/blueA2.mov",
                                sketchMov3: "data/2008/sketch/movies/blueB1.mov",
                                sketchMov4: "data/2008/sketch/movies/blueB2.mov",
                                sketchSlide1: "data/2008/sketch/slides/blueA1.pdf",
                                sketchSlide2: "data/2008/sketch/slides/blueA2.pdf",
                                sketchSlide3: "data/2008/sketch/slides/blueB1.pdf",
                                sketchSlide4: "data/2008/sketch/slides/blueB2.pdf",

                                mockName1: "wheelchairASSIST",
                                mockName2: "iDot",
                                mockPic1: "data/2008/mockup/photos/blueA1.JPG",
                                mockPic2: "data/2008/mockup/photos/blueA2.JPG",
                                mockPic3: "data/2008/mockup/photos/blueB1.JPG",
                                mockPic4: "data/2008/mockup/photos/blueB2.JPG",
                                mockMov1: "data/2008/mockup/movies/blueAs.mov",
                                mockMov2: "data/2008/mockup/movies/blueBs.mov",
                                mockSlide1: "data/2008/mockup/slides/blueA.pdf",
                                mockSlide2: "data/2008/mockup/slides/blueB.pdf",

                                assemblyPic1: "data/2008/assembly/blueAssembly.jpg",
                                assemblyContract1: "data/2008/assembly/blueContract.pdf",

                                techPic1: "data/2008/tech/photos/Blue1.JPG",
                                techPic2: "data/2008/tech/photos/Blue2.JPG",
                                techMov1: "data/2008/tech/movies/Blue.mov",
                                techContract1: null,

                                finalPic1: "data/2008/final/photos/blue1.JPG",
                                finalPic2: "data/2008/final/photos/blue2.JPG",
                                finalMov1: "data/2008/final/movies/blue.mov",
                                finalSlide1: "data/2008/final/slides/blue.pdf",
                                finalBrochure1: "data/2008/final/extras/blueBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "ModuWall", // folder name
                                projName: "ModuWall",
                                projDesc: " modular temporary wall system",
                                projColor: "yellow",
                                projTeam: "Yermie Cohen, Esther Hu, Eugene Jang, Laura Nicholson, Rane Nolan, Alberto Perez, Kelly Rockwell, Fiona Yuen, Sherife AbdelMessih, Alex Guerra, Michael Johnson, Caitrin Jones, Helen O'Keefe, Siamrut Patanavanich, Jeremy Richardson, Karlen Ruleman",
                                projCode: "data/2008/homepage/codeOfEthics/codeOfEthics.html#yellow",

                                ideasPic1: "data/2008/ideas/YellowA1.jpg",
                                ideasPic2: "data/2008/ideas/YellowA2.jpg",
                                ideasPic3: "data/2008/ideas/YellowA3.jpg",
                                ideasPic4: "data/2008/ideas/YellowB1.jpg",
                                ideasPic5: "data/2008/ideas/YellowB2.jpg",
                                ideasPic6: "data/2008/ideas/YellowB3.jpg",

                                sketchName1: "Bike rack",
                                sketchName2: "Mobile furniture",
                                sketchName3: "Movable walls",
                                sketchName4: "Lazy Susan fridge",
                                sketchPic1: "data/2008/sketch/photos/yellowA1_1.JPG",
                                sketchPic2: "data/2008/sketch/photos/yellowA1_2.JPG",
                                sketchPic3: "data/2008/sketch/photos/yellowA2_1.JPG",
                                sketchPic4: "data/2008/sketch/photos/yellowA2_2.JPG",
                                sketchPic5: "data/2008/sketch/photos/yellowB1_1.JPG",
                                sketchPic6: "data/2008/sketch/photos/yellowB1_2.JPG",
                                sketchPic7: "data/2008/sketch/photos/yellowB2_1.JPG",
                                sketchPic8: "data/2008/sketch/photos/yellowB2_2.JPG",
                                sketchMov1: "data/2008/sketch/movies/yellowA1.mov",
                                sketchMov2: "data/2008/sketch/movies/yellowA2.mov",
                                sketchMov3: "data/2008/sketch/movies/yellowB1.mov",
                                sketchMov4: "data/2008/sketch/movies/yellowB2.mov",
                                sketchSlide1: "data/2008/sketch/slides/yellowA1.pdf",
                                sketchSlide2: "data/2008/sketch/slides/yellowA2.pdf",
                                sketchSlide3: "data/2008/sketch/slides/yellowB1.pdf",
                                sketchSlide4: "data/2008/sketch/slides/yellowB2.pdf",

                                mockName1: "Movable Walls",
                                mockName2: "Lazy Susan Refrigerator",
                                mockPic1: "data/2008/mockup/photos/yellowA1.JPG",
                                mockPic2: "data/2008/mockup/photos/yellowA2.JPG",
                                mockPic3: "data/2008/mockup/photos/yellowB1.JPG",
                                mockPic4: "data/2008/mockup/photos/yellowB2.JPG",
                                mockMov1: "data/2008/mockup/movies/yellowAs.mov",
                                mockMov2: "data/2008/mockup/movies/yellowBs.mov",
                                mockSlide1: "data/2008/mockup/slides/yellowA.pdf",
                                mockSlide2: "data/2008/mockup/slides/yellowB.pdf",

                                assemblyPic1: "data/2008/assembly/yellowAssembly.jpg",
                                assemblyContract1: "data/2008/assembly/yellowContract.pdf",

                                techPic1: "data/2008/tech/photos/Yellow1.JPG",
                                techPic2: "data/2008/tech/photos/Yellow2.JPG",
                                techMov1: "data/2008/tech/movies/Yellow.mov",
                                techContract1: null,

                                finalPic1: "data/2008/final/photos/yellow1.JPG",
                                finalPic2: "data/2008/final/photos/yellow2.JPG",
                                finalMov1: "data/2008/final/movies/yellow.mov",
                                finalSlide1: "data/2008/final/slides/yellow.pdf",
                                finalBrochure1: "data/2008/final/extras/yellowBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Point-Guard", // folder name
                                projName: "Point Guard",
                                projDesc: "basketball return system",
                                projColor: "purple",
                                projTeam: "Brian Demers, Brittany Guyer, Rob Hummel, Zack Jackowski, Jarrell Johnson, Dan Klenk, Jason Ku, Adrienne Watral, Sarah Cole, David Schafer, Jeremy James, John Vincent, Jake Latcham, Paul Nikandrou, Jewel Sharpe, Julia Zimmerman",
                                projCode: "data/2008/homepage/codeOfEthics/codeOfEthics.html#purple",

                                ideasPic1: "data/2008/ideas/PurpleA1.jpg",
                                ideasPic2: "data/2008/ideas/PurpleA2.jpg",
                                ideasPic3: "data/2008/ideas/PurpleA3.jpg",
                                ideasPic4: "data/2008/ideas/PurpleB1.jpg",
                                ideasPic5: "data/2008/ideas/PurpleB2.jpg",
                                ideasPic6: "data/2008/ideas/PurpleB3.jpg",

                                sketchName1: "Truck n'Dump",
                                sketchName2: "Aerobi-Dog",
                                sketchName3: "Rock slide",
                                sketchName4: "PointGuard",
                                sketchPic1: "data/2008/sketch/photos/purpleA1_1.JPG",
                                sketchPic2: "data/2008/sketch/photos/purpleA1_2.JPG",
                                sketchPic3: "data/2008/sketch/photos/purpleA2_1.JPG",
                                sketchPic4: "data/2008/sketch/photos/purpleA2_2.JPG",
                                sketchPic5: "data/2008/sketch/photos/purpleB1_1.JPG",
                                sketchPic6: "data/2008/sketch/photos/purpleB1_2.JPG",
                                sketchPic7: "data/2008/sketch/photos/purpleB2_1.JPG",
                                sketchPic8: "data/2008/sketch/photos/purpleB2_2.JPG",
                                sketchMov1: "data/2008/sketch/movies/purpleA1.mov",
                                sketchMov2: "data/2008/sketch/movies/purpleA2.mov",
                                sketchMov3: "data/2008/sketch/movies/purpleB1.mov",
                                sketchMov4: "data/2008/sketch/movies/purpleB2.mov",
                                sketchSlide1: "data/2008/sketch/slides/purpleA1.pdf",
                                sketchSlide2: "data/2008/sketch/slides/purpleA2.pdf",
                                sketchSlide3: "data/2008/sketch/slides/purpleB1.pdf",
                                sketchSlide4: "data/2008/sketch/slides/purpleB2.pdf",

                                mockName1: "The Big Haul",
                                mockName2: "PointGuard",
                                mockPic1: "data/2008/mockup/photos/purpleA1.JPG",
                                mockPic2: "data/2008/mockup/photos/purpleA2.JPG",
                                mockPic3: "data/2008/mockup/photos/purpleB1.JPG",
                                mockPic4: "data/2008/mockup/photos/purpleB2.JPG",
                                mockMov1: "data/2008/mockup/movies/purpleAs.mov",
                                mockMov2: "data/2008/mockup/movies/purpleBs.mov",
                                mockSlide1: "data/2008/mockup/slides/purpleA.pdf",
                                mockSlide2: "data/2008/mockup/slides/purpleB.pdf",

                                assemblyPic1: "data/2008/assembly/purpleAssembly.jpg",
                                assemblyContract1: "data/2008/assembly/purpleContract.pdf",

                                techPic1: "data/2008/tech/photos/Purple1.JPG",
                                techPic2: "data/2008/tech/photos/Purple2.JPG",
                                techMov1: "data/2008/tech/movies/Purple.mov",
                                techContract1: null,

                                finalPic1: "data/2008/final/photos/purple1.JPG",
                                finalPic2: "data/2008/final/photos/purple2.JPG",
                                finalMov1: "data/2008/final/movies/purple.mov",
                                finalSlide1: "data/2008/final/slides/purple.pdf",
                                finalBrochure1: "data/2008/final/extras/purpleBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "thermoSmart", // folder name
                                projName: "thermoSmart",
                                projDesc: "forced air grate system",
                                projColor: "orange",
                                projTeam: "Paul Blascovich, Shreya Dave, Conor Lenahan, Jacob Levinson, Aiko Nakano, Rebecca Smith, Celeste Wallace, Peter Wellings, Jason Chan, Rahel Eisenberg, Daniel Lopez, Sara Segal, Tiffany Tseng, Robert Utz, Alice Yeh, Brian Syverud, Stephen Young",
                                projCode: "data/2008/homepage/codeOfEthics/codeOfEthics.html#orange",

                                ideasPic1: "data/2008/ideas/OrangeA1.jpg",
                                ideasPic2: "data/2008/ideas/OrangeA2.jpg",
                                ideasPic3: "data/2008/ideas/OrangeA3.jpg",
                                ideasPic4: "data/2008/ideas/OrangeB1.jpg",
                                ideasPic5: "data/2008/ideas/OrangeB2.jpg",
                                ideasPic6: "data/2008/ideas/OrangeB3.jpg",

                                sketchName1: "Flywheel ventilation",
                                sketchName2: "HVAC tracker",
                                sketchName3: "Vent-elation",
                                sketchName4: "Zephyr Dry-er",
                                sketchPic1: "data/2008/sketch/photos/orangeA1_1.JPG",
                                sketchPic2: "data/2008/sketch/photos/orangeA1_2.JPG",
                                sketchPic3: "data/2008/sketch/photos/orangeA2_1.JPG",
                                sketchPic4: "data/2008/sketch/photos/orangeA2_2.JPG",
                                sketchPic5: "data/2008/sketch/photos/orangeB1_1.JPG",
                                sketchPic6: "data/2008/sketch/photos/orangeB1_2.JPG",
                                sketchPic7: "data/2008/sketch/photos/orangeB2_1.JPG",
                                sketchPic8: "data/2008/sketch/photos/orangeB2_2.JPG",
                                sketchMov1: "data/2008/sketch/movies/orangeA1.mov",
                                sketchMov2: "data/2008/sketch/movies/orangeA2.mov",
                                sketchMov3: "data/2008/sketch/movies/orangeB1.mov",
                                sketchMov4: "data/2008/sketch/movies/orangeB2.mov",
                                sketchSlide1: "data/2008/sketch/slides/orangeA1.pdf",
                                sketchSlide2: "data/2008/sketch/slides/orangeA2.pdf",
                                sketchSlide3: "data/2008/sketch/slides/orangeB1.pdf",
                                sketchSlide4: "data/2008/sketch/slides/orangeB2.pdf",

                                mockName1: "HVAC Tracker",
                                mockName2: "Zephyr Dryer",
                                mockPic1: "data/2008/mockup/photos/orangeA1.JPG",
                                mockPic2: "data/2008/mockup/photos/orangeA2.JPG",
                                mockPic3: "data/2008/mockup/photos/orangeB1.JPG",
                                mockPic4: "data/2008/mockup/photos/orangeB2.JPG",
                                mockMov1: "data/2008/mockup/movies/orangeAs.mov",
                                mockMov2: "data/2008/mockup/movies/orangeBs.mov",
                                mockSlide1: "data/2008/mockup/slides/orangeA.pdf",
                                mockSlide2: "data/2008/mockup/slides/orangeB.pdf",

                                assemblyPic1: "data/2008/assembly/orangeAssembly.jpg",
                                assemblyContract1: "data/2008/assembly/orangeContract.pdf",

                                techPic1: "data/2008/tech/photos/Orange1.JPG",
                                techPic2: "data/2008/tech/photos/Orange2.JPG",
                                techMov1: "data/2008/tech/movies/Orange.mov",
                                techContract1: null,

                                finalPic1: "data/2008/final/photos/orange1.JPG",
                                finalPic2: "data/2008/final/photos/orange2.JPG",
                                finalMov1: "data/2008/final/movies/orange.mov",
                                finalSlide1: "data/2008/final/slides/orange.pdf",
                                finalBrochure1: "data/2008/final/extras/orangeBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Infinite-Range", // folder name
                                projName: "Infinite Range",
                                projDesc: "a sensing cook top",
                                projColor: "silver",
                                projTeam: "Mario Bollini, Jennifer Doyle, Jeremy Franklin, Luke Johnson, Amanda Maguire, Sean Mellott, Adam Paxson, Nate Sharpe, Michael Carvajal, Terrence Green, Sara Gutierrez, Mike Kerekes, Hassan Mohamed, Sarah Reed, Hector Vargas, Yan Wang",
                                projCode: "data/2008/homepage/codeOfEthics/codeOfEthics.html#silver",

                                ideasPic1: "data/2008/ideas/SilverA1.jpg",
                                ideasPic2: "data/2008/ideas/SilverA2.jpg",
                                ideasPic3: "data/2008/ideas/SilverA3.jpg",
                                ideasPic4: "data/2008/ideas/SilverB1.jpg",
                                ideasPic5: "data/2008/ideas/SilverB2.jpg",
                                ideasPic6: "data/2008/ideas/SilverB3.jpg",

                                sketchName1: "Break fast",
                                sketchName2: "Unlimited range",
                                sketchName3: "EasyFridge",
                                sketchName4: "Portable kitchen",
                                sketchPic1: "data/2008/sketch/photos/silverA1_1.JPG",
                                sketchPic2: "data/2008/sketch/photos/silverA1_2.JPG",
                                sketchPic3: "data/2008/sketch/photos/silverA2_1.JPG",
                                sketchPic4: "data/2008/sketch/photos/silverA2_2.JPG",
                                sketchPic5: "data/2008/sketch/photos/silverB1_1.JPG",
                                sketchPic6: "data/2008/sketch/photos/silverB1_2.JPG",
                                sketchPic7: "data/2008/sketch/photos/silverB2_1.JPG",
                                sketchPic8: "data/2008/sketch/photos/silverB2_2.JPG",
                                sketchMov1: "data/2008/sketch/movies/silverA1.mov",
                                sketchMov2: "data/2008/sketch/movies/silverA2.mov",
                                sketchMov3: "data/2008/sketch/movies/silverB1.mov",
                                sketchMov4: "data/2008/sketch/movies/silverB2.mov",
                                sketchSlide1: "data/2008/sketch/slides/silverA1.pdf",
                                sketchSlide2: "data/2008/sketch/slides/silverA2.pdf",
                                sketchSlide3: "data/2008/sketch/slides/silverB1.pdf",
                                sketchSlide4: "data/2008/sketch/slides/silverB2.pdf",

                                mockName1: "Unlimited Range",
                                mockName2: "Baking Buddy",
                                mockPic1: "data/2008/mockup/photos/silverA1.JPG",
                                mockPic2: "data/2008/mockup/photos/silverA2.JPG",
                                mockPic3: "data/2008/mockup/photos/silverB1.JPG",
                                mockPic4: "data/2008/mockup/photos/silverB2.JPG",
                                mockMov1: "data/2008/mockup/movies/silverAs.mov",
                                mockMov2: "data/2008/mockup/movies/silverBs.mov",
                                mockSlide1: "data/2008/mockup/slides/silverA.pdf",
                                mockSlide2: "data/2008/mockup/slides/silverB.pdf",

                                assemblyPic1: "data/2008/assembly/silverAssembly.jpg",
                                assemblyContract1: "data/2008/assembly/silverContract.pdf",

                                techPic1: "data/2008/tech/photos/Silver1.JPG",
                                techPic2: "data/2008/tech/photos/Silver2.JPG",
                                techMov1: "data/2008/tech/movies/Silver.mov",
                                techContract1: null,

                                finalPic1: "data/2008/final/photos/silver1.JPG",
                                finalPic2: "data/2008/final/photos/silver2.JPG",
                                finalMov1: "data/2008/final/movies/silver.mov",
                                finalSlide1: "data/2008/final/slides/silver.pdf",
                                finalBrochure1: "data/2008/final/extras/silverBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "elika", // folder name
                                projName: "elika",
                                projDesc: "high tech coffee table",
                                projColor: "green",
                                projTeam: "Rangel Dokov, Cyril Koniski, Ming Leong, Jared Sartee, Katie Stanchak, Phillip Vasquez, Yuki Wikman, Terance Neal, Eddie Lei, Shamus Cunningham, David Hill, Fiona Hughes, Andrew Leone, Kathryn Shroyer, Geoff Tsai, Cindy Wang, Yifei Wu, Cathy Mancuso",
                                projCode: "data/2008/homepage/codeOfEthics/codeOfEthics.html#green",

                                ideasPic1: "data/2008/ideas/GreenA1.jpg",
                                ideasPic2: "data/2008/ideas/GreenA2.jpg",
                                ideasPic3: "data/2008/ideas/GreenA3.jpg",
                                ideasPic4: "data/2008/ideas/GreenB1.jpg",
                                ideasPic5: "data/2008/ideas/GreenB2.jpg",
                                ideasPic6: "data/2008/ideas/GreenB3.jpg",

                                sketchName1: "Express-o table",
                                sketchName2: "Double-Desk",
                                sketchName3: "Mesh couch",
                                sketchName4: "Foosball pool table",
                                sketchPic1: "data/2008/sketch/photos/greenA1_1.JPG",
                                sketchPic2: "data/2008/sketch/photos/greenA1_2.JPG",
                                sketchPic3: "data/2008/sketch/photos/greenA2_1.JPG",
                                sketchPic4: "data/2008/sketch/photos/greenA2_2.JPG",
                                sketchPic5: "data/2008/sketch/photos/greenB1_1.JPG",
                                sketchPic6: "data/2008/sketch/photos/greenB1_2.JPG",
                                sketchPic7: "data/2008/sketch/photos/greenB2_1.JPG",
                                sketchPic8: "data/2008/sketch/photos/greenB2_2.JPG",
                                sketchMov1: "data/2008/sketch/movies/greenA1.mov",
                                sketchMov2: "data/2008/sketch/movies/greenA2.mov",
                                sketchMov3: "data/2008/sketch/movies/greenB1.mov",
                                sketchMov4: "data/2008/sketch/movies/greenB2.mov",
                                sketchSlide1: "data/2008/sketch/slides/greenA1.pdf",
                                sketchSlide2: "data/2008/sketch/slides/greenA2.pdf",
                                sketchSlide3: "data/2008/sketch/slides/greenB1.pdf",
                                sketchSlide4: "data/2008/sketch/slides/greenB2.pdf",

                                mockName1: "Double desk",
                                mockName2: "EspressO table",
                                mockPic1: "data/2008/mockup/photos/greenA1.JPG",
                                mockPic2: "data/2008/mockup/photos/greenA2.JPG",
                                mockPic3: "data/2008/mockup/photos/greenB1.JPG",
                                mockPic4: "data/2008/mockup/photos/greenB2.JPG",
                                mockMov1: "data/2008/mockup/movies/greenAs.mov",
                                mockMov2: "data/2008/mockup/movies/greenBs.mov",
                                mockSlide1: "data/2008/mockup/slides/greenA.pdf",
                                mockSlide2: "data/2008/mockup/slides/greenB.pdf",

                                assemblyPic1: "data/2008/assembly/greenAssembly.jpg",
                                assemblyContract1: "data/2008/assembly/greenContract.pdf",

                                techPic1: "data/2008/tech/photos/Green1.JPG",
                                techPic2: "data/2008/tech/photos/Green2.JPG",
                                techMov1: "data/2008/tech/movies/Green.mov",
                                techContract1: null,

                                finalPic1: "data/2008/final/photos/green1.JPG",
                                finalPic2: "data/2008/final/photos/green2.JPG",
                                finalMov1: "data/2008/final/movies/green.mov",
                                finalSlide1: "data/2008/final/slides/green.pdf",
                                finalBrochure1: "data/2008/final/extras/greenBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Fire-Safe-Microwave", // folder name
                                projName: "Fire Safe Microwave",
                                projDesc: "Fire Safe Microwave",
                                projColor: "red",
                                projTeam: "Kaitlyn Becker, Nikolai Begg, Jackie Kunkel, Nick Labounty, Shannon Roberts, Tasha Thomas, Tim Villabona, Reid Allen, Deke Hu, Corinna Hui, Kashika Sharma, Michael Stern, Orian Welling, Ross Wendell",
                                projCode: "data/2008/homepage/codeOfEthics/codeOfEthics.html#red",

                                ideasPic1: "data/2008/ideas/RedA1.jpg",
                                ideasPic2: "data/2008/ideas/RedA2.jpg",
                                ideasPic3: "data/2008/ideas/RedA3.jpg",
                                ideasPic4: "data/2008/ideas/RedB1.jpg",
                                ideasPic5: "data/2008/ideas/RedB2.jpg",
                                ideasPic6: "data/2008/ideas/RedB3.jpg",

                                sketchName1: "Adjustable height crib",
                                sketchName2: "People Lift",
                                sketchName3: "Collapsible lockable tent",
                                sketchName4: "Microwave metal detector",
                                sketchPic1: "data/2008/sketch/photos/redA1_1.JPG",
                                sketchPic2: "data/2008/sketch/photos/redA1_2.JPG",
                                sketchPic3: "data/2008/sketch/photos/redA2_1.JPG",
                                sketchPic4: "data/2008/sketch/photos/redA2_2.JPG",
                                sketchPic5: "data/2008/sketch/photos/redB1_1.JPG",
                                sketchPic6: "data/2008/sketch/photos/redB1_2.JPG",
                                sketchPic7: "data/2008/sketch/photos/redB2_1.JPG",
                                sketchPic8: "data/2008/sketch/photos/redB2_2.JPG",
                                sketchMov1: "data/2008/sketch/movies/redA1.mov",
                                sketchMov2: "data/2008/sketch/movies/redA2.mov",
                                sketchMov3: "data/2008/sketch/movies/redB1.mov",
                                sketchMov4: "data/2008/sketch/movies/redB2.mov",
                                sketchSlide1: "data/2008/sketch/slides/redA1.pdf",
                                sketchSlide2: "data/2008/sketch/slides/redA2.pdf",
                                sketchSlide3: "data/2008/sketch/slides/redB1.pdf",
                                sketchSlide4: "data/2008/sketch/slides/redB2.pdf",

                                mockName1: "Adjustable Height Crib",
                                mockName2: "Fire Safe Microwave",
                                mockPic1: "data/2008/mockup/photos/redA1.JPG",
                                mockPic2: "data/2008/mockup/photos/redA2.JPG",
                                mockPic3: "data/2008/mockup/photos/redB1.JPG",
                                mockPic4: "data/2008/mockup/photos/redB2.JPG",
                                mockMov1: "data/2008/mockup/movies/redAs.mov",
                                mockMov2: "data/2008/mockup/movies/redBs.mov",
                                mockSlide1: "data/2008/mockup/slides/redA.pdf",
                                mockSlide2: "data/2008/mockup/slides/redB.pdf",

                                assemblyPic1: "data/2008/assembly/redAssembly.jpg",
                                assemblyContract1: "data/2008/assembly/redContract.pdf",

                                techPic1: "data/2008/tech/photos/Red1.JPG",
                                techPic2: "data/2008/tech/photos/Red2.JPG",
                                techMov1: "data/2008/tech/movies/Red.mov",
                                techContract1: null,

                                finalPic1: "data/2008/final/photos/red1.JPG",
                                finalPic2: "data/2008/final/photos/red2.JPG",
                                finalMov1: "data/2008/final/movies/red.mov",
                                finalSlide1: "data/2008/final/slides/red.pdf",
                                finalBrochure1: "data/2008/final/extras/redBrochure.pdf",
                                finalBrochure2: null,
                        ],
                ],
        ],
]