[
        "2007": [
                themeYear: "2007", // folder name
                themeName: "Reduce, reuse, recycle.",
                themeDesc: "Products that use less or pollute less. Products designed for reuse or that incorporate reused or remanufactured goods. Products that are designed to be highly recyclable or use recycled materials.",
                highlights: [
                        [ linkLabel: "Home page and slide show", linkUrl: "data/2007/homepage/index.html" ],
                        [ linkLabel: "Student tribute", linkUrl: "data/2007/highlights/studentTribute.mov", onClick: "window.open('data/2007/highlights/studentTribute.mov', 'movieWin', 'width=660,height=510,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Gorilla in the classroom", linkUrl: "data/2007/highlights/gorilla.mov", onClick: "window.open('data/2007/highlights/gorilla.mov', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "MIT news story about the projects", linkUrl: "http://web.mit.edu/newsoffice/2007/product-design-1218.html" ],
                ],
                highlightDividerIndexes:  [ 1 ],
                sketchMovWidth: 320,
                sketchMovHeight: 256,
                mockMovWidth: 320,
                mockMovHeight: 256,
                techMovWidth: 320,
                techMovHeight: 256,
                finalMovWidth: 320,
                finalMovHeight: 256,
                picWidth: 240, // picHeight is determined dynamically
                projects: [
                        [
                                projId: "Solar-Recycl-o-Sort", // folder name
                                projName: "Solar Recycl-o-Sort",
                                projDesc: "Solar bottle sorter",
                                projColor: "blue",
                                projTeam: "Ali Alhassani, Amanda Poteet, Barnett Koryan, John Vivian, Joyce Gallagher, Nancy Diaz, Samuel Jasinski, Yi Chen, Benjamin Pope, Cynthia Lin, David Kalk, Jonathan Schechter, Katherine Weston, Mark Spadafora, Rosa Rodriguez, Yunzhi Wang",
                                projCode: "data/2007/homepage/codeOfEthics/codeOfEthics.html#blue",

                                ideasPic1: "data/2007/ideas/BlueA1.gif",
                                ideasPic2: "data/2007/ideas/BlueA2.gif",
                                ideasPic3: "data/2007/ideas/BlueA3.gif",
                                ideasPic4: "data/2007/ideas/BlueB1.gif",
                                ideasPic5: "data/2007/ideas/BlueB2.gif",
                                ideasPic6: "data/2007/ideas/BlueB3.gif",

                                sketchName1: "Power exercise bike",
                                sketchName2: "Solar recycl-o-sort",
                                sketchName3: "Motion sensor switch plate",
                                sketchName4: "Water-powered generator",
                                sketchPic1: "data/2007/sketch/photos/blueA1_1.JPG",
                                sketchPic2: "data/2007/sketch/photos/blueA1_2.JPG",
                                sketchPic3: "data/2007/sketch/photos/blueA2_1.JPG",
                                sketchPic4: "data/2007/sketch/photos/blueA2_2.JPG",
                                sketchPic5: "data/2007/sketch/photos/blueB1_1.JPG",
                                sketchPic6: "data/2007/sketch/photos/blueB1_2.JPG",
                                sketchPic7: "data/2007/sketch/photos/blueB2_1.JPG",
                                sketchPic8: "data/2007/sketch/photos/blueB2_2.JPG",
                                sketchMov1: "data/2007/sketch/movies/blueA1.mov",
                                sketchMov2: "data/2007/sketch/movies/blueA2.mov",
                                sketchMov3: "data/2007/sketch/movies/blueB1.mov",
                                sketchMov4: "data/2007/sketch/movies/blueB2.mov",
                                sketchSlide1: "data/2007/sketch/slides/blueA1.pdf",
                                sketchSlide2: "data/2007/sketch/slides/blueA2.pdf",
                                sketchSlide3: "data/2007/sketch/slides/blueB1.pdf",
                                sketchSlide4: "data/2007/sketch/slides/blueB2.pdf",

                                mockName1: "Solar Recycl-O-Sort",
                                mockName2: "Grey Water Management",
                                mockPic1: "data/2007/mockup/photos/blueA1.JPG",
                                mockPic2: "data/2007/mockup/photos/blueA2.JPG",
                                mockPic3: "data/2007/mockup/photos/blueB1.JPG",
                                mockPic4: "data/2007/mockup/photos/blueB2.JPG",
                                mockMov1: "data/2007/mockup/movies/blueAs.mov",
                                mockMov2: "data/2007/mockup/movies/blueBs.mov",
                                mockSlide1: "data/2007/mockup/slides/blueA.pdf",
                                mockSlide2: "data/2007/mockup/slides/blueB.pdf",

                                assemblyPic1: "data/2007/assembly/blueAssembly.jpg",
                                assemblyContract1: "data/2007/assembly/blueContract.pdf",

                                techPic1: "data/2007/tech/photos/Blue1.JPG",
                                techPic2: "data/2007/tech/photos/Blue2.JPG",
                                techMov1: "data/2007/tech/movies/Blue.mov",
                                techContract1: null,

                                finalPic1: "data/2007/final/photos/blue1.JPG",
                                finalPic2: "data/2007/final/photos/blue2.JPG",
                                finalMov1: "data/2007/final/movies/blue.mov",
                                finalSlide1: "data/2007/final/slides/blue.pdf",
                                finalBrochure1: "data/2007/final/extras/blueBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "IntelliShower", // folder name
                                projName: "IntelliShower",
                                projDesc: " A water-saving shower",
                                projColor: "yellow",
                                projTeam: "Andrew Hurwich, Chihjiun Yeh, Diego A. Melani, Ellann Cohen, Kristina Haller, Lisandro Quinones, Nathan Wang, Stuart Rossen, Tristan Lang, Asiri Ediriwickrema, Edward Summers, Holly B. Laird, Iliya Tsekov, Yamilee Toussaint, Ryan Dean, Sergio Navarro, Shane Treadway, Yangfang Wang",
                                projCode: "data/2007/homepage/codeOfEthics/codeOfEthics.html#yellow",

                                ideasPic1: "data/2007/ideas/YellowA1.gif",
                                ideasPic2: "data/2007/ideas/YellowA2.gif",
                                ideasPic3: "data/2007/ideas/YellowA3.gif",
                                ideasPic4: "data/2007/ideas/YellowB1.gif",
                                ideasPic5: "data/2007/ideas/YellowB2.gif",
                                ideasPic6: "data/2007/ideas/YellowB3.gif",

                                sketchName1: "Smart shower",
                                sketchName2: "Veggie washer",
                                sketchName3: "Reuse.A.Mug",
                                sketchName4: "Aquatron filter",
                                sketchPic1: "data/2007/sketch/photos/yellowA1_1.JPG",
                                sketchPic2: "data/2007/sketch/photos/yellowA1_2.JPG",
                                sketchPic3: "data/2007/sketch/photos/yellowA2_1.JPG",
                                sketchPic4: "data/2007/sketch/photos/yellowA2_2.JPG",
                                sketchPic5: "data/2007/sketch/photos/yellowB1_1.JPG",
                                sketchPic6: "data/2007/sketch/photos/yellowB1_2.JPG",
                                sketchPic7: "data/2007/sketch/photos/yellowB2_1.JPG",
                                sketchPic8: "data/2007/sketch/photos/yellowB2_2.JPG",
                                sketchMov1: "data/2007/sketch/movies/yellowA1.mov",
                                sketchMov2: "data/2007/sketch/movies/yellowA2.mov",
                                sketchMov3: "data/2007/sketch/movies/yellowB1.mov",
                                sketchMov4: "data/2007/sketch/movies/yellowB2.mov",
                                sketchSlide1: "data/2007/sketch/slides/yellowA1.pdf",
                                sketchSlide2: "data/2007/sketch/slides/yellowA2.pdf",
                                sketchSlide3: "data/2007/sketch/slides/yellowB1.pdf",
                                sketchSlide4: "data/2007/sketch/slides/yellowB2.pdf",

                                mockName1: "Smart Shower",
                                mockName2: "Reuse-A-Mug",
                                mockPic1: "data/2007/mockup/photos/yellowA1.JPG",
                                mockPic2: "data/2007/mockup/photos/yellowA2.JPG",
                                mockPic3: "data/2007/mockup/photos/yellowB1.JPG",
                                mockPic4: "data/2007/mockup/photos/yellowB2.JPG",
                                mockMov1: "data/2007/mockup/movies/yellowAs.mov",
                                mockMov2: "data/2007/mockup/movies/yellowBs.mov",
                                mockSlide1: "data/2007/mockup/slides/yellowA.pdf",
                                mockSlide2: "data/2007/mockup/slides/yellowB.pdf",

                                assemblyPic1: "data/2007/assembly/yellowAssembly.jpg",
                                assemblyContract1: "data/2007/assembly/yellowContract.pdf",

                                techPic1: "data/2007/tech/photos/Yellow1.JPG",
                                techPic2: "data/2007/tech/photos/Yellow2.JPG",
                                techMov1: "data/2007/tech/movies/Yellow.mov",
                                techContract1: null,

                                finalPic1: "data/2007/final/photos/yellow1.JPG",
                                finalPic2: "data/2007/final/photos/yellow2.JPG",
                                finalMov1: "data/2007/final/movies/yellow.mov",
                                finalSlide1: "data/2007/final/slides/yellow.pdf",
                                finalBrochure1: "data/2007/final/extras/yellowBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "PowerClick", // folder name
                                projName: "PowerClick",
                                projDesc: "Battery-free remote",
                                projColor: "purple",
                                projTeam: "Donald Lancaster, Doria Holbrook, Howard Kellogg, Ibrahim Kanan, Kimberly SooHoo, Matthew Gilbertson, Qinyuan Liu, Sebastian Castro, Yingdan Gu, Alexander Soo, Andrew Kennett, Eric Gilbertson, Erika R. Cerda, Jacob Muhleman, Jessica Leon, Michael Allshouse, Randal Pope, Vladimir Gordievsky",
                                projCode: "data/2007/homepage/codeOfEthics/codeOfEthics.html#purple",

                                ideasPic1: "data/2007/ideas/PurpleA1.gif",
                                ideasPic2: "data/2007/ideas/PurpleA2.gif",
                                ideasPic3: "data/2007/ideas/PurpleA3.gif",
                                ideasPic4: "data/2007/ideas/PurpleB1.gif",
                                ideasPic5: "data/2007/ideas/PurpleB2.gif",
                                ideasPic6: "data/2007/ideas/PurpleB3.gif",

                                sketchName1: "Pump-It remote control",
                                sketchName2: "Shower surge",
                                sketchName3: "PowerStroke",
                                sketchName4: "MowerCycle",
                                sketchPic1: "data/2007/sketch/photos/purpleA1_1.JPG",
                                sketchPic2: "data/2007/sketch/photos/purpleA1_2.JPG",
                                sketchPic3: "data/2007/sketch/photos/purpleA2_1.JPG",
                                sketchPic4: "data/2007/sketch/photos/purpleA2_2.JPG",
                                sketchPic5: "data/2007/sketch/photos/purpleB1_1.JPG",
                                sketchPic6: "data/2007/sketch/photos/purpleB1_2.JPG",
                                sketchPic7: "data/2007/sketch/photos/purpleB2_1.JPG",
                                sketchPic8: "data/2007/sketch/photos/purpleB2_2.JPG",
                                sketchMov1: "data/2007/sketch/movies/purpleA1.mov",
                                sketchMov2: "data/2007/sketch/movies/purpleA2.mov",
                                sketchMov3: "data/2007/sketch/movies/purpleB1.mov",
                                sketchMov4: "data/2007/sketch/movies/purpleB2.mov",
                                sketchSlide1: "data/2007/sketch/slides/purpleA1.pdf",
                                sketchSlide2: "data/2007/sketch/slides/purpleA2.pdf",
                                sketchSlide3: "data/2007/sketch/slides/purpleB1.pdf",
                                sketchSlide4: "data/2007/sketch/slides/purpleB2.pdf",

                                mockName1: "Battery-Free Remote",
                                mockName2: "MowerCycle",
                                mockPic1: "data/2007/mockup/photos/purpleA1.JPG",
                                mockPic2: "data/2007/mockup/photos/purpleA2.JPG",
                                mockPic3: "data/2007/mockup/photos/purpleB1.JPG",
                                mockPic4: "data/2007/mockup/photos/purpleB2.JPG",
                                mockMov1: "data/2007/mockup/movies/purpleAs.mov",
                                mockMov2: "data/2007/mockup/movies/purpleBs.mov",
                                mockSlide1: "data/2007/mockup/slides/purpleA.pdf",
                                mockSlide2: "data/2007/mockup/slides/purpleB.pdf",

                                assemblyPic1: "data/2007/assembly/purpleAssembly.jpg",
                                assemblyContract1: "data/2007/assembly/purpleContract.pdf",

                                techPic1: "data/2007/tech/photos/Purple1.JPG",
                                techPic2: "data/2007/tech/photos/Purple2.JPG",
                                techMov1: "data/2007/tech/movies/Purple.mov",
                                techContract1: null,

                                finalPic1: "data/2007/final/photos/purple1.JPG",
                                finalPic2: "data/2007/final/photos/purple2.JPG",
                                finalMov1: "data/2007/final/movies/purple.mov",
                                finalSlide1: "data/2007/final/slides/purple.pdf",
                                finalBrochure1: null,
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Coffee-Bean-Sorter", // folder name
                                projName: "Coffee Bean Sorter",
                                projDesc: "Human-power coffee bean sorter",
                                projColor: "orange",
                                projTeam: "Ashley Thomas, Erin Koksal, Gregory Schroll, Jessie Jeon, Joshua Garvin, Jusleen Karve, Matthew Humbert, Megan Roberts, Tess Vuethey, Shane Colton, Betar Gallant, Jean Chang, JeffreY Kirby, Jessica Luttkus, Jonathan Hsieh, Juan Pablo Mendieta, Marcus Lopez, Maria Telleria, Robert Truax",
                                projCode: "data/2007/homepage/codeOfEthics/codeOfEthics.html#orange",

                                ideasPic1: "data/2007/ideas/OrangeA1.gif",
                                ideasPic2: "data/2007/ideas/OrangeA2.gif",
                                ideasPic3: "data/2007/ideas/OrangeA3.gif",
                                ideasPic4: "data/2007/ideas/OrangeB1.gif",
                                ideasPic5: "data/2007/ideas/OrangeB2.gif",
                                ideasPic6: "data/2007/ideas/OrangeB3.gif",

                                sketchName1: "Interactive recycler",
                                sketchName2: "Coffee bean sorter",
                                sketchName3: "Oily water separator",
                                sketchName4: "Veggie oil collection system",
                                sketchPic1: "data/2007/sketch/photos/orangeA1_1.JPG",
                                sketchPic2: "data/2007/sketch/photos/orangeA1_2.JPG",
                                sketchPic3: "data/2007/sketch/photos/orangeA2_1.JPG",
                                sketchPic4: "data/2007/sketch/photos/orangeA2_2.JPG",
                                sketchPic5: "data/2007/sketch/photos/orangeB1_1.JPG",
                                sketchPic6: "data/2007/sketch/photos/orangeB1_2.JPG",
                                sketchPic7: "data/2007/sketch/photos/orangeB2_1.JPG",
                                sketchPic8: "data/2007/sketch/photos/orangeB2_2.JPG",
                                sketchMov1: "data/2007/sketch/movies/orangeA1.mov",
                                sketchMov2: "data/2007/sketch/movies/orangeA2.mov",
                                sketchMov3: "data/2007/sketch/movies/orangeB1.mov",
                                sketchMov4: "data/2007/sketch/movies/orangeB2.mov",
                                sketchSlide1: "data/2007/sketch/slides/orangeA1.pdf",
                                sketchSlide2: "data/2007/sketch/slides/orangeA2.pdf",
                                sketchSlide3: "data/2007/sketch/slides/orangeB1.pdf",
                                sketchSlide4: "data/2007/sketch/slides/orangeB2.pdf",

                                mockName1: "Coffee Bean Sorting",
                                mockName2: "Green Grease",
                                mockPic1: "data/2007/mockup/photos/orangeA1.JPG",
                                mockPic2: "data/2007/mockup/photos/orangeA2.JPG",
                                mockPic3: "data/2007/mockup/photos/orangeB1.JPG",
                                mockPic4: "data/2007/mockup/photos/orangeB2.JPG",
                                mockMov1: "data/2007/mockup/movies/orangeAs.mov",
                                mockMov2: "data/2007/mockup/movies/orangeBs.mov",
                                mockSlide1: "data/2007/mockup/slides/orangeA.pdf",
                                mockSlide2: "data/2007/mockup/slides/orangeB.pdf",

                                assemblyPic1: "data/2007/assembly/orangeAssembly.jpg",
                                assemblyContract1: "data/2007/assembly/orangeContract.pdf",

                                techPic1: "data/2007/tech/photos/Orange1.JPG",
                                techPic2: "data/2007/tech/photos/Orange2.JPG",
                                techMov1: "data/2007/tech/movies/Orange.mov",
                                techContract1: null,

                                finalPic1: "data/2007/final/photos/orange1.JPG",
                                finalPic2: "data/2007/final/photos/orange2.JPG",
                                finalMov1: "data/2007/final/movies/orange.mov",
                                finalSlide1: "data/2007/final/slides/orange.pdf",
                                finalBrochure1: null,
                                finalBrochure2: null,
                        ],
                        [
                                projId: "SheaCycle", // folder name
                                projName: "SheaCycle",
                                projDesc: "Shea paste grinder",
                                projColor: "silver",
                                projTeam: "Anthony Teixeira, David Kirkland, Dayan Paez, Jacquelyn Nowicke, Javier Burgos, Maria Luckyanova, Stephen Steger, Tolga Yazicioglu, Heraclio Hernandez, Brad Stronger, Gavin Cotter, Joseph Dieguez, Karen Noiva, Michael Kozlowski, Nadia Elkordy, Patrick Barragan, Philip Garcia, Basil Khoury",
                                projCode: "data/2007/homepage/codeOfEthics/codeOfEthics.html#silver",

                                ideasPic1: "data/2007/ideas/SilverA1.gif",
                                ideasPic2: "data/2007/ideas/SilverA2.gif",
                                ideasPic3: "data/2007/ideas/SilverA3.gif",
                                ideasPic4: "data/2007/ideas/SilverB1.gif",
                                ideasPic5: "data/2007/ideas/SilverB2.gif",
                                ideasPic6: "data/2007/ideas/SilverB3.gif",

                                sketchName1: "VeggiClean",
                                sketchName2: "WindBag",
                                sketchName3: "Shea nut press",
                                sketchName4: "Veggie washer",
                                sketchPic1: "data/2007/sketch/photos/silverA1_1.JPG",
                                sketchPic2: "data/2007/sketch/photos/silverA1_2.JPG",
                                sketchPic3: "data/2007/sketch/photos/silverA2_1.JPG",
                                sketchPic4: "data/2007/sketch/photos/silverA2_2.JPG",
                                sketchPic5: "data/2007/sketch/photos/silverB1_1.JPG",
                                sketchPic6: "data/2007/sketch/photos/silverB1_2.JPG",
                                sketchPic7: "data/2007/sketch/photos/silverB2_1.JPG",
                                sketchPic8: "data/2007/sketch/photos/silverB2_2.JPG",
                                sketchMov1: "data/2007/sketch/movies/silverA1.mov",
                                sketchMov2: "data/2007/sketch/movies/silverA2.mov",
                                sketchMov3: "data/2007/sketch/movies/silverB1.mov",
                                sketchMov4: "data/2007/sketch/movies/silverB2.mov",
                                sketchSlide1: "data/2007/sketch/slides/silverA1.pdf",
                                sketchSlide2: "data/2007/sketch/slides/silverA2.pdf",
                                sketchSlide3: "data/2007/sketch/slides/silverB1.pdf",
                                sketchSlide4: "data/2007/sketch/slides/silverB2.pdf",

                                mockName1: "VeggieClean",
                                mockName2: "Shea Nut Processing",
                                mockPic1: "data/2007/mockup/photos/silverA1.JPG",
                                mockPic2: "data/2007/mockup/photos/silverA2.JPG",
                                mockPic3: "data/2007/mockup/photos/silverB1.JPG",
                                mockPic4: "data/2007/mockup/photos/silverB2.JPG",
                                mockMov1: "data/2007/mockup/movies/silverAs.mov",
                                mockMov2: "data/2007/mockup/movies/silverBs.mov",
                                mockSlide1: "data/2007/mockup/slides/silverA.pdf",
                                mockSlide2: "data/2007/mockup/slides/silverB.pdf",

                                assemblyPic1: "data/2007/assembly/silverAssembly.jpg",
                                assemblyContract1: "data/2007/assembly/silverContract.pdf",

                                techPic1: "data/2007/tech/photos/Silver1.JPG",
                                techPic2: "data/2007/tech/photos/Silver2.JPG",
                                techMov1: "data/2007/tech/movies/Silver.mov",
                                techContract1: null,

                                finalPic1: "data/2007/final/photos/silver1.JPG",
                                finalPic2: "data/2007/final/photos/silver2.JPG",
                                finalMov1: "data/2007/final/movies/silver.mov",
                                finalSlide1: "data/2007/final/slides/silver.pdf",
                                finalBrochure1: null,
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Cyclos", // folder name
                                projName: "Cyclos",
                                projDesc: "Oil filter cleaner",
                                projColor: "green",
                                projTeam: "Andrea Greb, Brian Greviskes, Devanie DuFour, Emily Li, Holly Greenberg, Homar Molina Jr., Kimberlee Collins, Lucas Hernandez-Mena, Timothy Pier, Anthony Jones, Connie Yee, David Foster, Denise Law, Gina Angelosanto, Laura Martini, Michael Yoder, Richard Kosoglow, Mona Daniels",
                                projCode: "data/2007/homepage/codeOfEthics/codeOfEthics.html#green",

                                ideasPic1: "data/2007/ideas/GreenA1.gif",
                                ideasPic2: "data/2007/ideas/GreenA2.gif",
                                ideasPic3: "data/2007/ideas/GreenA3.gif",
                                ideasPic4: "data/2007/ideas/GreenB1.gif",
                                ideasPic5: "data/2007/ideas/GreenB2.gif",
                                ideasPic6: "data/2007/ideas/GreenB3.gif",

                                sketchName1: "Marine debris collector",
                                sketchName2: "Oil filter cleaner",
                                sketchName3: "Coffee bean sorter",
                                sketchName4: "Plastic bag rejuvenator",
                                sketchPic1: "data/2007/sketch/photos/greenA1_1.JPG",
                                sketchPic2: "data/2007/sketch/photos/greenA1_2.JPG",
                                sketchPic3: "data/2007/sketch/photos/greenA2_1.JPG",
                                sketchPic4: "data/2007/sketch/photos/greenA2_2.JPG",
                                sketchPic5: "data/2007/sketch/photos/greenB1_1.JPG",
                                sketchPic6: "data/2007/sketch/photos/greenB1_2.JPG",
                                sketchPic7: "data/2007/sketch/photos/greenB2_1.JPG",
                                sketchPic8: "data/2007/sketch/photos/greenB2_2.JPG",
                                sketchMov1: "data/2007/sketch/movies/greenA1.mov",
                                sketchMov2: "data/2007/sketch/movies/greenA2.mov",
                                sketchMov3: "data/2007/sketch/movies/greenB1.mov",
                                sketchMov4: "data/2007/sketch/movies/greenB2.mov",
                                sketchSlide1: "data/2007/sketch/slides/greenA1.pdf",
                                sketchSlide2: "data/2007/sketch/slides/greenA2.pdf",
                                sketchSlide3: "data/2007/sketch/slides/greenB1.pdf",
                                sketchSlide4: "data/2007/sketch/slides/greenB2.pdf",

                                mockName1: "Oil Filter cleaner",
                                mockName2: "Plastic Rejuvenator",
                                mockPic1: "data/2007/mockup/photos/greenA1.JPG",
                                mockPic2: "data/2007/mockup/photos/greenA2.JPG",
                                mockPic3: "data/2007/mockup/photos/greenB1.JPG",
                                mockPic4: "data/2007/mockup/photos/greenB2.JPG",
                                mockMov1: "data/2007/mockup/movies/greenAs.mov",
                                mockMov2: "data/2007/mockup/movies/greenBs.mov",
                                mockSlide1: "data/2007/mockup/slides/greenA.pdf",
                                mockSlide2: "data/2007/mockup/slides/greenB.pdf",

                                assemblyPic1: "data/2007/assembly/greenAssembly.jpg",
                                assemblyContract1: "data/2007/assembly/greenContract.pdf",

                                techPic1: "data/2007/tech/photos/Green1.JPG",
                                techPic2: "data/2007/tech/photos/Green2.JPG",
                                techMov1: "data/2007/tech/movies/Green.mov",
                                techContract1: null,

                                finalPic1: "data/2007/final/photos/green1.JPG",
                                finalPic2: "data/2007/final/photos/green2.JPG",
                                finalMov1: "data/2007/final/movies/green.mov",
                                finalSlide1: "data/2007/final/slides/green.pdf",
                                finalBrochure1: "data/2007/final/extras/greenBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Bottleation", // folder name
                                projName: "Bottleation",
                                projDesc: "Insulation from bottles",
                                projColor: "red",
                                projTeam: "Abby Carey, Alan Cohen, Brian Hack, Christopher Dimitriou, Irina Azu, Kenneth Rosche, Megan Firko, Roderick La Foy, Stephen Ray, Alexander St. Claire, Batya Fellman, Chris Becker, Christopher Desrochers, Ilan Moyer, Kathryn Matlack, Keith Molina, Matthew Robertson, Nicolina Akraboff",
                                projCode: "data/2007/homepage/codeOfEthics/codeOfEthics.html#red",

                                ideasPic1: "data/2007/ideas/RedA1.gif",
                                ideasPic2: "data/2007/ideas/RedA2.gif",
                                ideasPic3: "data/2007/ideas/RedA3.gif",
                                ideasPic4: "data/2007/ideas/RedB1.gif",
                                ideasPic5: "data/2007/ideas/RedB2.gif",
                                ideasPic6: "data/2007/ideas/RedB3.gif",

                                sketchName1: "Rope weaver",
                                sketchName2: "Hot rods (plastic sheet)",
                                sketchName3: "The deCAPitator",
                                sketchName4: "Heated plastic roller",
                                sketchPic1: "data/2007/sketch/photos/redA1_1.JPG",
                                sketchPic2: "data/2007/sketch/photos/redA1_2.JPG",
                                sketchPic3: "data/2007/sketch/photos/redA2_1.JPG",
                                sketchPic4: "data/2007/sketch/photos/redA2_2.JPG",
                                sketchPic5: "data/2007/sketch/photos/redB1_1.JPG",
                                sketchPic6: "data/2007/sketch/photos/redB1_2.JPG",
                                sketchPic7: "data/2007/sketch/photos/redB2_1.JPG",
                                sketchPic8: "data/2007/sketch/photos/redB2_2.JPG",
                                sketchMov1: "data/2007/sketch/movies/redA1.mov",
                                sketchMov2: "data/2007/sketch/movies/redA2.mov",
                                sketchMov3: "data/2007/sketch/movies/redB1.mov",
                                sketchMov4: "data/2007/sketch/movies/redB2.mov",
                                sketchSlide1: "data/2007/sketch/slides/redA1.pdf",
                                sketchSlide2: "data/2007/sketch/slides/redA2.pdf",
                                sketchSlide3: "data/2007/sketch/slides/redB1.pdf",
                                sketchSlide4: "data/2007/sketch/slides/redB2.pdf",

                                mockName1: "Rope Weaver",
                                mockName2: "Bottle Binder",
                                mockPic1: "data/2007/mockup/photos/redA1.JPG",
                                mockPic2: "data/2007/mockup/photos/redA2.JPG",
                                mockPic3: "data/2007/mockup/photos/redB1.JPG",
                                mockPic4: "data/2007/mockup/photos/redB2.JPG",
                                mockMov1: "data/2007/mockup/movies/redAs.mov",
                                mockMov2: "data/2007/mockup/movies/redBs.mov",
                                mockSlide1: "data/2007/mockup/slides/redA.pdf",
                                mockSlide2: "data/2007/mockup/slides/redB.pdf",

                                assemblyPic1: "data/2007/assembly/redAssembly.jpg",
                                assemblyContract1: "data/2007/assembly/redContract.pdf",

                                techPic1: "data/2007/tech/photos/Red1.JPG",
                                techPic2: "data/2007/tech/photos/Red2.JPG",
                                techMov1: "data/2007/tech/movies/Red.mov",
                                techContract1: null,

                                finalPic1: "data/2007/final/photos/red1.JPG",
                                finalPic2: "data/2007/final/photos/red2.JPG",
                                finalMov1: "data/2007/final/movies/red.mov",
                                finalSlide1: "data/2007/final/slides/red.pdf",
                                finalBrochure1: "data/2007/final/extras/redBrochure.pdf",
                                finalBrochure2: null,
                        ],
                ],
        ],
]