[
        "2005": [
                themeYear: "2005", // folder name
                themeName: "Agriculture",
                themeDesc: "Any agriculture or aquaculture-related products may be considered. Target customers may include both developed and developing countries.",
                highlights: [
                        [ linkLabel: "Home page and slide show", linkUrl: "http://web.mit.edu/2.009_gallery/www/2005_other/homepage/index.html" ],
                        [ linkLabel: "The Archimedes Death Ray", linkUrl: "http://web.mit.edu/2.009_gallery/www/2005_other/archimedes/10_ArchimedesResult.html" ],
                        [ linkLabel: "DesignNerds!", linkUrl: "data/2005/highlights/designerdsSmall.mov", onClick: "window.open('data/2005/highlights/designerdsSmall.mov', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "See the Tech Talk article", linkUrl: "http://web.mit.edu/newsoffice/2005/2009adv-1207.html" ],
                ],
                highlightDividerIndexes: [ 0 ],
                sketchMovWidth: 240,
                sketchMovHeight: 185,
                mockMovWidth: 240,
                mockMovHeight: 185,
                techMovWidth: 240,
                techMovHeight: 185,
                finalMovWidth: 240,
                finalMovHeight: 185,
                picWidth: 135, // picHeight is determined dynamically
                projects: [
                        [
                                projId: "Inocupro", // folder name
                                projName: "InocuPro",
                                projDesc: "A grinder used to chop inocculus root to a proper size for farmers to use as fertilizer",
                                projColor: "blue",
                                projTeam: "Michael Flores, Valerie Kuo, Harry Lichter, Elizabeth Lin, Matthew Sorge, Julius Strauss, Walton Ward, Zach Eisenstat, Dan Guarda, Justin Holland, Phil Hum, Levi Lalla, Wey-Jiun Lin, Tiffany Yang",
                                projCode: "http://web.mit.edu/2.009_gallery/www/2005/ethics.html#blue",

                                ideasPic1: "data/2005/ideas/BlueA1.jpg",
                                ideasPic2: "data/2005/ideas/BlueA2.jpg",
                                ideasPic3: "data/2005/ideas/BlueA3.jpg",
                                ideasPic4: "data/2005/ideas/BlueB1.jpg",
                                ideasPic5: "data/2005/ideas/BlueB2.jpg",
                                ideasPic6: "data/2005/ideas/BlueB3.jpg",

                                sketchName1: "Manioc Grater",
                                sketchName2: "Electronic Cattle Collar",
                                sketchName3: "Inocculus Root Grinder",
                                sketchName4: "Root Cleaner",
                                sketchPic1: "data/2005/sketch/photos/blueA1_1.jpg",
                                sketchPic2: "data/2005/sketch/photos/blueA1_2.jpg",
                                sketchPic3: "data/2005/sketch/photos/blueA2_1.jpg",
                                sketchPic4: "data/2005/sketch/photos/blueA2_2.jpg",
                                sketchPic5: "data/2005/sketch/photos/blueB1_1.jpg",
                                sketchPic6: "data/2005/sketch/photos/blueB1_2.jpg",
                                sketchPic7: "data/2005/sketch/photos/blueB2_1.jpg",
                                sketchPic8: "data/2005/sketch/photos/blueB2_2.jpg",
                                sketchMov1: "data/2005/sketch/movies/blueA1.mov",
                                sketchMov2: "data/2005/sketch/movies/blueA2.mov",
                                sketchMov3: "data/2005/sketch/movies/blueB1.mov",
                                sketchMov4: "data/2005/sketch/movies/blueB2.mov",
                                sketchSlide1: "data/2005/sketch/slides/blueA1.pdf",
                                sketchSlide2: "data/2005/sketch/slides/blueA2.pdf",
                                sketchSlide3: "data/2005/sketch/slides/blueB1.pdf",
                                sketchSlide4: "data/2005/sketch/slides/blueB2.pdf",

                                mockName1: "Electronic Cattle Collar",
                                mockName2: "Inocculus Root Grinder",

                                mockPic1: "data/2005/mockup/photos/blueA1.jpg",
                                mockPic2: "data/2005/mockup/photos/blueA2.jpg",
                                mockPic3: "data/2005/mockup/photos/blueB1.jpg",
                                mockPic4: "data/2005/mockup/photos/blueB2.jpg",
                                mockMov1: "data/2005/mockup/movies/blueAs.mov",
                                mockMov2: "data/2005/mockup/movies/blueBs.mov",
                                mockSlide1: "data/2005/mockup/slides/blueA.pdf",
                                mockSlide2: "data/2005/mockup/slides/blueB.pdf",

                                assemblyPic1: "data/2005/assembly/blueAssembly.jpg",
                                assemblyContract1: "data/2005/assembly/blueContract.pdf",

                                techPic1: "data/2005/tech/photos/Blue1.jpg",
                                techPic2: "data/2005/tech/photos/Blue2.jpg",
                                techMov1: "data/2005/tech/movies/Blue.mov",
                                techContract1: "data/2005/tech/extras/Blue_product_contract.pdf",

                                finalPic1: "data/2005/final/photos/blue1.jpg",
                                finalPic2: "data/2005/final/photos/blue2.jpg",
                                finalMov1: "data/2005/final/movies/blue.mov",
                                finalSlide1: "data/2005/final/slides/blue.ppt",
                                finalBrochure1: "data/2005/final/extras/blueBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "TreeTran", // folder name
                                projName: "TreeTran",
                                projDesc: "A means of transporting tree root balls and lowering them into holes",
                                projColor: "orange",
                                projTeam: "Nick Allard, Steph Lee, Sean Nabar, Sal Pallante, Arlis Reynolds, Omoleye Roberts, Thaddeus Stefanov-Wagner, Liz Hempel, Robert Rangel, Joel Sadler, Meghna Trivedi, Sandie Yang, Wen Zhang, Jean Zheng",
                                projCode: "http://web.mit.edu/2.009_gallery/www/2005/ethics.html#orange",

                                ideasPic1: "data/2005/ideas/OrangeA1.jpg",
                                ideasPic2: "data/2005/ideas/OrangeA2.jpg",
                                ideasPic3: "data/2005/ideas/OrangeA3.jpg",
                                ideasPic4: "data/2005/ideas/OrangeB1.jpg",
                                ideasPic5: "data/2005/ideas/OrangeB2.jpg",
                                ideasPic6: "data/2005/ideas/OrangeB3.jpg",

                                sketchName1: "Rice Transplanter",
                                sketchName2: "Tree Barrow",
                                sketchName3: "Rice Transplanter",
                                sketchName4: "Arborator",
                                sketchPic1: "data/2005/sketch/photos/orangeA1_1.jpg",
                                sketchPic2: "data/2005/sketch/photos/orangeA1_2.jpg",
                                sketchPic3: "data/2005/sketch/photos/orangeA2_1.jpg",
                                sketchPic4: "data/2005/sketch/photos/orangeA2_2.jpg",
                                sketchPic5: "data/2005/sketch/photos/orangeB1_1.jpg",
                                sketchPic6: "data/2005/sketch/photos/orangeB1_2.jpg",
                                sketchPic7: "data/2005/sketch/photos/orangeB2_1.jpg",
                                sketchPic8: "data/2005/sketch/photos/orangeB2_2.jpg",
                                sketchMov1: "data/2005/sketch/movies/orangeA1.mov",
                                sketchMov2: "data/2005/sketch/movies/orangeA2.mov",
                                sketchMov3: "data/2005/sketch/movies/orangeB1.mov",
                                sketchMov4: "data/2005/sketch/movies/orangeB2.mov",
                                sketchSlide1: "data/2005/sketch/slides/orangeA1.pdf",
                                sketchSlide2: "data/2005/sketch/slides/orangeA2.pdf",
                                sketchSlide3: "data/2005/sketch/slides/orangeB1.pdf",
                                sketchSlide4: "data/2005/sketch/slides/orangeB2.pdf",

                                mockName1: "Arborator",
                                mockName2: "Rice Transplanter",

                                mockPic1: "data/2005/mockup/photos/orangeA1.jpg",
                                mockPic2: "data/2005/mockup/photos/orangeA2.jpg",
                                mockPic3: "data/2005/mockup/photos/orangeB1.jpg",
                                mockPic4: "data/2005/mockup/photos/orangeB2.jpg",
                                mockMov1: "data/2005/mockup/movies/orangeAs.mov",
                                mockMov2: "data/2005/mockup/movies/orangeBs.mov",
                                mockSlide1: "data/2005/mockup/slides/orangeA.pdf",
                                mockSlide2: "data/2005/mockup/slides/orangeB.pdf",

                                assemblyPic1: "data/2005/assembly/orangeAssembly.jpg",
                                assemblyContract1: "data/2005/assembly/orangeContract.pdf",

                                techPic1: "data/2005/tech/photos/Orange1.jpg",
                                techPic2: "data/2005/tech/photos/Orange2.jpg",
                                techMov1: "data/2005/tech/movies/Orange.mov",
                                techContract1: "data/2005/tech/extras/Orange_product_contract.pdf",

                                finalPic1: "data/2005/final/photos/orange1.jpg",
                                finalPic2: "data/2005/final/photos/orange2.jpg",
                                finalMov1: "data/2005/final/movies/orange.mov",
                                finalSlide1: "data/2005/final/slides/orange.ppt",
                                finalBrochure1: "data/2005/final/extras/orangeBrochure1.pdf",
                                finalBrochure2: "data/2005/final/extras/orangeBrochure2.pdf",
                        ],
                        [
                                projId: "Banana", // folder name
                                projName: "Banana Harvester",
                                projDesc: "A device that assists banana famers in removing banana bunches from trees",
                                projColor: "red",
                                projTeam: "Jason Atkins, Andrew Greenhut, Adam Kaczmarek, Jim Labuz, Alex Nelson, Becky Romatoski, Byron Shieh, Kim Straub, Ricky Diaz, Thor Eusner, Tristan Hayeck, Brian Keegan, Sam Kesner, Elliot Ortiz-Soto, Mike Wolf",
                                projCode: "http://web.mit.edu/2.009_gallery/www/2005/ethics.html#red",

                                ideasPic1: "data/2005/ideas/RedA1.jpg",
                                ideasPic2: "data/2005/ideas/RedA2.jpg",
                                ideasPic3: "data/2005/ideas/RedA3.jpg",
                                ideasPic4: "data/2005/ideas/RedB1.jpg",
                                ideasPic5: "data/2005/ideas/RedB2.jpg",
                                ideasPic6: "data/2005/ideas/RedB3.jpg",

                                sketchName1: "Bunch Muncher",
                                sketchName2: "Mega Spreader",
                                sketchName3: "Cranberry Harvester",
                                sketchName4: "Citrus Picker",
                                sketchPic1: "data/2005/sketch/photos/redA1_1.jpg",
                                sketchPic2: "data/2005/sketch/photos/redA1_2.jpg",
                                sketchPic3: "data/2005/sketch/photos/redA2_1.jpg",
                                sketchPic4: "data/2005/sketch/photos/redA2_2.jpg",
                                sketchPic5: "data/2005/sketch/photos/redB1_1.jpg",
                                sketchPic6: "data/2005/sketch/photos/redB1_2.jpg",
                                sketchPic7: "data/2005/sketch/photos/redB2_1.jpg",
                                sketchPic8: "data/2005/sketch/photos/redB2_2.jpg",
                                sketchMov1: "data/2005/sketch/movies/redA1.mov",
                                sketchMov2: "data/2005/sketch/movies/redA2.mov",
                                sketchMov3: "data/2005/sketch/movies/redB1.mov",
                                sketchMov4: "data/2005/sketch/movies/redB2.mov",
                                sketchSlide1: "data/2005/sketch/slides/redA1.pdf",
                                sketchSlide2: "data/2005/sketch/slides/redA2.pdf",
                                sketchSlide3: "data/2005/sketch/slides/redB1.pdf",
                                sketchSlide4: "data/2005/sketch/slides/redB2.pdf",

                                mockName1: "Banana Picker",
                                mockName2: "Orange Harvester",
                                mockPic1: "data/2005/mockup/photos/redA1.jpg",
                                mockPic2: "data/2005/mockup/photos/redA2.jpg",
                                mockPic3: "data/2005/mockup/photos/redB1.jpg",
                                mockPic4: "data/2005/mockup/photos/redB2.jpg",
                                mockMov1: "data/2005/mockup/movies/redAs.mov",
                                mockMov2: "data/2005/mockup/movies/redBs.mov",
                                mockSlide1: "data/2005/mockup/slides/redA.pdf",
                                mockSlide2: "data/2005/mockup/slides/redB.pdf",

                                assemblyPic1: "data/2005/assembly/redAssembly.jpg",
                                assemblyContract1: "data/2005/assembly/redContract.pdf",

                                techPic1: "data/2005/tech/photos/Red1.jpg",
                                techPic2: "data/2005/tech/photos/Red2.jpg",
                                techMov1: "data/2005/tech/movies/Red.mov",
                                techContract1: "data/2005/tech/extras/Red_product_contract.pdf",

                                finalPic1: "data/2005/final/photos/red1.jpg",
                                finalPic2: "data/2005/final/photos/red2.jpg",
                                finalMov1: "data/2005/final/movies/red.mov",
                                finalSlide1: "data/2005/final/slides/red.ppt",
                                finalBrochure1: "data/2005/final/extras/redBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Yucca", // folder name
                                projName: "YuccaCycle",
                                projDesc: "Human powered yucca grater for Hatian communities",
                                projColor: "yellow",
                                projTeam: "Christina Chestnut, John Rebula, Shannon Turner, Louis Basel, Chris Farm, Chandler Hatton, Somin Lee, Kevin Mears, Alika Phipps, Nick Villarruel",
                                projCode: "http://web.mit.edu/2.009_gallery/www/2005/ethics.html#yellow",

                                ideasPic1: "data/2005/ideas/YellowA1.jpg",
                                ideasPic2: "data/2005/ideas/YellowA2.jpg",
                                ideasPic3: "data/2005/ideas/YellowA3.jpg",
                                ideasPic4: "data/2005/ideas/YellowB1.jpg",
                                ideasPic5: "data/2005/ideas/YellowB2.jpg",
                                ideasPic6: null,

                                sketchName1: "Peanut Oil Press",
                                sketchName2: "Composter",
                                sketchName3: "Manioc Grater",
                                sketchName4: null,

                                sketchPic1: "data/2005/sketch/photos/yellowA1_1.jpg",
                                sketchPic2: "data/2005/sketch/photos/yellowA1_2.jpg",
                                sketchPic3: "data/2005/sketch/photos/yellowA2_1.jpg",
                                sketchPic4: "data/2005/sketch/photos/yellowA2_2.jpg",
                                sketchPic5: "data/2005/sketch/photos/yellowB1_1.jpg",
                                sketchPic6: "data/2005/sketch/photos/yellowB1_2.jpg",
                                sketchPic7: null,
                                sketchPic8: null,
                                sketchMov1: "data/2005/sketch/movies/yellowA1.mov",
                                sketchMov2: "data/2005/sketch/movies/yellowA2.mov",
                                sketchMov3: "data/2005/sketch/movies/yellowB1.mov",
                                sketchMov4: null,
                                sketchSlide1: "data/2005/sketch/slides/yellowA1.ppt",
                                sketchSlide2: "data/2005/sketch/slides/yellowA2.ppt",
                                sketchSlide3: "data/2005/sketch/slides/yellowB1.ppt",
                                sketchSlide4: null,

                                mockName1: "Manioc Grater",
                                mockName2: null,
                                mockPic1: "data/2005/mockup/photos/yellowA1.jpg",
                                mockPic2: "data/2005/mockup/photos/yellowA2.jpg",
                                mockPic3: null,
                                mockPic4: null,
                                mockMov1: "data/2005/mockup/movies/yellowAs.mov",
                                mockMov2: null,
                                mockSlide1: "data/2005/mockup/slides/yellowA.ppt",
                                mockSlide2: null,

                                assemblyPic1: "data/2005/assembly/yellowAssembly.jpg",
                                assemblyContract1: "data/2005/assembly/yellowContract.pdf",

                                techPic1: "data/2005/tech/photos/Yellow1.jpg",
                                techPic2: "data/2005/tech/photos/Yellow2.jpg",
                                techMov1: "data/2005/tech/movies/Yellow.mov",
                                techContract1: "data/2005/tech/extras/Yellow_product_contract.pdf",

                                finalPic1: "data/2005/final/photos/yellow1.jpg",
                                finalPic2: "data/2005/final/photos/yellow2.jpg",
                                finalMov1: "data/2005/final/movies/yellow.mov",
                                finalSlide1: "data/2005/final/slides/yellow.ppt",
                                finalBrochure1: "data/2005/final/extras/yellowBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Lentil", // folder name
                                projName: "Lentil Cleaner",
                                projDesc: "A portable device for farmers that removes unwanted debris from lentils",
                                projColor: "green",
                                projTeam: "Nick Allard, Steph Lee, Sean Nabar, Sal Pallante, Arlis Reynolds, Omoleye Roberts, Thaddeus Stefanov-Wagner, Liz Hempel, Robert Rangel, Joel Sadler, Meghna Trivedi, Sandie Yang, Wen Zhang, Jean Zheng",
                                projCode: "http://web.mit.edu/2.009_gallery/www/2005/ethics.html#green",

                                ideasPic1: "data/2005/ideas/GreenA1.jpg",
                                ideasPic2: "data/2005/ideas/GreenA2.jpg",
                                ideasPic3: "data/2005/ideas/GreenA3.jpg",
                                ideasPic4: "data/2005/ideas/GreenB1.jpg",
                                ideasPic5: "data/2005/ideas/GreenB2.jpg",
                                ideasPic6: "data/2005/ideas/GreenB3.jpg",

                                sketchName1: "Pecan Sheller",
                                sketchName2: "Centrifugal Juicer",
                                sketchName3: "Nut Press",
                                sketchName4: "Lentil Sorter",
                                sketchPic1: "data/2005/sketch/photos/greenA1_1.jpg",
                                sketchPic2: "data/2005/sketch/photos/greenA1_2.jpg",
                                sketchPic3: "data/2005/sketch/photos/greenA2_1.jpg",
                                sketchPic4: "data/2005/sketch/photos/greenA2_2.jpg",
                                sketchPic5: "data/2005/sketch/photos/greenB1_1.jpg",
                                sketchPic6: "data/2005/sketch/photos/greenB1_2.jpg",
                                sketchPic7: "data/2005/sketch/photos/greenB2_1.jpg",
                                sketchPic8: "data/2005/sketch/photos/greenB2_2.jpg",
                                sketchMov1: "data/2005/sketch/movies/greenA1.mov",
                                sketchMov2: "data/2005/sketch/movies/greenA2.mov",
                                sketchMov3: "data/2005/sketch/movies/greenB1.mov",
                                sketchMov4: "data/2005/sketch/movies/greenB2.mov",
                                sketchSlide1: "data/2005/sketch/slides/greenA1.ppt",
                                sketchSlide2: "data/2005/sketch/slides/greenA2.ppt",
                                sketchSlide3: "data/2005/sketch/slides/greenB1.ppt",
                                sketchSlide4: "data/2005/sketch/slides/greenB2.ppt",

                                mockName1: "Pecan Sheller",
                                mockName2: "Lentil Sorter",
                                mockPic1: "data/2005/mockup/photos/greenA1.jpg",
                                mockPic2: "data/2005/mockup/photos/greenA2.jpg",
                                mockPic3: "data/2005/mockup/photos/greenB1.jpg",
                                mockPic4: "data/2005/mockup/photos/greenB2.jpg",
                                mockMov1: "data/2005/mockup/movies/greenAs.mov",
                                mockMov2: "data/2005/mockup/movies/greenBs.mov",
                                mockSlide1: "data/2005/mockup/slides/greenA.ppt",
                                mockSlide2: "data/2005/mockup/slides/greenB.ppt",

                                assemblyPic1: "data/2005/assembly/greenAssembly.jpg",
                                assemblyContract1: "data/2005/assembly/greenContract.pdf",

                                techPic1: "data/2005/tech/photos/Green1.jpg",
                                techPic2: "data/2005/tech/photos/Green2.jpg",
                                techMov1: "data/2005/tech/movies/Green.mov",
                                techContract1: "data/2005/tech/extras/Green_product_contract.pdf",

                                finalPic1: "data/2005/final/photos/green1.jpg",
                                finalPic2: "data/2005/final/photos/green2.jpg",
                                finalMov1: "data/2005/final/movies/green.mov",
                                finalSlide1: "data/2005/final/slides/green.ppt",
                                finalBrochure1: "data/2005/final/extras/greenBrochure1.pdf",
                                finalBrochure2: "data/2005/final/extras/greenBrochure2.pdf",
                        ],
                        [
                                projId: "Irrigator", // folder name
                                projName: "IrriGator",
                                projDesc: "Human powered water pump for developing areas",
                                projColor: "purple",
                                projTeam: "Steve Amanti, Emil Cuevas, Sam Felton, Deanna Lentz, Dean Ljubicic, Mika Tomczak, Chris Rhodes, Margaret Gentile, Chris Grossman, Charles Louison, Jim Otten, Jessica Rabl, Chris Rivest",
                                projCode: "http://web.mit.edu/2.009_gallery/www/2005/ethics.html#purple",

                                ideasPic1: "data/2005/ideas/PurpleA1.jpg",
                                ideasPic2: "data/2005/ideas/PurpleA2.jpg",
                                ideasPic3: "data/2005/ideas/PurpleA3.jpg",
                                ideasPic4: "data/2005/ideas/PurpleB1.jpg",
                                ideasPic5: "data/2005/ideas/PurpleB2.jpg",
                                ideasPic6: "data/2005/ideas/PurpleB3.jpg",

                                sketchName1: "Manioc Shredder",
                                sketchName2: "Tree Trolley",
                                sketchName3: "Bike Power",
                                sketchName4: "Water Pump",
                                sketchPic1: "data/2005/sketch/photos/purpleA1_1.jpg",
                                sketchPic2: "data/2005/sketch/photos/purpleA1_2.jpg",
                                sketchPic3: "data/2005/sketch/photos/purpleA2_1.jpg",
                                sketchPic4: "data/2005/sketch/photos/purpleA2_2.jpg",
                                sketchPic5: "data/2005/sketch/photos/purpleB1_1.jpg",
                                sketchPic6: "data/2005/sketch/photos/purpleB1_2.jpg",
                                sketchPic7: "data/2005/sketch/photos/purpleB2_1.jpg",
                                sketchPic8: "data/2005/sketch/photos/purpleB2_2.jpg",
                                sketchMov1: "data/2005/sketch/movies/purpleA1.mov",
                                sketchMov2: "data/2005/sketch/movies/purpleA2.mov",
                                sketchMov3: "data/2005/sketch/movies/purpleB1.mov",
                                sketchMov4: "data/2005/sketch/movies/purpleB2.mov",
                                sketchSlide1: "data/2005/sketch/slides/purpleA1.pdf",
                                sketchSlide2: "data/2005/sketch/slides/purpleA2.pdf",
                                sketchSlide3: "data/2005/sketch/slides/purpleB1.pdf",
                                sketchSlide4: "data/2005/sketch/slides/purpleB2.pdf",

                                mockName1: "Manioc Grinder",
                                mockName2: "Bicycle Water Pump",
                                mockPic1: "data/2005/mockup/photos/purpleA1.jpg",
                                mockPic2: "data/2005/mockup/photos/purpleA2.jpg",
                                mockPic3: "data/2005/mockup/photos/purpleB1.jpg",
                                mockPic4: "data/2005/mockup/photos/purpleB2.jpg",
                                mockMov1: "data/2005/mockup/movies/purpleAs.mov",
                                mockMov2: "data/2005/mockup/movies/purpleBs.mov",
                                mockSlide1: "data/2005/mockup/slides/purpleA.pdf",
                                mockSlide2: "data/2005/mockup/slides/purpleB.pdf",

                                assemblyPic1: "data/2005/assembly/purpleAssembly.jpg",
                                assemblyContract1: "data/2005/assembly/purpleContract.pdf",

                                techPic1: "data/2005/tech/photos/Purple1.jpg",
                                techPic2: "data/2005/tech/photos/Purple2.jpg",
                                techMov1: "data/2005/tech/movies/Purple.mov",
                                techContract1: "data/2005/tech/extras/Purple_product_contract.pdf",

                                finalPic1: "data/2005/final/photos/purple1.jpg",
                                finalPic2: "data/2005/final/photos/purple2.jpg",
                                finalMov1: "data/2005/final/movies/purple.mov",
                                finalSlide1: "data/2005/final/slides/purple.ppt",
                                finalBrochure1: "data/2005/final/extras/purpleBrochure.pdf",
                                finalBrochure2: null,
                        ],
                ],
        ],
]