[
        "2014": [
                themeYear: "2014", // folder name
                themeName: "Adventure",
                themeDesc: "Any viable, meaningful product idea related to 'adventure' is a potential candidate&mdash;exploration, recreation, entertainment, extreme sports, medical devices, manufacturing, family, story telling and life touch upon the theme.",
                highlights: [
                        [ linkLabel: "Home page and slide show", linkUrl: "data/2014/homepage/index.html" ],
                        [ linkLabel: "Student tribute", linkUrl: "data/2014/highlights/student_tribute_2014.mp4", onClick: "window.open('data/2014/highlights/student_tribute_2014.mp4', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                        
                        [ linkLabel: "Final Presentation: Program", linkUrl: "data/2014/highlights/program2014.pdf" ],
                        [ linkLabel: "Final Presentation: 5-min Compendium", linkUrl: "data/2014/highlights/5_min_web_360p.mp4", onClick: "window.open('data/2014/highlights/5_min_web_360p.mp4', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Final Presentation: Full Show", linkUrl: "data/2014/highlights/full_show_2014.mp4", onClick: "window.open('data/2014/highlights/full_show_2014.mp4', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Final Presentation: Timelapse", linkUrl: "data/2014/highlights/finalPresentationDay_2014.mp4", onClick: "window.open('data/2014/highlights/finalPresentationDay_2014.mp4', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Final Presentation: Projection Mapping", linkUrl: "data/2014/highlights/projection_mapping_process.mp4", onClick: "window.open('data/2014/highlights/projection_mapping_process.mp4', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        
                        [ linkLabel: "Balloon Challenge 2014", linkUrl: "data/2014/highlights/balloon_2014.mp4", onClick: "window.open('data/2014/highlights/balloon_2014.mp4', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Build Challenge 2014: Hot Lava", linkUrl: "data/2014/highlights/challenge_2014.mp4", onClick: "window.open('data/2014/highlights/challenge_2014.mp4', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Pink team: How did they get there?", linkUrl: "data/2014/highlights/pink_team_2014.mp4", onClick: "window.open('data/2014/highlights/pink_team_2014.mp4', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Project theme of 2014", linkUrl: "data/2014/homepage/project/projectTheme.html" ],
                        
                        [ linkLabel: "Thank you, Prof. Wallace!", linkUrl: "data/2014/highlights/thankyou_2014.mp4", onClick: "window.open('data/2014/highlights/thankyou_2014.mp4', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "2.009 in the Boston Globe", linkUrl: "http://www.bostonglobe.com/business/2015/02/05/learning-art-pitch-mit/9LR1q7PT1KvjS1mpzNBoRL/story.html" ],
                  
                ],
                highlightDividerIndexes: [1, 11],
                sketchMovWidth: 320,
                sketchMovHeight: 180,
                mockMovWidth: 320,
                mockMovHeight: 180, //changed from 195
                techMovWidth: 320,
                techMovHeight: 180, //changed from 195
                finalMovWidth: 640,
                finalMovHeight: 360, //changed from 376
                useNewVideoPlayer: true,
                picWidth: 240, // picHeight is determined dynamically
                projects: [
                        [
                                projId: "Origin", // folder name
                                projName: "Origin",
                                projDesc: "proximity device",
                                projColor: "pink",
                                projTeam: "Caitlin Mackey, Charles Vitry, Elizabeth Schanne, Erik Klatt, Hans Susilo, Joyce Chen, Laith Maswadeh, Lulu Xlong, Nafea Alwafi, Nicci Cazares, Ryan Fish, Ryan McDermott, Austin Osborne, Ayman Alomar, Banks Hunter, Daniel Wang, Debbie Ajilo, Dillon McConnon, Francisco Vargas, Georgia Van de Zande, Natasha Boghani, Staly Chin, Ta Corrales Sanchez, Victor Hung",
                                projCode: "data/2014/homepage/codeOfEthics/codeOfEthics.html#pink",
                                
                                ideasPic1: "data/2014/ideas/PinkA1.jpg",
                                ideasPic2: "data/2014/ideas/PinkA2.jpg",
                                ideasPic3: "data/2014/ideas/PinkA3.jpg",
                                ideasPic4: "data/2014/ideas/PinkB1.jpg",
                                ideasPic5: "data/2014/ideas/PinkB2.jpg",
                                ideasPic6: "data/2014/ideas/PinkB3.jpg",

                                sketchName1: "EveryWear",
                                sketchName2: "CoolKeep",
                                sketchName3: "PT: Personal Therapy",
                                sketchName4: "Fast Field",
                                sketchName5: "Aqua Boots",
                                sketchName6: "Ice Check",
                                sketchPic1: "data/2014/sketch/photos/pinkA1_1.jpg",
                                sketchPic2: "data/2014/sketch/photos/pinkA1_2.jpg",
                                sketchPic3: "data/2014/sketch/photos/pinkA2_1.jpg",
                                sketchPic4: "data/2014/sketch/photos/pinkA2_2.jpg",
                                sketchPic5: "data/2014/sketch/photos/pinkA3_1.jpg",
                                sketchPic6: "data/2014/sketch/photos/pinkA3_2.jpg",
                                sketchPic7: "data/2014/sketch/photos/pinkB1_1.jpg",
                                sketchPic8: "data/2014/sketch/photos/pinkB1_2.png",
                                sketchPic9: "data/2014/sketch/photos/pinkB2_1.png",
                                sketchPic10: "data/2014/sketch/photos/pinkB2_2.jpg",
                                sketchPic11: "data/2014/sketch/photos/pinkB3_1.jpg",
                                sketchPic12: "data/2014/sketch/photos/pinkB3_2.jpg",
                                
                                sketchMov1: "data/2014/sketch/movies/pinkA1",
                                sketchMov2: "data/2014/sketch/movies/pinkA2",
                                sketchMov3: "data/2014/sketch/movies/pinkA3",
                                sketchMov4: "data/2014/sketch/movies/pinkB1",
                                sketchMov5: "data/2014/sketch/movies/pinkB2",
                                sketchMov6: "data/2014/sketch/movies/pinkB3",
                                sketchSlide1: "data/2014/sketch/slides/pinkA1.pdf",
                                sketchSlide2: "data/2014/sketch/slides/pinkA2.pdf",
                                sketchSlide2: "data/2014/sketch/slides/pinkA3.pdf",
                                sketchSlide3: "data/2014/sketch/slides/pinkB1.pdf",
                                sketchSlide4: "data/2014/sketch/slides/pinkB2.pdf",
                                sketchSlide4: "data/2014/sketch/slides/pinkB3.pdf",

                                mockName1: "CoolKeep",
                                mockName2: "PT: Personal Therapy",
                                mockName3: "IceCheck",
                                mockName4: "ProxBand",
                                mockPic1: "data/2014/mockup/photos/pinkA1_1.jpg",
                                mockPic2: "data/2014/mockup/photos/pinkA1_2.jpg",
                                mockPic3: "data/2014/mockup/photos/pinkA2_1.jpg",
                                mockPic4: "data/2014/mockup/photos/pinkA2_2.jpg",
                                mockPic5: "data/2014/mockup/photos/pinkB1_1.jpg",
                                mockPic6: "data/2014/mockup/photos/pinkB1_2.jpg",
                                mockPic7: "data/2014/mockup/photos/pinkB2_1.jpg",
                                mockPic8: "data/2014/mockup/photos/pinkB2_2.jpg",
                                mockMov1: "data/2014/mockup/movies/pinkA1",
                                mockMov2: "data/2014/mockup/movies/pinkA2",
                                mockMov3: "data/2014/mockup/movies/pinkB1",
                                mockMov4: "data/2014/mockup/movies/pinkB2",
                                mockSlide1: "data/2014/mockup/slides/pinkA1.pdf",
                                mockSlide2: "data/2014/mockup/slides/pinkA2.pdf",
                                mockSlide3: "data/2014/mockup/slides/pinkB1.pdf",
                                mockSlide4: "data/2014/mockup/slides/pinkB2.pdf",

                                assemblyPic1: "data/2014/assembly/pinkAssembly.png",
                                assemblyContract1: "data/2014/assembly/pinkContract.pdf",

                                techPic1: "data/2014/tech/photos/Pink1.jpg",
                                techPic2: "data/2014/tech/photos/Pink2.jpg",
                                techMov1: "data/2014/tech/movies/Pink",

                                finalPic1: "data/2014/final/photos/original/pink1.jpg",
                                finalPic1Thumb: "data/2014/final/photos/small/pink1.jpg",
                                finalPic2: "data/2014/final/photos/original/pink2.jpg",
                                finalPic2Thumb: "data/2014/final/photos/small/pink2.jpg",
                                finalMov1: "data/2014/final/movies/pink",
                                finalSlide1: "data/2014/final/slides/pink.pdf",
                                finalBrochure1: "data/2014/final/extras/Pink_Origin_brochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Terrainer", // folder name
                                projName: "Terrainer",
                                projDesc: "bike trainer",
                                projColor: "blue",
                                projTeam: "Bitzy Flamholz, Cameron Wagar, Delphine Kaiser, Helena Wang, Jack Queeney, Jenna Klein, Justin White, Naina Mehta, Parker Chambers, Samantha Darryanto, Sebastian Joseph, Sherry Ren, Amelia Brooks, Annie LaBine, Aziz Tunusi, Cathy Zhou, Chris Cho, Fernando Nunez, Juanita Ballesteros, Karen Hao, Mario Martinez, Ricardo De Armas, Sultan Alsubaihin, Teresa Ho",
                                projCode: "data/2014/homepage/codeOfEthics/codeOfEthics.html#blue",
                                
                                ideasPic1: "data/2014/ideas/BlueA1.jpg",
                                ideasPic2: "data/2014/ideas/BlueA2.jpg",
                                ideasPic3: "data/2014/ideas/BlueA3.jpg",
                                ideasPic4: "data/2014/ideas/BlueB1.jpg",
                                ideasPic5: "data/2014/ideas/BlueB2.jpg",
                                ideasPic6: "data/2014/ideas/BlueB3.jpg",

                                sketchName1: "SpongeAssured",
                                sketchName2: "Bicycooler",
                                sketchName3: "Terrainer",
                                sketchName4: "Clutch Crutch",
                                sketchName5: "FlowAssist",
                                sketchName6: "HandHero",
                                sketchPic1: "data/2014/sketch/photos/blueA1_1.jpg",
                                sketchPic2: "data/2014/sketch/photos/blueA1_2.jpg",
                                sketchPic3: "data/2014/sketch/photos/blueA2_1.jpg",
                                sketchPic4: "data/2014/sketch/photos/blueA2_2.jpg",
                                sketchPic5: "data/2014/sketch/photos/blueA3_1.jpg",
                                sketchPic6: "data/2014/sketch/photos/blueA3_2.jpg",
                                sketchPic7: "data/2014/sketch/photos/blueB1_1.jpg",
                                sketchPic8: "data/2014/sketch/photos/blueB1_2.jpg",
                                sketchPic9: "data/2014/sketch/photos/blueB2_1.jpg",
                                sketchPic10: "data/2014/sketch/photos/blueB2_2.jpg",
                                sketchPic11: "data/2014/sketch/photos/blueB3_1.jpg",
                                sketchPic12: "data/2014/sketch/photos/blueB3_2.jpg",
                                
                                sketchMov1: "data/2014/sketch/movies/blueA1",
                                sketchMov2: "data/2014/sketch/movies/blueA2",
                                sketchMov3: "data/2014/sketch/movies/blueA3",
                                sketchMov4: "data/2014/sketch/movies/blueB1",
                                sketchMov5: "data/2014/sketch/movies/blueB2",
                                sketchMov6: "data/2014/sketch/movies/blueB3",
                                sketchSlide1: "data/2014/sketch/slides/blueA1.pdf",
                                sketchSlide2: "data/2014/sketch/slides/blueA2.pdf",
                                sketchSlide2: "data/2014/sketch/slides/blueA3.pdf",
                                sketchSlide3: "data/2014/sketch/slides/blueB1.pdf",
                                sketchSlide4: "data/2014/sketch/slides/blueB2.pdf",
                                sketchSlide4: "data/2014/sketch/slides/blueB3.pdf",

                                mockName1: "Terrainer",
                                mockName2: "SpongeAssured",
                                mockName3: "Mens et Manus",
                                mockName4: "Clutch Crutch",
                                mockPic1: "data/2014/mockup/photos/blueA1_1.jpg",
                                mockPic2: "data/2014/mockup/photos/blueA1_2.jpg",
                                mockPic3: "data/2014/mockup/photos/blueA2_1.jpg",
                                mockPic4: "data/2014/mockup/photos/blueA2_2.jpg",
                                mockPic5: "data/2014/mockup/photos/blueB1_1.jpg",
                                mockPic6: "data/2014/mockup/photos/blueB1_2.jpg",
                                mockPic7: "data/2014/mockup/photos/blueB2_1.jpg",
                                mockPic8: "data/2014/mockup/photos/blueB2_2.jpg",
                                mockMov1: "data/2014/mockup/movies/blueA1",
                                mockMov2: "data/2014/mockup/movies/blueA2",
                                mockMov3: "data/2014/mockup/movies/blueB1",
                                mockMov4: "data/2014/mockup/movies/blueB2",
                                mockSlide1: "data/2014/mockup/slides/blueA1.pdf",
                                mockSlide2: "data/2014/mockup/slides/blueA2.pdf",
                                mockSlide3: "data/2014/mockup/slides/blueB1.pdf",
                                mockSlide4: "data/2014/mockup/slides/blueB2.pdf",

                                assemblyPic1: "data/2014/assembly/blueAssembly.jpg",
                                assemblyContract1: "data/2014/assembly/blueContract.pdf",

                                techPic1: "data/2014/tech/photos/Blue1.jpg",
                                techPic2: "data/2014/tech/photos/Blue2.jpg",
                                techMov1: "data/2014/tech/movies/Blue",

                                finalPic1: "data/2014/final/photos/original/blue1.jpg",
                                finalPic1Thumb: "data/2014/final/photos/small/blue1.jpg",
                                finalPic2: "data/2014/final/photos/original/blue2.jpg",
                                finalPic2Thumb: "data/2014/final/photos/small/blue2.jpg",
                                finalMov1: "data/2014/final/movies/blue",
                                finalSlide1: "data/2014/final/slides/blue.pdf",
                                finalBrochure1: "data/2014/final/extras/Blue_Terraner_brochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Contour", // folder name
                                projName: "Contour",
                                projDesc: "comfortable prosthetic leg",
                                projColor: "silver",
                                projTeam: "Abdiel Mireles, Al Mireault, Aleksya Aguirre, Brian Alvarez, Chris Cook, David Bian, Diana Rosales, Feyza Haskaraman, Kiele Miller Oana, Kyle Veldman, Quantum Wei, Alexander Lukas, Brendon Chiu, Darci Reed, Elyud Ismail, Ernesto Ramirez, Luis Carbajal, Meisha Brooks, Mohammed Al-Zayer, Perla Villarreal, Simon Okaine, Zack Bright",
                                projCode: "data/2014/homepage/codeOfEthics/codeOfEthics.html#silver",
                                
                                ideasPic1: "data/2014/ideas/SilverA1.jpg",
                                ideasPic2: "data/2014/ideas/SilverA2.jpg",
                                ideasPic3: "data/2014/ideas/SilverA3.jpg",
                                ideasPic4: "data/2014/ideas/SilverB1.jpg",
                                ideasPic5: "data/2014/ideas/SilverB2.jpg",
                                ideasPic6: "data/2014/ideas/SilverB3.jpg",

                                sketchName1: "Imagilimb",
                                sketchName2: "Habitus",
                                sketchName3: "LetMilk",
                                sketchName4: "Walkable Splint",
                                sketchName5: "Free Wheelie",
                                sketchName6: "ReShape",
                                sketchPic1: "data/2014/sketch/photos/silverA1_1.jpg",
                                sketchPic2: "data/2014/sketch/photos/silverA1_2.jpg",
                                sketchPic3: "data/2014/sketch/photos/silverA2_1.jpg",
                                sketchPic4: "data/2014/sketch/photos/silverA2_2.jpg",
                                sketchPic5: "data/2014/sketch/photos/silverA3_1.jpg",
                                sketchPic6: "data/2014/sketch/photos/silverA3_2.jpg",
                                sketchPic7: "data/2014/sketch/photos/silverB1_1.jpg",
                                sketchPic8: "data/2014/sketch/photos/silverB1_2.jpg",
                                sketchPic9: "data/2014/sketch/photos/silverB2_1.jpg",
                                sketchPic10: "data/2014/sketch/photos/silverB2_2.jpg",
                                sketchPic11: "data/2014/sketch/photos/silverB3_1.jpg",
                                sketchPic12: "data/2014/sketch/photos/silverB3_2.jpg",
                                sketchMov1: "data/2014/sketch/movies/silverA1",
                                sketchMov2: "data/2014/sketch/movies/silverA2",
                                sketchMov3: "data/2014/sketch/movies/silverA3",
                                sketchMov4: "data/2014/sketch/movies/silverB1",
                                sketchMov5: "data/2014/sketch/movies/silverB2",
                                sketchMov6: "data/2014/sketch/movies/silverB3",
                                sketchSlide1: "data/2014/sketch/slides/silverA1.pdf",
                                sketchSlide2: "data/2014/sketch/slides/silverA2.pdf",
                                sketchSlide2: "data/2014/sketch/slides/silverA3.pdf",
                                sketchSlide3: "data/2014/sketch/slides/silverB1.pdf",
                                sketchSlide4: "data/2014/sketch/slides/silverB2.pdf",
                                sketchSlide4: "data/2014/sketch/slides/silverB3.pdf",

                                mockName1: "Align",
                                mockName2: "Let Milk",
                                mockName3: "ReShape",
                                mockName4: "FreeWheelie",
                                mockPic1: "data/2014/mockup/photos/silverA1_1.jpg",
                                mockPic2: "data/2014/mockup/photos/silverA1_2.jpg",
                                mockPic3: "data/2014/mockup/photos/silverA2_1.jpg",
                                mockPic4: "data/2014/mockup/photos/silverA2_2.jpg",
                                mockPic5: "data/2014/mockup/photos/silverB1_1.jpg",
                                mockPic6: "data/2014/mockup/photos/silverB1_2.jpg",
                                mockPic7: "data/2014/mockup/photos/silverB2_1.jpg",
                                mockPic8: "data/2014/mockup/photos/silverB2_2.jpg",
                                mockMov1: "data/2014/mockup/movies/silverA1",
                                mockMov2: "data/2014/mockup/movies/silverA2",
                                mockMov3: "data/2014/mockup/movies/silverB1",
                                mockMov4: "data/2014/mockup/movies/silverB2",
                                mockSlide1: "data/2014/mockup/slides/silverA1.pdf",
                                mockSlide2: "data/2014/mockup/slides/silverA2.pdf",
                                mockSlide3: "data/2014/mockup/slides/silverB1.pdf",
                                mockSlide4: "data/2014/mockup/slides/silverB2.pdf",

                                assemblyPic1: "data/2014/assembly/silverAssembly.jpg",
                                assemblyContract1: "data/2014/assembly/silverContract.pdf",

                                techPic1: "data/2014/tech/photos/Sivler1.jpg",
                                techPic2: "data/2014/tech/photos/Silver2.jpg",
                                techMov1: "data/2014/tech/movies/Silver",

                                finalPic1: "data/2014/final/photos/original/silver1.jpg",
                                finalPic1Thumb: "data/2014/final/photos/small/silver1.jpg",
                                finalPic2: "data/2014/final/photos/original/silver2.jpg",
                                finalPic2Thumb: "data/2014/final/photos/small/silver2.jpg",
                                finalMov1: "data/2014/final/movies/silver",
                                finalSlide1: "data/2014/final/slides/silver.pdf",
                                finalBrochure1: "data/2014/final/extras/Silver_Contour_brochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "UpBeat", // folder name
                                projName: "UpBeat",
                                projDesc: "drum trainer",
                                projColor: "purple",
                                projTeam: "Aarti Anturkar, Alex Gilbert, Andrew Busse, Antonia Warner, Bruna Moscol, Chris Davidson, Eddie Farias, Erin Bailie, Isabella Hurtado-Braun, Miles Burr, Nathan Spielberg, Saya Date, Shreya Dave, Alice Huang, Angela Ha, Brad Eckert, Connor Humber, Dennis Levene, Emma Feshbach, Jonathan Lambert, Margaret Coad, Nick Diamantoni, Paige Reiter, Sarah Fay, Stephen Suen, Xiaoyue Xie",
                                projCode: "data/2014/homepage/codeOfEthics/codeOfEthics.html#purple",
                                
                                ideasPic1: "data/2014/ideas/PurpleA1.jpg",
                                ideasPic2: "data/2014/ideas/PurpleA2.jpg",
                                ideasPic3: "data/2014/ideas/PurpleA3.jpg",
                                ideasPic4: "data/2014/ideas/PurpleB1.jpg",
                                ideasPic5: "data/2014/ideas/PurpleB2.jpg",
                                ideasPic6: "data/2014/ideas/PurpleB3.jpg",

                                sketchName1: "eDrum",
                                sketchName2: "Arch",
                                sketchName3: "Tunescriber",
                                sketchName4: "The Waypointer",
                                sketchName5: "Lumos - Helmet",
                                sketchName6: "Lumos - Controller",
                                sketchPic1: "data/2014/sketch/photos/purpleA1_1.jpg",
                                sketchPic2: "data/2014/sketch/photos/purpleA1_2.jpg",
                                sketchPic3: "data/2014/sketch/photos/purpleA2_1.jpg",
                                sketchPic4: "data/2014/sketch/photos/purpleA2_2.jpg",
                                sketchPic5: "data/2014/sketch/photos/purpleA3_1.jpg",
                                sketchPic6: "data/2014/sketch/photos/purpleA3_2.jpg",
                                sketchPic7: "data/2014/sketch/photos/purpleB1_1.jpg",
                                sketchPic8: "data/2014/sketch/photos/purpleB1_2.jpg",
                                sketchPic9: "data/2014/sketch/photos/purpleB2_1.jpg",
                                sketchPic10: "data/2014/sketch/photos/purpleB2_2.jpg",
                                sketchPic11: "data/2014/sketch/photos/purpleB3_1.jpg",
                                sketchPic12: "data/2014/sketch/photos/purpleB3_2.jpg",
                                sketchMov1: "data/2014/sketch/movies/purpleA1",
                                sketchMov2: "data/2014/sketch/movies/purpleA2",
                                sketchMov3: "data/2014/sketch/movies/purpleA3",
                                sketchMov4: "data/2014/sketch/movies/purpleB1",
                                sketchMov5: "data/2014/sketch/movies/purpleB2",
                                sketchMov6: "data/2014/sketch/movies/purpleB3",
                                sketchSlide1: "data/2014/sketch/slides/purpleA1.pdf",
                                sketchSlide2: "data/2014/sketch/slides/purpleA2.pdf",
                                sketchSlide2: "data/2014/sketch/slides/purpleA3.pdf",
                                sketchSlide3: "data/2014/sketch/slides/purpleB1.pdf",
                                sketchSlide4: "data/2014/sketch/slides/purpleB2.pdf",
                                sketchSlide4: "data/2014/sketch/slides/purpleB3.pdf",

                                mockName1: "eDrum",
                                mockName2: "Mogul Mill",
                                mockName3: "Lumos",
                                mockName4: "Waypointer",
                                mockPic1: "data/2014/mockup/photos/purpleA1_1.jpg",
                                mockPic2: "data/2014/mockup/photos/purpleA1_2.jpg",
                                mockPic3: "data/2014/mockup/photos/purpleA2_1.jpg",
                                mockPic4: "data/2014/mockup/photos/purpleA2_2.jpg",
                                mockPic5: "data/2014/mockup/photos/purpleB1_1.jpg",
                                mockPic6: "data/2014/mockup/photos/purpleB1_2.jpg",
                                mockPic7: "data/2014/mockup/photos/purpleB2_1.jpg",
                                mockPic8: "data/2014/mockup/photos/purpleB2_2.jpg",
                                mockMov1: "data/2014/mockup/movies/purpleA1",
                                mockMov2: "data/2014/mockup/movies/purpleA2",
                                mockMov3: "data/2014/mockup/movies/purpleB1",
                                mockMov4: "data/2014/mockup/movies/purpleB2",
                                mockSlide1: "data/2014/mockup/slides/purpleA1.pdf",
                                mockSlide2: "data/2014/mockup/slides/purpleA2.pdf",
                                mockSlide3: "data/2014/mockup/slides/purpleB1.pdf",
                                mockSlide4: "data/2014/mockup/slides/purpleB2.pdf",

                                assemblyPic1: "data/2014/assembly/purpleAssembly.jpg",
                                assemblyContract1: "data/2014/assembly/purpleContract.pdf",

                                techPic1: "data/2014/tech/photos/Purple1.jpg",
                                techPic2: "data/2014/tech/photos/Purple2.jpg",
                                techMov1: "data/2014/tech/movies/Purple",

                                finalPic1: "data/2014/final/photos/original/purple1.jpg",
                                finalPic1Thumb: "data/2014/final/photos/small/purple1.jpg",
                                finalPic2: "data/2014/final/photos/original/purple2.jpg",
                                finalPic2Thumb: "data/2014/final/photos/small/purple2.jpg",
                                finalMov1: "data/2014/final/movies/purple",
                                finalSlide1: "data/2014/final/slides/purple.pdf",
                                finalBrochure1: "data/2014/final/extras/Purple_UpBeat_brochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Wali", // folder name
                                projName: "Wali",
                                projDesc: "baby gate",
                                projColor: "green",
                                projTeam: "Abraham Garza, Andrea Arce, Diana Valero, Emily TenCate, Erik Pearson, Kathy Yang, Kyle Bowman, Michael Everett, Noa Flaherty, Paelle Powell, Rene Miller, Spencer Boone, Aileen Gutmann, Camille Richman, David McClelland, Estefania Avila, Henry Nassif, Jeremy Bernstein, Kelly Wang, Kirsten Lim, Matthew Hildner, Oliver Gilliland, Rashed Al-Rashed, Sam Parker",
                                projCode: "data/2014/homepage/codeOfEthics/codeOfEthics.html#green",
                                
                                ideasPic1: "data/2014/ideas/GreenA1.jpg",
                                ideasPic2: "data/2014/ideas/GreenA2.jpg",
                                ideasPic3: "data/2014/ideas/GreenA3.jpg",
                                ideasPic4: "data/2014/ideas/GreenB1.jpg",
                                ideasPic5: "data/2014/ideas/GreenB2.jpg",
                                ideasPic6: "data/2014/ideas/GreenB3.jpg",

                                sketchName1: "TreeFort",
                                sketchName2: "In-Fence",
                                sketchName3: "Fido Sled",
                                sketchName4: "Float Assist",
                                sketchName5: "Ventus",
                                sketchName6: "Dry-Venture",
                                sketchPic1: "data/2014/sketch/photos/greenA1_1.jpg",
                                sketchPic2: "data/2014/sketch/photos/greenA1_2.jpg",
                                sketchPic3: "data/2014/sketch/photos/greenA2_1.jpg",
                                sketchPic4: "data/2014/sketch/photos/greenA2_2.jpg",
                                sketchPic5: "data/2014/sketch/photos/greenA3_1.jpg",
                                sketchPic6: "data/2014/sketch/photos/greenA3_2.jpg",
                                sketchPic7: "data/2014/sketch/photos/greenB1_1.jpg",
                                sketchPic8: "data/2014/sketch/photos/greenB1_2.jpg",
                                sketchPic9: "data/2014/sketch/photos/greenB2_1.jpg",
                                sketchPic10: "data/2014/sketch/photos/greenB2_2.jpg",
                                sketchPic11: "data/2014/sketch/photos/greenB3_1.jpg",
                                sketchPic12: "data/2014/sketch/photos/greenB3_2.jpg",
                                sketchMov1: "data/2014/sketch/movies/greenA1",
                                sketchMov2: "data/2014/sketch/movies/greenA2",
                                sketchMov3: "data/2014/sketch/movies/greenA3",
                                sketchMov4: "data/2014/sketch/movies/greenB1",
                                sketchMov5: "data/2014/sketch/movies/greenB2",
                                sketchMov6: "data/2014/sketch/movies/greenB3",
                                sketchSlide1: "data/2014/sketch/slides/greenA1.pdf",
                                sketchSlide2: "data/2014/sketch/slides/greenA2.pdf",
                                sketchSlide2: "data/2014/sketch/slides/greenA3.pdf",
                                sketchSlide3: "data/2014/sketch/slides/greenB1.pdf",
                                sketchSlide4: "data/2014/sketch/slides/greenB2.pdf",
                                sketchSlide4: "data/2014/sketch/slides/greenB3.pdf",

                                mockName1: "TreeFort",
                                mockName2: "In-Fence",
                                mockName3: "Dry-Venture",
                                mockName4: "Statera",
                                mockPic1: "data/2014/mockup/photos/greenA1_1.jpg",
                                mockPic2: "data/2014/mockup/photos/greenA1_2.jpg",
                                mockPic3: "data/2014/mockup/photos/greenA2_1.jpg",
                                mockPic4: "data/2014/mockup/photos/greenA2_2.jpg",
                                mockPic5: "data/2014/mockup/photos/greenB1_1.jpg",
                                mockPic6: "data/2014/mockup/photos/greenB1_2.jpg",
                                mockPic7: "data/2014/mockup/photos/greenB2_1.jpg",
                                mockPic8: "data/2014/mockup/photos/greenB2_2.jpg",
                                mockMov1: "data/2014/mockup/movies/greenA1",
                                mockMov2: "data/2014/mockup/movies/greenA2",
                                mockMov3: "data/2014/mockup/movies/greenB1",
                                mockMov4: "data/2014/mockup/movies/greenB2",
                                mockSlide1: "data/2014/mockup/slides/greenA1.pdf",
                                mockSlide2: "data/2014/mockup/slides/greenA2.pdf",
                                mockSlide3: "data/2014/mockup/slides/greenB1.pdf",
                                mockSlide4: "data/2014/mockup/slides/greenB2.pdf",

                                assemblyPic1: "data/2014/assembly/greenAssembly.jpg",
                                assemblyContract1: "data/2014/assembly/greenContract.pdf",

                                techPic1: "data/2014/tech/photos/Green1.jpg",
                                techPic2: "data/2014/tech/photos/Green2.jpg",
                                techMov1: "data/2014/tech/movies/Green",

                                finalPic1: "data/2014/final/photos/original/green1.jpg",
                                finalPic1Thumb: "data/2014/final/photos/small/green1.jpg",
                                finalPic2: "data/2014/final/photos/original/green2.jpg",
                                finalPic2Thumb: "data/2014/final/photos/small/green2.jpg",
                                finalMov1: "data/2014/final/movies/green",
                                finalSlide1: "data/2014/final/slides/green.pdf",
                                finalBrochure1: "data/2014/final/extras/Green_Wali_brochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Otto", // folder name
                                projName: "Otto",
                                projDesc: "longboard brake",
                                projColor: "red",
                                projTeam: "Alex Warner, Amanda Wang, Jake Sanchez, Jody Fu, Joey Campion, Makai Cartman, Molly Donaldson, Nelson Brock, Ola Kalinowska, Paul Dawson, Rachael Aptowitz, Yinong Liu, Alexxis Isaac, Andrew Young, Ayantu Regassa, Cole Houston, Fro Myers, James Logan, Larissa Senatus, Michelle Lee, Nik Albarran, Sophie Seidell, Suhail Idrees, Will Pritchett, Zianga Abraham",
                                projCode: "data/2014/homepage/codeOfEthics/codeOfEthics.html#red",
                                
                                ideasPic1: "data/2014/ideas/RedA1.jpg",
                                ideasPic2: "data/2014/ideas/RedA2.jpg",
                                ideasPic3: "data/2014/ideas/RedA3.jpg",
                                ideasPic4: "data/2014/ideas/RedB1.jpg",
                                ideasPic5: "data/2014/ideas/RedB2.jpg",
                                ideasPic6: "data/2014/ideas/RedB3.jpg",

                                sketchName1: "TransVend",
                                sketchName2: "GeniLite",
                                sketchName3: "WheelAssist",
                                sketchName4: "Aquapod",
                                sketchName5: "Ghostbraker",
                                sketchName6: "ChesseShack and BrewHouse",
                                sketchPic1: "data/2014/sketch/photos/redA1_1.jpg",
                                sketchPic2: "data/2014/sketch/photos/redA1_2.jpg",
                                sketchPic3: "data/2014/sketch/photos/redA2_1.jpg",
                                sketchPic4: "data/2014/sketch/photos/redA2_2.jpg",
                                sketchPic5: "data/2014/sketch/photos/redA3_1.jpg",
                                sketchPic6: "data/2014/sketch/photos/redA3_2.jpg",
                                sketchPic7: "data/2014/sketch/photos/redB1_1.jpg",
                                sketchPic8: "data/2014/sketch/photos/redB1_2.jpg",
                                sketchPic9: "data/2014/sketch/photos/redB2_1.jpg",
                                sketchPic10: "data/2014/sketch/photos/redB2_2.jpg",
                                sketchPic11: "data/2014/sketch/photos/redB3_1.jpg",
                                sketchPic12: "data/2014/sketch/photos/redB3_2.jpg",
                                sketchMov1: "data/2014/sketch/movies/redA1",
                                sketchMov2: "data/2014/sketch/movies/redA2",
                                sketchMov3: "data/2014/sketch/movies/redA3",
                                sketchMov4: "data/2014/sketch/movies/redB1",
                                sketchMov5: "data/2014/sketch/movies/redB2",
                                sketchMov6: "data/2014/sketch/movies/redB3",
                                sketchSlide1: "data/2014/sketch/slides/redA1.pdf",
                                sketchSlide2: "data/2014/sketch/slides/redA2.pdf",
                                sketchSlide2: "data/2014/sketch/slides/redA3.pdf",
                                sketchSlide3: "data/2014/sketch/slides/redB1.pdf",
                                sketchSlide4: "data/2014/sketch/slides/redB2.pdf",
                                sketchSlide4: "data/2014/sketch/slides/redB3.pdf",

                                mockName1: "Transvend",
                                mockName2: "WheelAssist",
                                mockName3: "GhostBraker",
                                mockName4: "BrewHouse",
                                mockPic1: "data/2014/mockup/photos/redA1_1.jpg",
                                mockPic2: "data/2014/mockup/photos/redA1_2.jpg",
                                mockPic3: "data/2014/mockup/photos/redA2_1.jpg",
                                mockPic4: "data/2014/mockup/photos/redA2_2.jpg",
                                mockPic5: "data/2014/mockup/photos/redB1_1.jpg",
                                mockPic6: "data/2014/mockup/photos/redB1_2.jpg",
                                mockPic7: "data/2014/mockup/photos/redB2_1.jpg",
                                mockPic8: "data/2014/mockup/photos/redB2_2.jpg",
                                mockMov1: "data/2014/mockup/movies/redA1",
                                mockMov2: "data/2014/mockup/movies/redA2",
                                mockMov3: "data/2014/mockup/movies/redB1",
                                mockMov4: "data/2014/mockup/movies/redB2",
                                mockSlide1: "data/2014/mockup/slides/redA1.pdf",
                                mockSlide2: "data/2014/mockup/slides/redA2.pdf",
                                mockSlide3: "data/2014/mockup/slides/redB1.pdf",
                                mockSlide4: "data/2014/mockup/slides/redB2.pdf",

                                assemblyPic1: "data/2014/assembly/redAssembly.jpg",
                                assemblyContract1: "data/2014/assembly/redContract.pdf",

                                techPic1: "data/2014/tech/photos/Red1.jpg",
                                techPic2: "data/2014/tech/photos/Red2.jpg",
                                techMov1: "data/2014/tech/movies/Red",

                                finalPic1: "data/2014/final/photos/original/red1.jpg",
                                finalPic1Thumb: "data/2014/final/photos/small/red1.jpg",
                                finalPic2: "data/2014/final/photos/original/red2.jpg",
                                finalPic2Thumb: "data/2014/final/photos/small/red2.jpg",
                                finalMov1: "data/2014/final/movies/red",
                                finalSlide1: "data/2014/final/slides/red.pdf",
                                finalBrochure1: "data/2014/final/extras/Red_Otto_brochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Sunflower", // folder name
                                projName: "Sunflower",
                                projDesc: "baby warmer",
                                projColor: "yellow",
                                projTeam: "Andrew Acker, Ben Niewood, Catherine Fox, David Gilchrist, Gholson Glass, Jade Hardacker, K.K. Wopat, Matt Kim, Rachel McDermott, Saeed Fakeiha, Teresa Lin, Yasmin Inam, Abdullah Akbar, Brandon Wright, Cliodhna McCarthy, Eduardo Bacardi, Isaac Sosa, Jacob Haip, Jake Slonaker, Joanna So, Kristin Zimmerman, Lorcan Murphy, Sarah McMillian, Valerie Andersen",
                                projCode: "data/2014/homepage/codeOfEthics/codeOfEthics.html#yellow",
                                
                                ideasPic1: "data/2014/ideas/YellowA1.jpg",
                                ideasPic2: "data/2014/ideas/YellowA2.jpg",
                                ideasPic3: "data/2014/ideas/YellowA3.jpg",
                                ideasPic4: "data/2014/ideas/YellowB1.jpg",
                                ideasPic5: "data/2014/ideas/YellowB2.jpg",
                                ideasPic6: "data/2014/ideas/YellowB3.jpg",

                                sketchName1: "E-gen",
                                sketchName2: "Power Pole",
                                sketchName3: "The X",
                                sketchName4: "CoffeeGoGo",
                                sketchName5: "Tail-gater",
                                sketchName6: "Sunflower",
                                sketchPic1: "data/2014/sketch/photos/yellowA1_1.jpg",
                                sketchPic2: "data/2014/sketch/photos/yellowA1_2.jpg",
                                sketchPic3: "data/2014/sketch/photos/yellowA2_1.jpg",
                                sketchPic4: "data/2014/sketch/photos/yellowA2_2.jpg",
                                sketchPic5: "data/2014/sketch/photos/yellowA3_1.jpg",
                                sketchPic6: "data/2014/sketch/photos/yellowA3_2.jpg",
                                sketchPic7: "data/2014/sketch/photos/yellowB1_1.jpg",
                                sketchPic8: "data/2014/sketch/photos/yellowB1_2.jpg",
                                sketchPic9: "data/2014/sketch/photos/yellowB2_1.jpg",
                                sketchPic10: "data/2014/sketch/photos/yellowB2_2.jpg",
                                sketchPic11: "data/2014/sketch/photos/yellowB3_1.jpg",
                                sketchPic12: "data/2014/sketch/photos/yellowB3_2.jpg",
                                sketchMov1: "data/2014/sketch/movies/yellowA1",
                                sketchMov2: "data/2014/sketch/movies/yellowA2",
                                sketchMov3: "data/2014/sketch/movies/yellowA3",
                                sketchMov4: "data/2014/sketch/movies/yellowB1",
                                sketchMov5: "data/2014/sketch/movies/yellowB2",
                                sketchMov6: "data/2014/sketch/movies/yellowB3",
                                sketchSlide1: "data/2014/sketch/slides/yellowA1.pdf",
                                sketchSlide2: "data/2014/sketch/slides/yellowA2.pdf",
                                sketchSlide2: "data/2014/sketch/slides/yellowA3.pdf",
                                sketchSlide3: "data/2014/sketch/slides/yellowB1.pdf",
                                sketchSlide4: "data/2014/sketch/slides/yellowB2.pdf",
                                sketchSlide4: "data/2014/sketch/slides/yellowB3.pdf",

                                mockName1: "Sunflower",
                                mockName2: "K-Charge",
                                mockName3: "Smart Checkout",
                                mockName4: "E-Gen",
                                mockPic1: "data/2014/mockup/photos/yellowA1_1.jpg",
                                mockPic2: "data/2014/mockup/photos/yellowA1_2.jpg",
                                mockPic3: "data/2014/mockup/photos/yellowA2_1.jpg",
                                mockPic4: "data/2014/mockup/photos/yellowA2_2.jpg",
                                mockPic5: "data/2014/mockup/photos/yellowB1_1.jpg",
                                mockPic6: "data/2014/mockup/photos/yellowB1_2.jpg",
                                mockPic7: "data/2014/mockup/photos/yellowB2_1.jpg",
                                mockPic8: "data/2014/mockup/photos/yellowB2_2.jpg",
                                mockMov1: "data/2014/mockup/movies/yellowA1",
                                mockMov2: "data/2014/mockup/movies/yellowA2",
                                mockMov3: "data/2014/mockup/movies/yellowB1",
                                mockMov4: "data/2014/mockup/movies/yellowB2",
                                mockSlide1: "data/2014/mockup/slides/yellowA1.pdf",
                                mockSlide2: "data/2014/mockup/slides/yellowA2.pdf",
                                mockSlide3: "data/2014/mockup/slides/yellowB1.pdf",
                                mockSlide4: "data/2014/mockup/slides/yellowB2.pdf",

                                assemblyPic1: "data/2014/assembly/yellowAssembly.jpg",
                                assemblyContract1: "data/2014/assembly/yellowContract.pdf",

                                techPic1: "data/2014/tech/photos/Yellow1.jpg",
                                techPic2: "data/2014/tech/photos/Yellow2.jpg",
                                techMov1: "data/2014/tech/movies/Yellow",

                                finalPic1: "data/2014/final/photos/original/yellow1.jpg",
                                finalPic1Thumb: "data/2014/final/photos/small/yellow1.jpg",
                                finalPic2: "data/2014/final/photos/original/yellow2.jpg",
                                finalPic2Thumb: "data/2014/final/photos/small/yellow2.jpg",
                                finalMov1: "data/2014/final/movies/yellow",
                                finalSlide1: "data/2014/final/slides/yellow.pdf",
                                finalBrochure1: "data/2014/final/extras/Yellow_Sunflower_brochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "KOACH", // folder name
                                projName: "KOACH",
                                projDesc: "boxing trainer",
                                projColor: "orange",
                                projTeam: "Chantine Akiyama, Daniel Huertas, Hannah Barrett, Jack Clark, Jess Ong, Kelsey Seto, Nathan Landman, Priya Garg, Steven Guitron, Tara Ebsworth, Tye Ellis, Veronica Szklarzewski, Victoria Li, Dextina Booker, Emma Kane, Guilherme Venturelli Cavalheiro, Hannarae Nam, Hunter Guarino, John Thomas, Jose Smith, Morgan Stewart, Pat Capulong, Sterling Watson, Steve Sullivan, Xochitl Mellor",
                                projCode: "data/2014/homepage/codeOfEthics/codeOfEthics.html#orange",
                                
                                ideasPic1: "data/2014/ideas/OrangeA1.jpg",
                                ideasPic2: "data/2014/ideas/OrangeA2.jpg",
                                ideasPic3: "data/2014/ideas/OrangeA3.jpg",
                                ideasPic4: "data/2014/ideas/OrangeB1.jpg",
                                ideasPic5: "data/2014/ideas/OrangeB2.jpg",
                                ideasPic6: "data/2014/ideas/OrangeB3.jpg",

                                sketchName1: "Ruma Pump",
                                sketchName2: "Sonic Scrub",
                                sketchName3: "Handy Rail",
                                sketchName4: "KOACH",
                                sketchName5: "NapCap",
                                sketchName6: "StarTrekker",
                                sketchPic1: "data/2014/sketch/photos/orangeA1_1.jpg",
                                sketchPic2: "data/2014/sketch/photos/orangeA1_2.jpg",
                                sketchPic3: "data/2014/sketch/photos/orangeA2_1.jpg",
                                sketchPic4: "data/2014/sketch/photos/orangeA2_2.jpg",
                                sketchPic5: "data/2014/sketch/photos/orangeA3_1.jpg",
                                sketchPic6: "data/2014/sketch/photos/orangeA3_2.jpg",
                                sketchPic7: "data/2014/sketch/photos/orangeB1_1.jpg",
                                sketchPic8: "data/2014/sketch/photos/orangeB1_2.jpg",
                                sketchPic9: "data/2014/sketch/photos/orangeB2_1.jpg",
                                sketchPic10: "data/2014/sketch/photos/orangeB2_2.jpg",
                                sketchPic11: "data/2014/sketch/photos/orangeB3_1.jpg",
                                sketchPic12: "data/2014/sketch/photos/orangeB3_2.jpg",
                                sketchMov1: "data/2014/sketch/movies/orangeA1",
                                sketchMov2: "data/2014/sketch/movies/orangeA2",
                                sketchMov3: "data/2014/sketch/movies/orangeA3",
                                sketchMov4: "data/2014/sketch/movies/orangeB1",
                                sketchMov5: "data/2014/sketch/movies/orangeB2",
                                sketchMov6: "data/2014/sketch/movies/orangeB3",
                                sketchSlide1: "data/2014/sketch/slides/orangeA1.pdf",
                                sketchSlide2: "data/2014/sketch/slides/orangeA2.pdf",
                                sketchSlide2: "data/2014/sketch/slides/orangeA3.pdf",
                                sketchSlide3: "data/2014/sketch/slides/orangeB1.pdf",
                                sketchSlide4: "data/2014/sketch/slides/orangeB2.pdf",
                                sketchSlide4: "data/2014/sketch/slides/orangeB3.pdf",

                                mockName1: "KOACH",
                                mockName2: "Handy Rail",
                                mockName3: "Ruma Pump",
                                mockName4: "Cinemagraph",
                                mockPic1: "data/2014/mockup/photos/orangeA1_1.jpg",
                                mockPic2: "data/2014/mockup/photos/orangeA1_2.jpg",
                                mockPic3: "data/2014/mockup/photos/orangeA2_1.jpg",
                                mockPic4: "data/2014/mockup/photos/orangeA2_2.jpg",
                                mockPic5: "data/2014/mockup/photos/orangeB1_1.jpg",
                                mockPic6: "data/2014/mockup/photos/orangeB1_2.jpg",
                                mockPic7: "data/2014/mockup/photos/orangeB2_1.jpg",
                                mockPic8: "data/2014/mockup/photos/orangeB2_2.jpg",
                                mockMov1: "data/2014/mockup/movies/orangeA1",
                                mockMov2: "data/2014/mockup/movies/orangeA2",
                                mockMov3: "data/2014/mockup/movies/orangeB1",
                                mockMov4: "data/2014/mockup/movies/orangeB2",
                                mockSlide1: "data/2014/mockup/slides/orangeA1.pdf",
                                mockSlide2: "data/2014/mockup/slides/orangeA2.pdf",
                                mockSlide3: "data/2014/mockup/slides/orangeB1.pdf",
                                mockSlide4: "data/2014/mockup/slides/orangeB2.pdf",

                                assemblyPic1: "data/2014/assembly/orangeAssembly.jpg",
                                assemblyContract1: "data/2014/assembly/orangeContract.pdf",

                                techPic1: "data/2014/tech/photos/Orange1.jpg",
                                techPic2: "data/2014/tech/photos/Orange2.jpg",
                                techMov1: "data/2014/tech/movies/Orange",

                                finalPic1: "data/2014/final/photos/original/orange1.jpg",
                                finalPic1Thumb: "data/2014/final/photos/small/orange1.jpg",
                                finalPic2: "data/2014/final/photos/original/orange2.jpg",
                                finalPic2Thumb: "data/2014/final/photos/small/orange2.jpg",
                                finalMov1: "data/2014/final/movies/orange",
                                finalSlide1: "data/2014/final/slides/orange.pdf",
                                finalBrochure1: "data/2014/final/extras/Orange_KOACH_brochure.pdf",
                                finalBrochure2: null,
                        ],
                         
                   
                ],
        ],
]