[
        "2010": [
                themeYear: "2010", // folder name
                themeName: "Food",
                themeDesc: "Any viable, meaningful product idea related to the food industry is a potential candidate&mdash;sustainability, security, supply and safety, agriculture, animal welfare, health, manufacturing, distribution, preservation, food services, community farming, restaurants, and housewares.",
                highlights: [
                        [ linkLabel: "Home page and slide show", linkUrl: "data/2010/homepage/index.html" ],
                        [ linkLabel: "Student tribute", linkUrl: "data/2010/highlights/tributePublic_sm.mov", onClick: "window.open('data/2010/highlights/tributePublic_sm.mov', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Final presentation program", linkUrl: "data/2010/highlights/programme.pdf" ],
                        [ linkLabel: "Final presentation: 8-min compendium", linkUrl: "data/2010/highlights/8minWeb.mov", onClick: "window.open('data/2010/highlights/8minWeb.mov', 'movieWin', 'width=660,height=400,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Final presentation: full show", linkUrl: "data/2010/highlights/ShowForPublic.mov", onClick: "window.open('data/2010/highlights/ShowForPublic.mov', 'movieWin', 'width=660,height=400,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Human-powered fire starting devices", linkUrl: "data/2010/highlights/firestarting-video-2010-small.mov", onClick: "window.open('data/2010/highlights/firestarting-video-2010-small.mov', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Red team: How did they get there?", linkUrl: "data/2010/highlights/red-team-2010-small.mov", onClick: "window.open('data/2010/highlights/red-team-2010-small.mov', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Project theme of 2010", linkUrl: "data/2010/homepage/project/projectTheme.html" ],
                        [ linkLabel: "Product teardown exercise", linkUrl: "data/2010/highlights/teardown-exercise-2010.mov", onClick: "window.open('data/2010/highlights/teardown-exercise-2010.mov', 'movieWin', 'width=660,height=520,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "A tale of two critiques", linkUrl: "data/2010/highlights/tale-of-two-critiques.mov", onClick: "window.open('data/2010/highlights/tale-of-two-critiques.mov', 'movieWin', 'width=660,height=520,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Thank you, Prof. Wallace!", linkUrl: "data/2010/highlights/WallaceThankYou.mov", onClick: "window.open('data/2010/highlights/WallaceThankYou.mov', 'movieWin', 'width=660,height=400,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "2.009 on The Tech", linkUrl: "http://tech.mit.edu/V130/N59/project2.009.html" ],
                        [ linkLabel: "2.009 on MIT News", linkUrl: "http://web.mit.edu/newsoffice/2010/2-009-presentations-1208.html" ],
                ],
                highlightDividerIndexes: [1, 10],
                sketchMovWidth: 320,
                sketchMovHeight: 256,
                mockMovWidth: 320,
                mockMovHeight: 229,
                techMovWidth: 320,
                techMovHeight: 256,
                finalMovWidth: 640,
                finalMovHeight: 376,
                picWidth: 240, // picHeight is determined dynamically
                projects: [
                        [
                                projId: "happyEgg", // folder name
                                projName: "Happy Egg",
                                projDesc: "egg washing and drying machine",
                                projColor: "blue",
                                projTeam: "Alyse Cardell, Ari Miller, Brian Doyle, Christina Jaworsky, Conor O'Rourke, Ian Tracy, Lim Wannaphahoon, Michelle Nason, Nick Sisler, Romain Teil, Derek Ho, Derek Li, Grace Kane, Jacky Lau, Jessica Bainbridge-Smith, Keri Dixon, Mitch Kelley, Nicole Teague, Omar Abudayyeh, Orlando Saldivar",
                                projCode: "data/2010/homepage/codeOfEthics/codeOfEthics.html#blue",

                                ideasPic1: "data/2010/ideas/BlueA1.jpg",
                                ideasPic2: "data/2010/ideas/BlueA2.jpg",
                                ideasPic3: "data/2010/ideas/BlueA3.jpg",
                                ideasPic4: "data/2010/ideas/BlueB1.jpg",
                                ideasPic5: "data/2010/ideas/BlueB2.jpg",
                                ideasPic6: "data/2010/ideas/BlueB3.jpg",

                                sketchName1: "Souper Cooler",
                                sketchName2: "FreezeSafe",
                                sketchName3: "Happy Egg Washer",
                                sketchName4: "EasyLift Stretcher",
                                sketchPic1: "data/2010/sketch/photos/blueA1_1.JPG",
                                sketchPic2: "data/2010/sketch/photos/blueA1_2.JPG",
                                sketchPic3: "data/2010/sketch/photos/blueA2_1.JPG",
                                sketchPic4: "data/2010/sketch/photos/blueA2_2.JPG",
                                sketchPic5: "data/2010/sketch/photos/blueB1_1.JPG",
                                sketchPic6: "data/2010/sketch/photos/blueB1_2.JPG",
                                sketchPic7: "data/2010/sketch/photos/blueB2_1.JPG",
                                sketchPic8: "data/2010/sketch/photos/blueB2_2.JPG",
                                sketchMov1: "data/2010/sketch/movies/blueA1.mov",
                                sketchMov2: "data/2010/sketch/movies/blueA2.mov",
                                sketchMov3: "data/2010/sketch/movies/blueB1.mov",
                                sketchMov4: "data/2010/sketch/movies/blueB2.mov",
                                sketchSlide1: "data/2010/sketch/slides/blueA1.pdf",
                                sketchSlide2: "data/2010/sketch/slides/blueA2.pdf",
                                sketchSlide3: "data/2010/sketch/slides/blueB1.pdf",
                                sketchSlide4: "data/2010/sketch/slides/blueB2.pdf",

                                mockName1: "SouperCooler",
                                mockName2: "Happy Egg Washer",
                                mockPic1: "data/2010/mockup/photos/blueA1.JPG",
                                mockPic2: "data/2010/mockup/photos/blueA2.JPG",
                                mockPic3: "data/2010/mockup/photos/blueB1.JPG",
                                mockPic4: "data/2010/mockup/photos/blueB2.JPG",
                                mockMov1: "data/2010/mockup/movies/blueAs.mov",
                                mockMov2: "data/2010/mockup/movies/blueBs.mov",
                                mockSlide1: "data/2010/mockup/slides/blueA.pdf",
                                mockSlide2: "data/2010/mockup/slides/blueB.pdf",

                                assemblyPic1: "data/2010/assembly/blueAssembly.jpg",
                                assemblyContract1: "data/2010/assembly/blueContract.pdf",

                                techPic1: "data/2010/tech/photos/Blue1.JPG",
                                techPic2: "data/2010/tech/photos/Blue2.JPG",
                                techMov1: "data/2010/tech/movies/Blue.mov",
                                techContract1: "data/2010/tech/extras/blueContract.pdf",

                                finalPic1: "data/2010/final/photos/blue1.JPG",
                                finalPic2: "data/2010/final/photos/blue2.JPG",
                                finalMov1: "data/2010/final/movies/blue.mov",
                                finalSlide1: "data/2010/final/slides/blue.pdf",
                                finalBrochure1: "data/2010/final/extras/blueBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "trueTourne", // folder name
                                projName: "True Tourn&eacute;",
                                projDesc: "tourn&eacute; potato cutting device",
                                projColor: "yellow",
                                projTeam: "Dan Hyatt, Eliza Eddison, Jamie Curran, Jonathan Mendoza, Justin Myers, Katelyn Snyder, Pall Kornmayer, Phillip Gonzales, Sarah Lichtblau, Stewart Park, Adam Doroski, Garrett Winther, Hazel Briner, Kevin Kleinguetl, Lily Berger, Nick Leonard, Richard Mancco, Stuart Bermack, Wei Sun",
                                projCode: "data/2010/homepage/codeOfEthics/codeOfEthics.html#yellow",

                                ideasPic1: "data/2010/ideas/YellowA1.jpg",
                                ideasPic2: "data/2010/ideas/YellowA2.jpg",
                                ideasPic3: "data/2010/ideas/YellowA3.jpg",
                                ideasPic4: "data/2010/ideas/YellowB1.jpg",
                                ideasPic5: "data/2010/ideas/YellowB2.jpg",
                                ideasPic6: "data/2010/ideas/YellowB3.jpg",

                                sketchName1: "Press 'n' Test",
                                sketchName2: "The Individual Cookie Maker",
                                sketchName3: "Power Rack Oven",
                                sketchName4: "Easy Tourn&eacute;e",
                                sketchPic1: "data/2010/sketch/photos/yellowA1_1.JPG",
                                sketchPic2: "data/2010/sketch/photos/yellowA1_2.JPG",
                                sketchPic3: "data/2010/sketch/photos/yellowA2_1.JPG",
                                sketchPic4: "data/2010/sketch/photos/yellowA2_2.JPG",
                                sketchPic5: "data/2010/sketch/photos/yellowB1_1.JPG",
                                sketchPic6: "data/2010/sketch/photos/yellowB1_2.JPG",
                                sketchPic7: "data/2010/sketch/photos/yellowB2_1.JPG",
                                sketchPic8: "data/2010/sketch/photos/yellowB2_2.JPG",
                                sketchMov1: "data/2010/sketch/movies/yellowA1.mov",
                                sketchMov2: "data/2010/sketch/movies/yellowA2.mov",
                                sketchMov3: "data/2010/sketch/movies/yellowB1.mov",
                                sketchMov4: "data/2010/sketch/movies/yellowB2.mov",
                                sketchSlide1: "data/2010/sketch/slides/yellowA1.pdf",
                                sketchSlide2: "data/2010/sketch/slides/yellowA2.pdf",
                                sketchSlide3: "data/2010/sketch/slides/yellowB1.pdf",
                                sketchSlide4: "data/2010/sketch/slides/yellowB2.pdf",

                                mockName1: "The Press 'N' Test",
                                mockName2: "Easy Tourn&eacute;e",
                                mockPic1: "data/2010/mockup/photos/yellowA1.JPG",
                                mockPic2: "data/2010/mockup/photos/yellowA2.JPG",
                                mockPic3: "data/2010/mockup/photos/yellowB1.JPG",
                                mockPic4: "data/2010/mockup/photos/yellowB2.JPG",
                                mockMov1: "data/2010/mockup/movies/yellowAs.mov",
                                mockMov2: "data/2010/mockup/movies/yellowBs.mov",
                                mockSlide1: "data/2010/mockup/slides/yellowA.pdf",
                                mockSlide2: "data/2010/mockup/slides/yellowB.pdf",

                                assemblyPic1: "data/2010/assembly/yellowAssembly.jpg",
                                assemblyContract1: "data/2010/assembly/yellowContract.pdf",

                                techPic1: "data/2010/tech/photos/Yellow1.JPG",
                                techPic2: "data/2010/tech/photos/Yellow2.JPG",
                                techMov1: "data/2010/tech/movies/Yellow.mov",
                                techContract1: "data/2010/tech/extras/yellowContract.pdf",

                                finalPic1: "data/2010/final/photos/yellow1.JPG",
                                finalPic2: "data/2010/final/photos/yellow2.JPG",
                                finalMov1: "data/2010/final/movies/yellow.mov",
                                finalSlide1: "data/2010/final/slides/yellow.pdf",
                                finalBrochure1: "data/2010/final/extras/yellowBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "groceryMate", // folder name
                                projName: "Grocery Mate",
                                projDesc: "wheelchair tray and grocery basket",
                                projColor: "purple",
                                projTeam: "Benji Moncivaiz, Chris Ohlmacher, Emily Conn, Emily Suter, Juliana Velez, My Vu, Stephanie Schmit, Sun Kim, Ben Bersanti, Clark Davenport, Elli Pula, Meagan Roth, Naomi Zabel, Riley Brandt, Taylor Gilbert, Tiffany Jin",
                                projCode: "data/2010/homepage/codeOfEthics/codeOfEthics.html#purple",

                                ideasPic1: "data/2010/ideas/PurpleA1.jpg",
                                ideasPic2: "data/2010/ideas/PurpleA2.jpg",
                                ideasPic3: "data/2010/ideas/PurpleA3.jpg",
                                ideasPic4: "data/2010/ideas/PurpleB1.jpg",
                                ideasPic5: "data/2010/ideas/PurpleB2.jpg",
                                ideasPic6: "data/2010/ideas/PurpleB3.jpg",

                                sketchName1: "The Eye Pot",
                                sketchName2: "Lift-n-Lock Oven Rack",
                                sketchName3: "Grocery Mate",
                                sketchName4: "Cooking Board",
                                sketchPic1: "data/2010/sketch/photos/purpleA1_1.JPG",
                                sketchPic2: "data/2010/sketch/photos/purpleA1_2.JPG",
                                sketchPic3: "data/2010/sketch/photos/purpleA2_1.JPG",
                                sketchPic4: "data/2010/sketch/photos/purpleA2_2.JPG",
                                sketchPic5: "data/2010/sketch/photos/purpleB1_1.JPG",
                                sketchPic6: "data/2010/sketch/photos/purpleB1_2.JPG",
                                sketchPic7: "data/2010/sketch/photos/purpleB2_1.JPG",
                                sketchPic8: "data/2010/sketch/photos/purpleB2_2.JPG",
                                sketchMov1: "data/2010/sketch/movies/purpleA1.mov",
                                sketchMov2: "data/2010/sketch/movies/purpleA2.mov",
                                sketchMov3: "data/2010/sketch/movies/purpleB1.mov",
                                sketchMov4: "data/2010/sketch/movies/purpleB2.mov",
                                sketchSlide1: "data/2010/sketch/slides/purpleA1.pdf",
                                sketchSlide2: "data/2010/sketch/slides/purpleA2.pdf",
                                sketchSlide3: "data/2010/sketch/slides/purpleB1.pdf",
                                sketchSlide4: "data/2010/sketch/slides/purpleB2.pdf",

                                mockName1: "Lift-n-Lock",
                                mockName2: "Grocery Mate",
                                mockPic1: "data/2010/mockup/photos/purpleA1.JPG",
                                mockPic2: "data/2010/mockup/photos/purpleA2.JPG",
                                mockPic3: "data/2010/mockup/photos/purpleB1.JPG",
                                mockPic4: "data/2010/mockup/photos/purpleB2.JPG",
                                mockMov1: "data/2010/mockup/movies/purpleAs.mov",
                                mockMov2: "data/2010/mockup/movies/purpleBs.mov",
                                mockSlide1: "data/2010/mockup/slides/purpleA.pdf",
                                mockSlide2: "data/2010/mockup/slides/purpleB.pdf",

                                assemblyPic1: "data/2010/assembly/purpleAssembly.jpg",
                                assemblyContract1: "data/2010/assembly/purpleContract.pdf",

                                techPic1: "data/2010/tech/photos/Purple1.JPG",
                                techPic2: "data/2010/tech/photos/Purple2.JPG",
                                techMov1: "data/2010/tech/movies/Purple.mov",
                                techContract1: "data/2010/tech/extras/purpleContract.pdf",

                                finalPic1: "data/2010/final/photos/purple1.JPG",
                                finalPic2: "data/2010/final/photos/purple2.JPG",
                                finalMov1: "data/2010/final/movies/purple.mov",
                                finalSlide1: "data/2010/final/slides/purple.pdf",
                                finalBrochure1: "data/2010/final/extras/purpleBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "dash", // folder name
                                projName: "Dash",
                                projDesc: "spice mixer and dispenser",
                                projColor: "orange",
                                projTeam: "Amanda Grue, Amy Qian, Emily Shao, Evan Schneider, Ignacio del Pino, Justin Lan, Melody Kuna, Vrajesh Modi, Wayne Hollman, Wendi Zhang, Amber Houghstow, Anne Shen, Dan Fourie, Grant Kadokura, Jesse Thornburg, Karen Hart, Kevin Boehm, Michelle Burroughs, Mitch Westwood, Travis Tucker",
                                projCode: "data/2010/homepage/codeOfEthics/codeOfEthics.html#orange",

                                ideasPic1: "data/2010/ideas/OrangeA1.jpg",
                                ideasPic2: "data/2010/ideas/OrangeA2.jpg",
                                ideasPic3: "data/2010/ideas/OrangeA3.jpg",
                                ideasPic4: "data/2010/ideas/OrangeB1.jpg",
                                ideasPic5: "data/2010/ideas/OrangeB2.jpg",
                                ideasPic6: "data/2010/ideas/OrangeB3.jpg",

                                sketchName1: "Select-a-Bake",
                                sketchName2: "Easy Dish",
                                sketchName3: "Shape Shifter",
                                sketchName4: "Cup 'N Cake",
                                sketchPic1: "data/2010/sketch/photos/orangeA1_1.JPG",
                                sketchPic2: "data/2010/sketch/photos/orangeA1_2.JPG",
                                sketchPic3: "data/2010/sketch/photos/orangeA2_1.JPG",
                                sketchPic4: "data/2010/sketch/photos/orangeA2_2.JPG",
                                sketchPic5: "data/2010/sketch/photos/orangeB1_1.JPG",
                                sketchPic6: "data/2010/sketch/photos/orangeB1_2.JPG",
                                sketchPic7: "data/2010/sketch/photos/orangeB2_1.JPG",
                                sketchPic8: "data/2010/sketch/photos/orangeB2_2.JPG",
                                sketchMov1: "data/2010/sketch/movies/orangeA1.mov",
                                sketchMov2: "data/2010/sketch/movies/orangeA2.mov",
                                sketchMov3: "data/2010/sketch/movies/orangeB1.mov",
                                sketchMov4: "data/2010/sketch/movies/orangeB2.mov",
                                sketchSlide1: "data/2010/sketch/slides/orangeA1.pdf",
                                sketchSlide2: "data/2010/sketch/slides/orangeA2.pdf",
                                sketchSlide3: "data/2010/sketch/slides/orangeB1.pdf",
                                sketchSlide4: "data/2010/sketch/slides/orangeB2.pdf",

                                mockName1: "Select-a-Spice",
                                mockName2: "Cup 'N Cake",
                                mockPic1: "data/2010/mockup/photos/orangeA1.JPG",
                                mockPic2: "data/2010/mockup/photos/orangeA2.JPG",
                                mockPic3: "data/2010/mockup/photos/orangeB1.JPG",
                                mockPic4: "data/2010/mockup/photos/orangeB2.JPG",
                                mockMov1: "data/2010/mockup/movies/orangeAs.mov",
                                mockMov2: "data/2010/mockup/movies/orangeBs.mov",
                                mockSlide1: "data/2010/mockup/slides/orangeA.pdf",
                                mockSlide2: "data/2010/mockup/slides/orangeB.pdf",

                                assemblyPic1: "data/2010/assembly/orangeAssembly.jpg",
                                assemblyContract1: "data/2010/assembly/orangeContract.pdf",

                                techPic1: "data/2010/tech/photos/Orange1.JPG",
                                techPic2: "data/2010/tech/photos/Orange2.JPG",
                                techMov1: "data/2010/tech/movies/Orange.mov",
                                techContract1: "data/2010/tech/extras/orangeContract.pdf",

                                finalPic1: "data/2010/final/photos/orange1.JPG",
                                finalPic2: "data/2010/final/photos/orange2.JPG",
                                finalMov1: "data/2010/final/movies/orange.mov",
                                finalSlide1: "data/2010/final/slides/orange.pdf",
                                finalBrochure1: "data/2010/final/extras/orangeBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "noribo", // folder name
                                projName: "Noribo",
                                projDesc: "sushi deliverying robots",
                                projColor: "silver",
                                projTeam: "Christian Segura-Rivera, Eric Roselli, John Boghossian, Juan Rodriguez, Katy Olesnavage, Kevin Jenks, Lauren Hernley, Liane Fang, Rachel Lewis, Robert Long, Alyssa Roque, Arin Rogers, Charles Guan, Cody Daniel, Jen Rees, Katrina Schoen, Laura Schuhrke, Michael Snively, Yoshi Perez",
                                projCode: "data/2010/homepage/codeOfEthics/codeOfEthics.html#silver",

                                ideasPic1: "data/2010/ideas/SilverA1.jpg",
                                ideasPic2: "data/2010/ideas/SilverA2.jpg",
                                ideasPic3: "data/2010/ideas/SilverA3.jpg",
                                ideasPic4: "data/2010/ideas/SilverB1.jpg",
                                ideasPic5: "data/2010/ideas/SilverB2.jpg",
                                ideasPic6: "data/2010/ideas/SilverB3.jpg",

                                sketchName1: "Fryer Fuel",
                                sketchName2: "Tourn&eacute;e-Do",
                                sketchName3: "Wilbur Wake up",
                                sketchName4: "Coaster Bot",
                                sketchPic1: "data/2010/sketch/photos/silverA1_1.JPG",
                                sketchPic2: "data/2010/sketch/photos/silverA1_2.JPG",
                                sketchPic3: "data/2010/sketch/photos/silverA2_1.JPG",
                                sketchPic4: "data/2010/sketch/photos/silverA2_2.JPG",
                                sketchPic5: "data/2010/sketch/photos/silverB1_1.JPG",
                                sketchPic6: "data/2010/sketch/photos/silverB1_2.JPG",
                                sketchPic7: "data/2010/sketch/photos/silverB2_1.JPG",
                                sketchPic8: "data/2010/sketch/photos/silverB2_2.JPG",
                                sketchMov1: "data/2010/sketch/movies/silverA1.mov",
                                sketchMov2: "data/2010/sketch/movies/silverA2.mov",
                                sketchMov3: "data/2010/sketch/movies/silverB1.mov",
                                sketchMov4: "data/2010/sketch/movies/silverB2.mov",
                                sketchSlide1: "data/2010/sketch/slides/silverA1.pdf",
                                sketchSlide2: "data/2010/sketch/slides/silverA2.pdf",
                                sketchSlide3: "data/2010/sketch/slides/silverB1.pdf",
                                sketchSlide4: "data/2010/sketch/slides/silverB2.pdf",

                                mockName1: "Tourn&eacute;e-Do",
                                mockName2: "CoasterBot",
                                mockPic1: "data/2010/mockup/photos/silverA1.JPG",
                                mockPic2: "data/2010/mockup/photos/silverA2.JPG",
                                mockPic3: "data/2010/mockup/photos/silverB1.JPG",
                                mockPic4: "data/2010/mockup/photos/silverB2.JPG",
                                mockMov1: "data/2010/mockup/movies/silverAs.mov",
                                mockMov2: "data/2010/mockup/movies/silverBs.mov",
                                mockSlide1: "data/2010/mockup/slides/silverA.pdf",
                                mockSlide2: "data/2010/mockup/slides/silverB.pdf",

                                assemblyPic1: "data/2010/assembly/silverAssembly.jpg",
                                assemblyContract1: "data/2010/assembly/silverContract.pdf",

                                techPic1: "data/2010/tech/photos/Silver1.JPG",
                                techPic2: "data/2010/tech/photos/Silver2.JPG",
                                techMov1: "data/2010/tech/movies/Silver.mov",
                                techContract1: "data/2010/tech/extras/silverContract.pdf",

                                finalPic1: "data/2010/final/photos/silver1.JPG",
                                finalPic2: "data/2010/final/photos/silver2.JPG",
                                finalMov1: "data/2010/final/movies/silver.mov",
                                finalSlide1: "data/2010/final/slides/silver.pdf",
                                finalBrochure1: "data/2010/final/extras/silverBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "rensa", // folder name
                                projName: "Rensa",
                                projDesc: "water bottle washer and filler",
                                projColor: "green",
                                projTeam: "Allin Resposo, Benjamin Peters, Caroline Hane-Weijman, Jen Tran, Mike Cupelli, Paula Te, Saba Mohsin, Sam Hui, Vazrik Chiloyan, Will Vega-Brown, Annie Kwon, Ben  Judge, Caitlin Reyda, Eddie Grinnell, Grant Tomassi, Heather McDonald, Maddie Hickman, Patrick Jupe, Vibin Kundukulam, Yue Li",
                                projCode: "data/2010/homepage/codeOfEthics/codeOfEthics.html#green",

                                ideasPic1: "data/2010/ideas/GreenA1.jpg",
                                ideasPic2: "data/2010/ideas/GreenA2.jpg",
                                ideasPic3: "data/2010/ideas/GreenA3.jpg",
                                ideasPic4: "data/2010/ideas/GreenB1.jpg",
                                ideasPic5: "data/2010/ideas/GreenB2.jpg",
                                ideasPic6: "data/2010/ideas/GreenB3.jpg",

                                sketchName1: "Kineto-cup",
                                sketchName2: "Waste oil converter",
                                sketchName3: "Sustain-a-bottle",
                                sketchName4: "Veggie Washer",
                                sketchPic1: "data/2010/sketch/photos/greenA1_1.JPG",
                                sketchPic2: "data/2010/sketch/photos/greenA1_2.JPG",
                                sketchPic3: "data/2010/sketch/photos/greenA2_1.JPG",
                                sketchPic4: "data/2010/sketch/photos/greenA2_2.JPG",
                                sketchPic5: "data/2010/sketch/photos/greenB1_1.JPG",
                                sketchPic6: "data/2010/sketch/photos/greenB1_2.JPG",
                                sketchPic7: "data/2010/sketch/photos/greenB2_1.JPG",
                                sketchPic8: "data/2010/sketch/photos/greenB2_2.JPG",
                                sketchMov1: "data/2010/sketch/movies/greenA1.mov",
                                sketchMov2: "data/2010/sketch/movies/greenA2.mov",
                                sketchMov3: "data/2010/sketch/movies/greenB1.mov",
                                sketchMov4: "data/2010/sketch/movies/greenB2.mov",
                                sketchSlide1: "data/2010/sketch/slides/greenA1.pdf",
                                sketchSlide2: "data/2010/sketch/slides/greenA2.pdf",
                                sketchSlide3: "data/2010/sketch/slides/greenB1.pdf",
                                sketchSlide4: "data/2010/sketch/slides/greenB2.pdf",

                                mockName1: "Veggiefuel",
                                mockName2: "Green Canteen",
                                mockPic1: "data/2010/mockup/photos/greenA1.JPG",
                                mockPic2: "data/2010/mockup/photos/greenA2.JPG",
                                mockPic3: "data/2010/mockup/photos/greenB1.JPG",
                                mockPic4: "data/2010/mockup/photos/greenB2.JPG",
                                mockMov1: "data/2010/mockup/movies/greenAs.mov",
                                mockMov2: "data/2010/mockup/movies/greenBs.mov",
                                mockSlide1: "data/2010/mockup/slides/greenA.pdf",
                                mockSlide2: "data/2010/mockup/slides/greenB.pdf",

                                assemblyPic1: "data/2010/assembly/greenAssembly.jpg",
                                assemblyContract1: "data/2010/assembly/greenContract.pdf",

                                techPic1: "data/2010/tech/photos/Green1.JPG",
                                techPic2: "data/2010/tech/photos/Green2.JPG",
                                techMov1: "data/2010/tech/movies/Green.mov",
                                techContract1: "data/2010/tech/extras/greenContract.pdf",

                                finalPic1: "data/2010/final/photos/green1.JPG",
                                finalPic2: "data/2010/final/photos/green2.JPG",
                                finalMov1: "data/2010/final/movies/green.mov",
                                finalSlide1: "data/2010/final/slides/green.pdf",
                                finalBrochure1: "data/2010/final/extras/greenBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "gaia", // folder name
                                projName: "Gaia",
                                projDesc: "powdered milk dryer",
                                projColor: "red",
                                projTeam: "Andrea Blakemore, Brett van Zuiden, Carter Chang, Matthew Rodriguez, Michael Fraser, Moji Jimoh, Stephan Hawthorne, Tim Grejtak, Tommy Ciesielski, Chiedozie Okafor, Jasmine Florentine, Juan Valdez, Maia Bageant, Michael Dobson, Q Harris, Thi Tran, Travis Hery, Trevor Shannon",
                                projCode: "data/2010/homepage/codeOfEthics/codeOfEthics.html#red",

                                ideasPic1: "data/2010/ideas/RedA1.jpg",
                                ideasPic2: "data/2010/ideas/RedA2.jpg",
                                ideasPic3: "data/2010/ideas/RedA3.jpg",
                                ideasPic4: "data/2010/ideas/RedB1.jpg",
                                ideasPic5: "data/2010/ideas/RedB2.jpg",
                                ideasPic6: "data/2010/ideas/RedB3.jpg",

                                sketchName1: "Low-Cost Milk Dryer",
                                sketchName2: "Cake Transporter",
                                sketchName3: "Weed Extractor",
                                sketchName4: "Mechanically Powered UV Water Purifier",
                                sketchPic1: "data/2010/sketch/photos/redA1_1.JPG",
                                sketchPic2: "data/2010/sketch/photos/redA1_2.JPG",
                                sketchPic3: "data/2010/sketch/photos/redA2_1.JPG",
                                sketchPic4: "data/2010/sketch/photos/redA2_2.JPG",
                                sketchPic5: "data/2010/sketch/photos/redB1_1.JPG",
                                sketchPic6: "data/2010/sketch/photos/redB1_2.JPG",
                                sketchPic7: "data/2010/sketch/photos/redB2_1.JPG",
                                sketchPic8: "data/2010/sketch/photos/redB2_2.JPG",
                                sketchMov1: "data/2010/sketch/movies/redA1.mov",
                                sketchMov2: "data/2010/sketch/movies/redA2.mov",
                                sketchMov3: "data/2010/sketch/movies/redB1.mov",
                                sketchMov4: "data/2010/sketch/movies/redB2.mov",
                                sketchSlide1: "data/2010/sketch/slides/redA1.pdf",
                                sketchSlide2: "data/2010/sketch/slides/redA2.pdf",
                                sketchSlide3: "data/2010/sketch/slides/redB1.pdf",
                                sketchSlide4: "data/2010/sketch/slides/redB2.pdf",

                                mockName1: "Milk Saver",
                                mockName2: "Lightning Jug",
                                mockPic1: "data/2010/mockup/photos/redA1.JPG",
                                mockPic2: "data/2010/mockup/photos/redA2.JPG",
                                mockPic3: "data/2010/mockup/photos/redB1.JPG",
                                mockPic4: "data/2010/mockup/photos/redB2.JPG",
                                mockMov1: "data/2010/mockup/movies/redAs.mov",
                                mockMov2: "data/2010/mockup/movies/redBs.mov",
                                mockSlide1: "data/2010/mockup/slides/redA.pdf",
                                mockSlide2: "data/2010/mockup/slides/redB.pdf",

                                assemblyPic1: "data/2010/assembly/redAssembly.jpg",
                                assemblyContract1: "data/2010/assembly/redContract.pdf",

                                techPic1: "data/2010/tech/photos/Red1.JPG",
                                techPic2: "data/2010/tech/photos/Red2.JPG",
                                techMov1: "data/2010/tech/movies/Red.mov",
                                techContract1: "data/2010/tech/extras/redContract.pdf",

                                finalPic1: "data/2010/final/photos/red1.JPG",
                                finalPic2: "data/2010/final/photos/red2.JPG",
                                finalMov1: "data/2010/final/movies/red.mov",
                                finalSlide1: "data/2010/final/slides/red.pdf",
                                finalBrochure1: "data/2010/final/extras/redBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "spence", // folder name
                                projName: "Spence",
                                projDesc: "flour metering device",
                                projColor: "pink",
                                projTeam: "Ade Ogunniyi, Anna Haas, Ben Williams, Bonnie Blackburn, Dan Kubaczyk, Danielle Whited, Elvine Pineda, Julie Henion, Julie Hui, Omar Carrasquillo, Carmen Graves, Joanna Faulk, Jon Reimer, Josh Ramos, Kim Zalatan, Noah Caplan, Parhys Napier, Pete Lu, William Pickeral",
                                projCode: "data/2010/homepage/codeOfEthics/codeOfEthics.html#pink",

                                ideasPic1: "data/2010/ideas/PinkA1.jpg",
                                ideasPic2: "data/2010/ideas/PinkA2.jpg",
                                ideasPic3: "data/2010/ideas/PinkA3.jpg",
                                ideasPic4: "data/2010/ideas/PinkB1.jpg",
                                ideasPic5: "data/2010/ideas/PinkB2.jpg",
                                ideasPic6: "data/2010/ideas/PinkB3.jpg",

                                sketchName1: "Waste Wobbler",
                                sketchName2: "Baker's Blaster",
                                sketchName3: "Scrumptious Sketcher",
                                sketchName4: "Measure Monster",
                                sketchPic1: "data/2010/sketch/photos/pinkA1_1.JPG",
                                sketchPic2: "data/2010/sketch/photos/pinkA1_2.JPG",
                                sketchPic3: "data/2010/sketch/photos/pinkA2_1.JPG",
                                sketchPic4: "data/2010/sketch/photos/pinkA2_2.JPG",
                                sketchPic5: "data/2010/sketch/photos/pinkB1_1.JPG",
                                sketchPic6: "data/2010/sketch/photos/pinkB1_2.JPG",
                                sketchPic7: "data/2010/sketch/photos/pinkB2_1.JPG",
                                sketchPic8: "data/2010/sketch/photos/pinkB2_2.JPG",
                                sketchMov1: "data/2010/sketch/movies/pinkA1.mov",
                                sketchMov2: "data/2010/sketch/movies/pinkA2.mov",
                                sketchMov3: "data/2010/sketch/movies/pinkB1.mov",
                                sketchMov4: "data/2010/sketch/movies/pinkB2.mov",
                                sketchSlide1: "data/2010/sketch/slides/pinkA1.pdf",
                                sketchSlide2: "data/2010/sketch/slides/pinkA2.pdf",
                                sketchSlide3: "data/2010/sketch/slides/pinkB1.pdf",
                                sketchSlide4: "data/2010/sketch/slides/pinkB2.pdf",

                                mockName1: "Baker's Blaster",
                                mockName2: "Flour Pot",
                                mockPic1: "data/2010/mockup/photos/pinkA1.JPG",
                                mockPic2: "data/2010/mockup/photos/pinkA2.JPG",
                                mockPic3: "data/2010/mockup/photos/pinkB1.JPG",
                                mockPic4: "data/2010/mockup/photos/pinkB2.JPG",
                                mockMov1: "data/2010/mockup/movies/pinkAs.mov",
                                mockMov2: "data/2010/mockup/movies/pinkBs.mov",
                                mockSlide1: "data/2010/mockup/slides/pinkA.pdf",
                                mockSlide2: "data/2010/mockup/slides/pinkB.pdf",

                                assemblyPic1: "data/2010/assembly/pinkAssembly.jpg",
                                assemblyContract1: "data/2010/assembly/pinkContract.pdf",

                                techPic1: "data/2010/tech/photos/Pink1.JPG",
                                techPic2: "data/2010/tech/photos/Pink2.JPG",
                                techMov1: "data/2010/tech/movies/Pink.mov",
                                techContract1: "data/2010/tech/extras/pinkContract.pdf",

                                finalPic1: "data/2010/final/photos/pink1.JPG",
                                finalPic2: "data/2010/final/photos/pink2.JPG",
                                finalMov1: "data/2010/final/movies/pink.mov",
                                finalSlide1: "data/2010/final/slides/pink.pdf",
                                finalBrochure1: "data/2010/final/extras/pinkBrochure.pdf",
                                finalBrochure2: null,
                        ],
                ],
        ],
]