[
        "2011": [
                themeYear: "2011", // folder name
                themeName: "On-the-go",
                themeDesc: "Any viable, meaningful product idea related to 'on-the-go' is a potential candidate&mdash;transportation, mobility and assistive technology, computing, medical devices, food-related products, sports and recreation, play, and travel all might touch upon the theme.",
                highlights: [
                        [ linkLabel: "Home page and slide show", linkUrl: "data/2011/homepage/index.html" ],
                        [ linkLabel: "Student tribute", linkUrl: "data/2011/highlights/tributePublic_sm.mov", onClick: "window.open('data/2011/highlights/tributePublic_sm.mov', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Final presentation program", linkUrl: "data/2011/highlights/programme.pdf" ],
                        [ linkLabel: "Final presentation: 3-min compendium", linkUrl: "data/2011/highlights/3minWeb.mov", onClick: "window.open('data/2011/highlights/3minWeb.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Final presentation: full show", linkUrl: "data/2011/highlights/ShowForPublic.mov", onClick: "window.open('data/2011/highlights/ShowForPublic.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Angry Birds!", linkUrl: "data/2011/highlights/AngryBirds.mov", onClick: "window.open('data/2011/highlights/AngryBirds.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Orange team: How did they get there?", linkUrl: "data/2011/highlights/OrangeTeam.mov", onClick: "window.open('data/2011/highlights/OrangeTeam.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Project theme of 2011", linkUrl: "data/2011/homepage/project/projectTheme.html" ],
                        [ linkLabel: "Course Syllabus", linkUrl: "data/2011/highlights/syllabus.mov", onClick: "window.open('data/2011/highlights/syllabus.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Product teardown exercise", linkUrl: "data/2011/highlights/teardown.mov", onClick: "window.open('data/2011/highlights/teardown.mov', 'movieWin', 'width=720,height=480,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Bird Cannon", linkUrl: "data/2011/highlights/bird_cannon.mov", onClick: "window.open('data/2011/highlights/bird_cannon.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Thank you, Prof. Wallace!", linkUrl: "data/2011/highlights/WallaceThankYou.mov", onClick: "window.open('data/2011/highlights/WallaceThankYou.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "2.009 on The Tech", linkUrl: "http://tech.mit.edu/V131/N59/2.009.html" ],
                        [ linkLabel: "2.009 on The Boston Globe", linkUrl: "http://www.boston.com/news/local/massachusetts/articles/2011/12/31/mit_students_design_vending_machine_to_provide_bike_renters_with_helmets/?page=1" ],
                ],
                highlightDividerIndexes: [1, 11],
                sketchMovWidth: 320,
                sketchMovHeight: 195,
                mockMovWidth: 320,
                mockMovHeight: 195,
                techMovWidth: 320,
                techMovHeight: 195,
                finalMovWidth: 640,
                finalMovHeight: 376,
                picWidth: 240, // picHeight is determined dynamically
                projects: [
                        [
                                projId: "cobalt", // folder name
                                projName: "cobalt",
                                projDesc: "keyless bike lock",
                                projColor: "blue",
                                projTeam: "Brenna Hogan, Hank Peppe, Jeff Huang, Jenn Hammond, Ken Lopez, Pooja Shah, Eli Davis, Emily Tow, Jean Martin, Lisette Lopez, Marty Sweeney, Michael Bickers, Stephen Hendel",
                                projCode: "data/2011/homepage/codeOfEthics/codeOfEthics.html#blue",
                                
                                ideasPic1: "data/2011/ideas/BlueA1.jpg",
                                ideasPic2: "data/2011/ideas/BlueA2.jpg",
                                ideasPic3: "data/2011/ideas/BlueA3.jpg",
                                ideasPic4: "data/2011/ideas/BlueB1.jpg",
                                ideasPic5: "data/2011/ideas/BlueB2.jpg",
                                ideasPic6: "data/2011/ideas/BlueB3.jpg",

                                sketchName1: "Pick-A-Spot",
                                sketchName2: "Peanut Butter Jelly Time",
                                sketchName3: "SwiftSecure",
                                sketchName4: "Coffee-waker",
                                sketchPic1: "data/2011/sketch/photos/blueA1_1.jpg",
                                sketchPic2: "data/2011/sketch/photos/blueA1_2.jpg",
                                sketchPic3: "data/2011/sketch/photos/blueA2_1.jpg",
                                sketchPic4: "data/2011/sketch/photos/blueA2_2.jpg",
                                sketchPic5: "data/2011/sketch/photos/blueB1_1.jpg",
                                sketchPic6: "data/2011/sketch/photos/blueB1_2.jpg",
                                sketchPic7: "data/2011/sketch/photos/blueB2_1.jpg",
                                sketchPic8: "data/2011/sketch/photos/blueB2_2.jpg",
                                sketchMov1: "data/2011/sketch/movies/blueA1.mov",
                                sketchMov2: "data/2011/sketch/movies/blueA2.mov",
                                sketchMov3: "data/2011/sketch/movies/blueB1.mov",
                                sketchMov4: "data/2011/sketch/movies/blueB2.mov",
                                sketchSlide1: "data/2011/sketch/slides/blueA1.pdf",
                                sketchSlide2: "data/2011/sketch/slides/blueA2.pdf",
                                sketchSlide3: "data/2011/sketch/slides/blueB1.pdf",
                                sketchSlide4: "data/2011/sketch/slides/blueB2.pdf",

                                mockName1: "SwiftSecure",
                                mockName2: "Coffee-Waker",
                                mockPic1: "data/2011/mockup/photos/blueA1.jpg",
                                mockPic2: "data/2011/mockup/photos/blueA2.jpg",
                                mockPic3: "data/2011/mockup/photos/blueB1.jpg",
                                mockPic4: "data/2011/mockup/photos/blueB2.jpg",
                                mockMov1: "data/2011/mockup/movies/blueAs.mov",
                                mockMov2: "data/2011/mockup/movies/blueBs.mov",
                                mockSlide1: "data/2011/mockup/slides/blueA.pdf",
                                mockSlide2: "data/2011/mockup/slides/blueB.pdf",

                                assemblyPic1: "data/2011/assembly/blueAssembly.png",
                                assemblyContract1: "data/2011/assembly/blueContract.pdf",

                                techPic1: "data/2011/tech/photos/Blue1.jpg",
                                techPic2: "data/2011/tech/photos/Blue2.jpg",
                                techMov1: "data/2011/tech/movies/Blue.mov",
                                techContract1: "data/2011/tech/extras/blueContract.pdf",

                                finalPic1: "data/2011/final/photos/blue1.jpg",
                                finalPic2: "data/2011/final/photos/blue2.jpg",
                                finalMov1: "data/2011/final/movies/blue.mov",
                                finalSlide1: "data/2011/final/slides/blue.pdf",
                                finalBrochure1: "data/2011/final/extras/blueBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "freeRim", // folder name
                                projName: "FreeRim",
                                projDesc: "hands clean wheelchair",
                                projColor: "yellow",
                                projTeam: "Justin Kresz, Lauren Gust, Marcel Sanchez, Mike Thompson, Nate Fox, Sam Powers, Bryan Beller, Celeste Faaiuaso, David Zhu, Jake Wamala, Mukul Singh, Paula Countouris, Scott Sundvor",
                                projCode: "data/2011/homepage/codeOfEthics/codeOfEthics.html#orange",
                                
                                ideasPic1: "data/2011/ideas/YellowA1.jpg",
                                ideasPic2: "data/2011/ideas/YellowA2.jpg",
                                ideasPic3: "data/2011/ideas/YellowA3.jpg",
                                ideasPic4: "data/2011/ideas/YellowB1.jpg",
                                ideasPic5: "data/2011/ideas/YellowB2.jpg",
                                ideasPic6: "data/2011/ideas/YellowB3.jpg",

                                sketchName1: "Run Run Revolution",
                                sketchName2: "Brush 'N' Floss",
                                sketchName3: "All Weather Wheelies",
                                sketchName4: "Bike Right",
                                sketchPic1: "data/2011/sketch/photos/yellowA1_1.jpg",
                                sketchPic2: "data/2011/sketch/photos/yellowA1_2.jpg",
                                sketchPic3: "data/2011/sketch/photos/yellowA2_1.jpg",
                                sketchPic4: "data/2011/sketch/photos/yellowA2_2.jpg",
                                sketchPic5: "data/2011/sketch/photos/yellowB1_1.jpg",
                                sketchPic6: "data/2011/sketch/photos/yellowB1_2.jpg",
                                sketchPic7: "data/2011/sketch/photos/yellowB2_1.jpg",
                                sketchPic8: "data/2011/sketch/photos/yellowB2_2.jpg",
                                sketchMov1: "data/2011/sketch/movies/yellowA1.mov",
                                sketchMov2: "data/2011/sketch/movies/yellowA2.mov",
                                sketchMov3: "data/2011/sketch/movies/yellowB1.mov",
                                sketchMov4: "data/2011/sketch/movies/yellowB2.mov",
                                sketchSlide1: "data/2011/sketch/slides/yellowA1.pdf",
                                sketchSlide2: "data/2011/sketch/slides/yellowA2.pdf",
                                sketchSlide3: "data/2011/sketch/slides/yellowB1.pdf",
                                sketchSlide4: "data/2011/sketch/slides/yellowB2.pdf",

                                mockName1: "Brush N Floss",
                                mockName2: "Indego",
                                mockPic1: "data/2011/mockup/photos/yellowA1.jpg",
                                mockPic2: "data/2011/mockup/photos/yellowA2.jpg",
                                mockPic3: "data/2011/mockup/photos/yellowB1.jpg",
                                mockPic4: "data/2011/mockup/photos/yellowB2.jpg",
                                mockMov1: "data/2011/mockup/movies/yellowAs.mov",
                                mockMov2: "data/2011/mockup/movies/yellowBs.mov",
                                mockSlide1: "data/2011/mockup/slides/yellowA.pdf",
                                mockSlide2: "data/2011/mockup/slides/yellowB.pdf",

                                assemblyPic1: "data/2011/assembly/yellowAssembly.jpg",
                                assemblyContract1: "data/2011/assembly/yellowContract.pdf",

                                techPic1: "data/2011/tech/photos/Yellow1.jpg",
                                techPic2: "data/2011/tech/photos/Yellow2.jpg",
                                techMov1: "data/2011/tech/movies/Yellow.mov",
                                techContract1: "data/2011/tech/extras/yellowContract.pdf",

                                finalPic1: "data/2011/final/photos/yellow1.jpg",
                                finalPic2: "data/2011/final/photos/yellow2.jpg",
                                finalMov1: "data/2011/final/movies/yellow.mov",
                                finalSlide1: "data/2011/final/slides/yellow.pdf",
                                finalBrochure1: "data/2011/final/extras/yellowBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [

                                projId: "ascent", // folder name
                                projName: "Ascent",
                                projDesc: "power-assist wheelchair",
                                projColor: "purple",
                                projTeam: "Ade Esho, Becky Vasquez, Erons Ohienmhen, Martin Lozano, Victoria Hammett, Craig Broady, James Silva, Marcel Thomas, Michael Lo, Paul Weaver, Tom Martins",
                                projCode: "data/2011/homepage/codeOfEthics/codeOfEthics.html#purple",
                                
                                ideasPic1: "data/2011/ideas/PurpleA1.jpg",
                                ideasPic2: "data/2011/ideas/PurpleA2.jpg",
                                ideasPic3: "data/2011/ideas/PurpleA3.jpg",
                                ideasPic4: "data/2011/ideas/PurpleB1.jpg",
                                ideasPic5: "data/2011/ideas/PurpleB2.jpg",
                                ideasPic6: "data/2011/ideas/PurpleB3.jpg",

                                sketchName1: "Forget-Me-Not",
                                sketchName2: "On-the-Clock",
                                sketchName3: "Chair Force One",
                                sketchName4: "Porta-Plotter",
                                sketchPic1: "data/2011/sketch/photos/purpleA1_1.jpg",
                                sketchPic2: "data/2011/sketch/photos/purpleA1_2.jpg",
                                sketchPic3: "data/2011/sketch/photos/purpleA2_1.jpg",
                                sketchPic4: "data/2011/sketch/photos/purpleA2_2.jpg",
                                sketchPic5: "data/2011/sketch/photos/purpleB1_1.jpg",
                                sketchPic6: "data/2011/sketch/photos/purpleB1_2.jpg",
                                sketchPic7: "data/2011/sketch/photos/purpleB2_1.jpg",
                                sketchPic8: "data/2011/sketch/photos/purpleB2_2.jpg",
                                sketchMov1: "data/2011/sketch/movies/purpleA1.mov",
                                sketchMov2: "data/2011/sketch/movies/purpleA2.mov",
                                sketchMov3: "data/2011/sketch/movies/purpleB1.mov",
                                sketchMov4: "data/2011/sketch/movies/purpleB2.mov",
                                sketchSlide1: "data/2011/sketch/slides/purpleA1.pdf",
                                sketchSlide2: "data/2011/sketch/slides/purpleA2.pdf",
                                sketchSlide3: "data/2011/sketch/slides/purpleB1.pdf",
                                sketchSlide4: "data/2011/sketch/slides/purpleB2.pdf",

                                mockName1: "Forget-Me-Not",
                                mockName2: "Chair Force One",
                                mockPic1: "data/2011/mockup/photos/purpleA1.jpg",
                                mockPic2: "data/2011/mockup/photos/purpleA2.jpg",
                                mockPic3: "data/2011/mockup/photos/purpleB1.jpg",
                                mockPic4: "data/2011/mockup/photos/purpleB2.jpg",
                                mockMov1: "data/2011/mockup/movies/purpleAs.mov",
                                mockMov2: "data/2011/mockup/movies/purpleBs.mov",
                                mockSlide1: "data/2011/mockup/slides/purpleA.pdf",
                                mockSlide2: "data/2011/mockup/slides/purpleB.pdf",

                                assemblyPic1: "data/2011/assembly/purpleAssembly.png",
                                assemblyContract1: "data/2011/assembly/purpleContract.pdf",

                                techPic1: "data/2011/tech/photos/Purple1.jpg",
                                techPic2: "data/2011/tech/photos/Purple2.jpg",
                                techMov1: "data/2011/tech/movies/Purple.mov",
                                techContract1: "data/2011/tech/extras/purpleContract.pdf",

                                finalPic1: "data/2011/final/photos/purple1.jpg",
                                finalPic2: "data/2011/final/photos/purple2.jpg",
                                finalMov1: "data/2011/final/movies/purple.mov",
                                finalSlide1: "data/2011/final/slides/purple.pdf",
                                finalBrochure1: "data/2011/final/extras/purpleBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [

                                projId: "phil", // folder name
                                projName: "Phil",
                                projDesc: "automatic sink filler",
                                projColor: "orange",
                                projTeam: "Brent Boswell, Bryan Macomber, Cat Thu Nguyen Huu, Danny Guillen, Jared Darby, Kami Klauber, Richard Dahan, Bennett Wilson, Charlie Klene, David Parell, Jess Iacobucci, Nick Dou, Nydia Ruleman",
                                projCode: "data/2011/homepage/codeOfEthics/codeOfEthics.html#orange",

                                ideasPic1: "data/2011/ideas/OrangeA1.jpg",
                                ideasPic2: "data/2011/ideas/OrangeA2.jpg",
                                ideasPic3: "data/2011/ideas/OrangeA3.jpg",
                                ideasPic4: "data/2011/ideas/OrangeB1.jpg",
                                ideasPic5: "data/2011/ideas/OrangeB2.jpg",
                                ideasPic6: "data/2011/ideas/OrangeB3.jpg",

                                sketchName1: "four leaf",
                                sketchName2: "Mobile Meds",
                                sketchName3: "Ultra Clean",
                                sketchName4: "Phil",
                                sketchPic1: "data/2011/sketch/photos/orangeA1_1.jpg",
                                sketchPic2: "data/2011/sketch/photos/orangeA1_2.jpg",
                                sketchPic3: "data/2011/sketch/photos/orangeA2_1.jpg",
                                sketchPic4: "data/2011/sketch/photos/orangeA2_2.jpg",
                                sketchPic5: "data/2011/sketch/photos/orangeB1_1.jpg",
                                sketchPic6: "data/2011/sketch/photos/orangeB1_2.jpg",
                                sketchPic7: "data/2011/sketch/photos/orangeB2_1.jpg",
                                sketchPic8: "data/2011/sketch/photos/orangeB2_2.jpg",
                                sketchMov1: "data/2011/sketch/movies/orangeA1.mov",
                                sketchMov2: "data/2011/sketch/movies/orangeA2.mov",
                                sketchMov3: "data/2011/sketch/movies/orangeB1.mov",
                                sketchMov4: "data/2011/sketch/movies/orangeB2.mov",
                                sketchSlide1: "data/2011/sketch/slides/orangeA1.pdf",
                                sketchSlide2: "data/2011/sketch/slides/orangeA2.pdf",
                                sketchSlide3: "data/2011/sketch/slides/orangeB1.pdf",
                                sketchSlide4: "data/2011/sketch/slides/orangeB2.pdf",

                                mockName1: "Phil",
                                mockName2: "four leaf",
                                mockPic1: "data/2011/mockup/photos/orangeA1.jpg",
                                mockPic2: "data/2011/mockup/photos/orangeA2.jpg",
                                mockPic3: "data/2011/mockup/photos/orangeB1.jpg",
                                mockPic4: "data/2011/mockup/photos/orangeB2.jpg",
                                mockMov1: "data/2011/mockup/movies/orangeAs.mov",
                                mockMov2: "data/2011/mockup/movies/orangeBs.mov",
                                mockSlide1: "data/2011/mockup/slides/orangeA.pdf",
                                mockSlide2: "data/2011/mockup/slides/orangeB.pdf",

                                assemblyPic1: "data/2011/assembly/orangeAssembly.png",
                                assemblyContract1: "data/2011/assembly/orangeContract.pdf",

                                techPic1: "data/2011/tech/photos/Orange1.jpg",
                                techPic2: "data/2011/tech/photos/Orange2.jpg",
                                techMov1: "data/2011/tech/movies/Orange.mov",
                                techContract1: "data/2011/tech/extras/orangeContract.pdf",

                                finalPic1: "data/2011/final/photos/orange1.jpg",
                                finalPic2: "data/2011/final/photos/orange2.jpg",
                                finalMov1: "data/2011/final/movies/orange.mov",
                                finalSlide1: "data/2011/final/slides/orange.pdf",
                                finalBrochure1: "data/2011/final/extras/orangeBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [

                                projId: "exhale", // folder name
                                projName: "Exhale",
                                projDesc: "vacuum-compress suitcase",
                                projColor: "silver",
                                projTeam: "Chao He, Joe Conte, Katharine Luginbuhl, Max St. John, Sarah Simon, Amanda Turk, E.J. Hester, Krishna Gupta, Kuan Cheng, Michael Fowler, Reuben Aronson",
                                projCode: "data/2011/homepage/codeOfEthics/codeOfEthics.html#silver",

                                ideasPic1: "data/2011/ideas/SilverA1.jpg",
                                ideasPic2: "data/2011/ideas/SilverA2.jpg",
                                ideasPic3: "data/2011/ideas/SilverA3.jpg",
                                ideasPic4: "data/2011/ideas/SilverB1.jpg",
                                ideasPic5: "data/2011/ideas/SilverB2.jpg",
                                ideasPic6: "data/2011/ideas/SilverB3.jpg",

                                sketchName1: "Pedal-Power",
                                sketchName2: "TranSit",
                                sketchName3: "Go-Bar Snack Bar Maker",
                                sketchName4: "CompactaBag",
                                sketchPic1: "data/2011/sketch/photos/silverA1_1.jpg",
                                sketchPic2: "data/2011/sketch/photos/silverA1_2.jpg",
                                sketchPic3: "data/2011/sketch/photos/silverA2_1.jpg",
                                sketchPic4: "data/2011/sketch/photos/silverA2_2.jpg",
                                sketchPic5: "data/2011/sketch/photos/silverB1_1.jpg",
                                sketchPic6: "data/2011/sketch/photos/silverB1_2.jpg",
                                sketchPic7: "data/2011/sketch/photos/silverB2_1.jpg",
                                sketchPic8: "data/2011/sketch/photos/silverB2_2.jpg",
                                sketchMov1: "data/2011/sketch/movies/silverA1.mov",
                                sketchMov2: "data/2011/sketch/movies/silverA2.mov",
                                sketchMov3: "data/2011/sketch/movies/silverB1.mov",
                                sketchMov4: "data/2011/sketch/movies/silverB2.mov",
                                sketchSlide1: "data/2011/sketch/slides/silverA1.pdf",
                                sketchSlide2: "data/2011/sketch/slides/silverA2.pdf",
                                sketchSlide3: "data/2011/sketch/slides/silverB1.pdf",
                                sketchSlide4: "data/2011/sketch/slides/silverB2.pdf",

                                mockName1: "TranSit",
                                mockName2: "CompactaBag",
                                mockPic1: "data/2011/mockup/photos/silverA1.jpg",
                                mockPic2: "data/2011/mockup/photos/silverA2.jpg",
                                mockPic3: "data/2011/mockup/photos/silverB1.jpg",
                                mockPic4: "data/2011/mockup/photos/silverB2.jpg",
                                mockMov1: "data/2011/mockup/movies/silverAs.mov",
                                mockMov2: "data/2011/mockup/movies/silverBs.mov",
                                mockSlide1: "data/2011/mockup/slides/silverA.pdf",
                                mockSlide2: "data/2011/mockup/slides/silverB.pdf",

                                assemblyPic1: "data/2011/assembly/silverAssembly.png",
                                assemblyContract1: "data/2011/assembly/silverContract.pdf",

                                techPic1: "data/2011/tech/photos/Silver1.jpg",
                                techPic2: "data/2011/tech/photos/Silver2.jpg",
                                techMov1: "data/2011/tech/movies/Silver.mov",
                                techContract1: "data/2011/tech/extras/silverContract.pdf",

                                finalPic1: "data/2011/final/photos/silver1.jpg",
                                finalPic2: "data/2011/final/photos/silver2.jpg",
                                finalMov1: "data/2011/final/movies/silver.mov",
                                finalSlide1: "data/2011/final/slides/silver.pdf",
                                finalBrochure1: "data/2011/final/extras/silverBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "walkerPrime", // folder name
                                projName: "Walker Prime",
                                projDesc: "folding walker and cane",
                                projColor: "green",
                                projTeam: "Annie Huang, Dan Kelly, Jessy Mwarage, Kristin Kagetsu, Ragheb El Khaja, Rand Hidaya, Brendan Rios, Elaina Present, Jonn-Ross Andrews, Li Wu, Mike Nawrot, Rodrigo",
                                projCode: "data/2011/homepage/codeOfEthics/codeOfEthics.html#green",
                                
                                ideasPic1: "data/2011/ideas/GreenA1.jpg",
                                ideasPic2: "data/2011/ideas/GreenA2.jpg",
                                ideasPic3: "data/2011/ideas/GreenA3.jpg",
                                ideasPic4: "data/2011/ideas/GreenB1.jpg",
                                ideasPic5: "data/2011/ideas/GreenB2.jpg",
                                ideasPic6: "data/2011/ideas/GreenB3.jpg",

                                sketchName1: "Bike Wheel Display",
                                sketchName2: "Scuiter",
                                sketchName3: "Backpack Bicycle",
                                sketchName4: "Collapsible Walker",
                                sketchPic1: "data/2011/sketch/photos/greenA1_1.jpg",
                                sketchPic2: "data/2011/sketch/photos/greenA1_2.jpg",
                                sketchPic3: "data/2011/sketch/photos/greenA2_1.jpg",
                                sketchPic4: "data/2011/sketch/photos/greenA2_2.jpg",
                                sketchPic5: "data/2011/sketch/photos/greenB1_1.jpg",
                                sketchPic6: "data/2011/sketch/photos/greenB1_2.jpg",
                                sketchPic7: "data/2011/sketch/photos/greenB2_1.jpg",
                                sketchPic8: "data/2011/sketch/photos/greenB2_2.jpg",
                                sketchMov1: "data/2011/sketch/movies/greenA1.mov",
                                sketchMov2: "data/2011/sketch/movies/greenA2.mov",
                                sketchMov3: "data/2011/sketch/movies/greenB1.mov",
                                sketchMov4: "data/2011/sketch/movies/greenB2.mov",
                                sketchSlide1: "data/2011/sketch/slides/greenA1.pdf",
                                sketchSlide2: "data/2011/sketch/slides/greenA2.pdf",
                                sketchSlide3: "data/2011/sketch/slides/greenB1.pdf",
                                sketchSlide4: "data/2011/sketch/slides/greenB2.pdf",

                                mockName1: "Scuiter",
                                mockName2: "CompactiWalker",
                                mockPic1: "data/2011/mockup/photos/greenA1.jpg",
                                mockPic2: "data/2011/mockup/photos/greenA2.jpg",
                                mockPic3: "data/2011/mockup/photos/greenB1.jpg",
                                mockPic4: "data/2011/mockup/photos/greenB2.jpg",
                                mockMov1: "data/2011/mockup/movies/greenAs.mov",
                                mockMov2: "data/2011/mockup/movies/greenBs.mov",
                                mockSlide1: "data/2011/mockup/slides/greenA.pdf",
                                mockSlide2: "data/2011/mockup/slides/greenB.pdf",

                                assemblyPic1: "data/2011/assembly/greenAssembly.jpg",
                                assemblyContract1: "data/2011/assembly/greenContract.pdf",

                                techPic1: "data/2011/tech/photos/Green1.jpg",
                                techPic2: "data/2011/tech/photos/Green2.jpg",
                                techMov1: "data/2011/tech/movies/Green.mov",
                                techContract1: "data/2011/tech/extras/greenContract.pdf",

                                finalPic1: "data/2011/final/photos/green1.jpg",
                                finalPic2: "data/2011/final/photos/green2.jpg",
                                finalMov1: "data/2011/final/movies/green.mov",
                                finalSlide1: "data/2011/final/slides/green.pdf",
                                finalBrochure1: "data/2011/final/extras/greenBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [

                                projId: "thermAssist", // folder name
                                projName: "ThermAssist",
                                projDesc: "temperature control wheelchair",
                                projColor: "red",
                                projTeam: "Alban Cobi, Ana Escalante, Chris Vaughan, Jordan Burgess, Marie McGraw, Sandra Chen, Ben Harvatine, Deniz Sevinc, Esteban McKenzie, Laura Shumaker, Nigel Kojimoto, Tania Morimoto, Victor Nevarez",
                                projCode: "data/2011/homepage/codeOfEthics/codeOfEthics.html#red",

                                ideasPic1: "data/2011/ideas/RedA1.jpg",
                                ideasPic2: "data/2011/ideas/RedA2.jpg",
                                ideasPic3: "data/2011/ideas/RedA3.jpg",
                                ideasPic4: "data/2011/ideas/RedB1.jpg",
                                ideasPic5: "data/2011/ideas/RedB2.jpg",
                                ideasPic6: "data/2011/ideas/RedB3.jpg",

                                sketchName1: "Covered Bike Tree",
                                sketchName2: "Idea Table",
                                sketchName3: "Homey-Gami Shelter",
                                sketchName4: "Wheelchair Thermal System",
                                sketchPic1: "data/2011/sketch/photos/redA1_1.jpg",
                                sketchPic2: "data/2011/sketch/photos/redA1_2.jpg",
                                sketchPic3: "data/2011/sketch/photos/redA2_1.jpg",
                                sketchPic4: "data/2011/sketch/photos/redA2_2.jpg",
                                sketchPic5: "data/2011/sketch/photos/redB1_1.jpg",
                                sketchPic6: "data/2011/sketch/photos/redB1_2.jpg",
                                sketchPic7: "data/2011/sketch/photos/redB2_1.jpg",
                                sketchPic8: "data/2011/sketch/photos/redB2_2.jpg",
                                sketchMov1: "data/2011/sketch/movies/redA1.mov",
                                sketchMov2: "data/2011/sketch/movies/redA2.mov",
                                sketchMov3: "data/2011/sketch/movies/redB1.mov",
                                sketchMov4: "data/2011/sketch/movies/redB2.mov",
                                sketchSlide1: "data/2011/sketch/slides/redA1.pdf",
                                sketchSlide2: "data/2011/sketch/slides/redA2.pdf",
                                sketchSlide3: "data/2011/sketch/slides/redB1.pdf",
                                sketchSlide4: "data/2011/sketch/slides/redB2.pdf",

                                mockName1: "Obelisk",
                                mockName2: "ThermAssist",
                                mockPic1: "data/2011/mockup/photos/redA1.jpg",
                                mockPic2: "data/2011/mockup/photos/redA2.jpg",
                                mockPic3: "data/2011/mockup/photos/redB1.jpg",
                                mockPic4: "data/2011/mockup/photos/redB2.jpg",
                                mockMov1: "data/2011/mockup/movies/redAs.mov",
                                mockMov2: "data/2011/mockup/movies/redBs.mov",
                                mockSlide1: "data/2011/mockup/slides/redA.pdf",
                                mockSlide2: "data/2011/mockup/slides/redB.pdf",

                                assemblyPic1: "data/2011/assembly/redAssembly.png",
                                assemblyContract1: "data/2011/assembly/redContract.pdf",

                                techPic1: "data/2011/tech/photos/Red1.jpg",
                                techPic2: "data/2011/tech/photos/Red2.jpg",
                                techMov1: "data/2011/tech/movies/Red.mov",
                                techContract1: "data/2011/tech/extras/redContract.pdf",

                                finalPic1: "data/2011/final/photos/red1.jpg",
                                finalPic2: "data/2011/final/photos/red2.jpg",
                                finalMov1: "data/2011/final/movies/red.mov",
                                finalSlide1: "data/2011/final/slides/red.pdf",
                                finalBrochure1: "data/2011/final/extras/redBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "helmetHub", // folder name
                                projName: "HelmetHub",
                                projDesc: "helmet vending machine",
                                projColor: "pink",
                                projTeam: "Breanna Berry, Chris Mills, Iggy Chen, Laura Ware, Ron Perez, Arni Lehto, Dani Hicks, Jessica Artiles, Jose Avedillo, Katie Barnes, Shen Huang, Stephanie Whalen",
                                projCode: "data/2011/homepage/codeOfEthics/codeOfEthics.html#pink",

                                ideasPic1: "data/2011/ideas/PinkA1.jpg",
                                ideasPic2: "data/2011/ideas/PinkA2.jpg",
                                ideasPic3: "data/2011/ideas/PinkA3.jpg",
                                ideasPic4: "data/2011/ideas/PinkB1.jpg",
                                ideasPic5: "data/2011/ideas/PinkB2.jpg",
                                ideasPic6: "data/2011/ideas/PinkB3.jpg",

                                sketchName1: "charette",
                                sketchName2: "modulaire",
                                sketchName3: "spring case",
                                sketchName4: "helmet hub",
                                sketchPic1: "data/2011/sketch/photos/pinkA1_1.jpg",
                                sketchPic2: "data/2011/sketch/photos/pinkA1_2.jpg",
                                sketchPic3: "data/2011/sketch/photos/pinkA2_1.jpg",
                                sketchPic4: "data/2011/sketch/photos/pinkA2_2.jpg",
                                sketchPic5: "data/2011/sketch/photos/pinkB1_1.jpg",
                                sketchPic6: "data/2011/sketch/photos/pinkB1_2.jpg",
                                sketchPic7: "data/2011/sketch/photos/pinkB2_1.jpg",
                                sketchPic8: "data/2011/sketch/photos/pinkB2_2.jpg",
                                sketchMov1: "data/2011/sketch/movies/pinkA1.mov",
                                sketchMov2: "data/2011/sketch/movies/pinkA2.mov",
                                sketchMov3: "data/2011/sketch/movies/pinkB1.mov",
                                sketchMov4: "data/2011/sketch/movies/pinkB2.mov",
                                sketchSlide1: "data/2011/sketch/slides/pinkA1.pdf",
                                sketchSlide2: "data/2011/sketch/slides/pinkA2.pdf",
                                sketchSlide3: "data/2011/sketch/slides/pinkB1.pdf",
                                sketchSlide4: "data/2011/sketch/slides/pinkB2.pdf",

                                mockName1: "ModulAir",
                                mockName2: "Helmet Hub",
                                mockPic1: "data/2011/mockup/photos/pinkA1.jpg",
                                mockPic2: "data/2011/mockup/photos/pinkA2.jpg",
                                mockPic3: "data/2011/mockup/photos/pinkB1.jpg",
                                mockPic4: "data/2011/mockup/photos/pinkB2.jpg",
                                mockMov1: "data/2011/mockup/movies/pinkAs.mov",
                                mockMov2: "data/2011/mockup/movies/pinkBs.mov",
                                mockSlide1: "data/2011/mockup/slides/pinkA.pdf",
                                mockSlide2: "data/2011/mockup/slides/pinkB.pdf",

                                assemblyPic1: "data/2011/assembly/pinkAssembly.jpg",
                                assemblyContract1: "data/2011/assembly/pinkContract.pdf",

                                techPic1: "data/2011/tech/photos/Pink1.jpg",
                                techPic2: "data/2011/tech/photos/Pink2.jpg",
                                techMov1: "data/2011/tech/movies/Pink.mov",
                                techContract1: "data/2011/tech/extras/pinkContract.pdf",

                                finalPic1: "data/2011/final/photos/pink1.jpg",
                                finalPic2: "data/2011/final/photos/pink2.jpg",
                                finalMov1: "data/2011/final/movies/pink.mov",
                                finalSlide1: "data/2011/final/slides/pink.pdf",
                                finalBrochure1: "data/2011/final/extras/pinkBrochure.pdf",
                                finalBrochure2: null,
                        ],
                ],
        ],
]