[
        "2004": [
                themeYear: "2004", // folder name
                themeName: "Energy",
                themeDesc: "Any products related to alternative energy, energy conservation, and products that use cleaner energy.",
                highlights: [
                        [ linkLabel: "Home page and slide show", linkUrl: "data/2004/homepage/index.html" ],
                        [ linkLabel: "Older projects in 2000-2002", linkUrl: "http://web.mit.edu/2.009_gallery/www/gallery/" ],
                ],

                highlightDividerIndexes: [ -1 ],
                sketchMovWidth: 320,
                sketchMovHeight: 255,
                mockMovWidth: 320,
                mockMovHeight: 255,
                techMovWidth: 320,
                techMovHeight: 255,
                finalMovWidth: 320,
                finalMovHeight: 255,
                picWidth: 135, // picHeight is determined dynamically
                projects: [
                        [
                                projId: "Charcoal-extruder", // folder name
                                projName: "Charcoal extruder",
                                projDesc: "an environmentally friendly charcoal maker",
                                projColor: "blue",
                                projTeam: "Kevin Chen, Dexter Ang, Danny Hilton, Derik Thomann, Greg Fonder, Andres Pino, John Brewer, Matthew Krueger, Ben Su, Panasaya Charenkavanich, Sheila Longo, Shira Lee, Way Luu, Lynn Kamimoto, Andres Ramirez, Orlando Soto",
                                projCode: "data/2004/homepage/codeOfEthics/blueEthics.html",

                                ideasPic1: "data/2004/ideas/BlueA1.gif",
                                ideasPic2: "data/2004/ideas/BlueA2.gif",
                                ideasPic3: "data/2004/ideas/BlueA3.gif",
                                ideasPic4: "data/2004/ideas/BlueB1.gif",
                                ideasPic5: "data/2004/ideas/BlueB2.gif",
                                ideasPic6: "data/2004/ideas/BlueB3.gif",
                                
                                sketchName1: "Screw extruder",
                                sketchName2: "Piston extruder",
                                sketchName3: "Lever press",
                                sketchName4: "Ratchet press",
                                sketchPic1: "data/2006/sketch/photos/blueA1_1.jpg",
                                sketchPic2: "data/2006/sketch/photos/blueA1_2.jpg",
                                sketchPic3: "data/2006/sketch/photos/blueA2_1.jpg",
                                sketchPic4: "data/2006/sketch/photos/blueA2_2.jpg",
                                sketchPic5: "data/2006/sketch/photos/blueB1_1.jpg",
                                sketchPic6: "data/2006/sketch/photos/blueB1_2.jpg",
                                sketchPic7: "data/2006/sketch/photos/blueB2_1.jpg",
                                sketchPic8: "data/2006/sketch/photos/blueB2_2.jpg",
                                sketchMov1: "data/2004/sketch/movies/blueA1.mov",
                                sketchMov2: "data/2004/sketch/movies/blueA2.mov",
                                sketchMov3: "data/2004/sketch/movies/blueB1.mov",
                                sketchMov4: "data/2004/sketch/movies/blueB2.mov",
                                sketchSlide1: "data/2004/sketch/slides/blueA1.pdf",
                                sketchSlide2: "data/2004/sketch/slides/blueA2.pdf",
                                sketchSlide3: "data/2004/sketch/slides/blueB1.pdf",
                                sketchSlide4: "data/2004/sketch/slides/blueB2.pdf",

                                mockName1: "Briquette extruder",
                                mockName2: "Sugar Brick",
                                mockPic1: "data/2004/mockup/photos/blueA1.gif",
                                mockPic2: "data/2004/mockup/photos/blueA2.gif",
                                mockPic3: "data/2004/mockup/photos/blueB1.gif",
                                mockPic4: "data/2004/mockup/photos/blueB2.gif",
                                mockMov1: "data/2004/mockup/movies/blueA.mov",
                                mockMov2: "data/2004/mockup/movies/blueB.mov",
                                mockSlide1: "data/2004/mockup/slides/blueA.pdf",
                                mockSlide2: "data/2004/mockup/slides/blueB.pdf",

                                assemblyPic1: "data/2004/assembly/blue1.gif",
                                assemblyContract1: "data/2004/assembly/blueContract.pdf",

                                techPic1: "data/2004/tech/photos/blue1.gif",
                                techPic2: "data/2004/tech/photos/blue2.gif",
                                techMov1: "data/2004/tech/movies/blue.mov",
                                techContract1: null,

                                finalPic1: "data/2004/final/photos/blue1.gif",
                                finalPic2: "data/2004/final/photos/blue2.gif",
                                finalMov1: "data/2004/final/movies/blue.mov",
                                finalSlide1: "data/2004/final/slides/blue.pdf",
                                finalBrochure1: "data/2004/final/extras/blueBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Kinkajuice", // folder name
                                projName: "Kinkajuice",
                                projDesc: "a human powered charger",
                                projColor: "yellow",
                                projTeam: "Christine Lin, Etan Trangle, Keith Durand, Jiengju Lin, Heather Doering, Smitha Raghunathan, Christopher DiBiasio, Alfredo Bocanegra, Chidinma Obi, Ehsan Farkhondeh, Jennifer Hu, Saundra Quinlan, Yuan Shu, Lisa Chandler",
                                projCode: "data/2004/homepage/codeOfEthics/yellowEthics.html",

                                ideasPic1: "data/2004/ideas/YellowA1.gif",
                                ideasPic2: "data/2004/ideas/YellowA2.gif",
                                ideasPic3: "data/2004/ideas/YellowA3.gif",
                                ideasPic4: "data/2004/ideas/YellowB1.gif",
                                ideasPic5: "data/2004/ideas/YellowB2.gif",
                                ideasPic6: "data/2004/ideas/YellowB3.gif",

                                sketchName1: "KinkaJuice",
                                sketchName2: "Savonius battery charger",
                                sketchName3: "Wind battery charger",
                                sketchName4: "Motorcycle generator",
                                sketchPic1: "data/2006/sketch/photos/yellowA1_1.jpg",
                                sketchPic2: "data/2006/sketch/photos/yellowA1_2.jpg",
                                sketchPic3: "data/2006/sketch/photos/yellowA2_1.jpg",
                                sketchPic4: "data/2006/sketch/photos/yellowA2_2.jpg",
                                sketchPic5: "data/2006/sketch/photos/yellowB1_1.jpg",
                                sketchPic6: "data/2006/sketch/photos/yellowB1_2.jpg",
                                sketchPic7: "data/2006/sketch/photos/yellowB2_1.jpg",
                                sketchPic8: "data/2006/sketch/photos/yellowB2_2.jpg",
                                sketchMov1: "data/2004/sketch/movies/yellowA1.mov",
                                sketchMov2: "data/2004/sketch/movies/yellowA2.mov",
                                sketchMov3: "data/2004/sketch/movies/yellowB1.mov",
                                sketchMov4: "data/2004/sketch/movies/yellowB2.mov",
                                sketchSlide1: "data/2004/sketch/slides/yellowA1.pdf",
                                sketchSlide2: "data/2004/sketch/slides/yellowA2.pdf",
                                sketchSlide3: "data/2004/sketch/slides/yellowB1.pdf",
                                sketchSlide4: "data/2004/sketch/slides/yellowB2.pdf",

                                mockName1: "KinkaJuice",
                                mockName2: "Motor cycle charger",
                                mockPic1: "data/2004/mockup/photos/yellowA1.gif",
                                mockPic2: "data/2004/mockup/photos/yellowA2.gif",
                                mockPic3: "data/2004/mockup/photos/yellowB1.gif",
                                mockPic4: "data/2004/mockup/photos/yellowB2.gif",
                                mockMov1: "data/2004/mockup/movies/yellowA.mov",
                                mockMov2: "data/2004/mockup/movies/yellowB.mov",
                                mockSlide1: "data/2004/mockup/slides/yellowA.pdf",
                                mockSlide2: "data/2004/mockup/slides/yellowB.pdf",

                                assemblyPic1: "data/2004/assembly/yellow1.gif",
                                assemblyContract1: "data/2004/assembly/yellowContract.pdf",

                                techPic1: "data/2004/tech/photos/yellow1.gif",
                                techPic2: "data/2004/tech/photos/yellow2.gif",
                                techMov1: "data/2004/tech/movies/yellow.mov",
                                techContract1: null,

                                finalPic1: "data/2004/final/photos/yellow1.gif",
                                finalPic2: "data/2004/final/photos/yellow2.gif",
                                finalMov1: "data/2004/final/movies/yellow.mov",
                                finalSlide1: "data/2004/final/slides/yellow.pdf",
                                finalBrochure1: "data/2004/final/extras/yellowBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "MP4ever", // folder name
                                projName: "MP4ever",
                                projDesc: "a human powered MP3 player",
                                projColor: "purple",
                                projTeam: "Calvin Bonas, Severiano Canales, Philip Johnson, Sean Schoenmakers, Nathaniel Chan, Luke Haidorfer, Ronald Tharp, Nicasio Gomez III, Peter Sung, Timothy Suen, Ian Collier, Edward Hsieh, Catherine Koveal, Monica Rush, Benjamin Smith, Jeremy Scholz, Jason Martinez, Andrew Baines",
                                projCode: "data/2004/homepage/codeOfEthics/purpleEthics.html",

                                ideasPic1: "data/2004/ideas/PurpleA1.gif",
                                ideasPic2: "data/2004/ideas/PurpleA2.gif",
                                ideasPic3: "data/2004/ideas/PurpleA3.gif",
                                ideasPic4: "data/2004/ideas/PurpleB1.gif",
                                ideasPic5: "data/2004/ideas/PurpleB2.gif",
                                ideasPic6: "data/2004/ideas/PurpleB3.gif",

                                sketchName1: "Kinetic jogger",
                                sketchName2: "Piezo boot",
                                sketchName3: "Modular exercise equipment",
                                sketchName4: "Compressed air regenerative braking",
                                sketchPic1: "data/2006/sketch/photos/purpleA1_1.jpg",
                                sketchPic2: "data/2006/sketch/photos/purpleA1_2.jpg",
                                sketchPic3: "data/2006/sketch/photos/purpleA2_1.jpg",
                                sketchPic4: "data/2006/sketch/photos/purpleA2_2.jpg",
                                sketchPic5: "data/2006/sketch/photos/purpleB1_1.jpg",
                                sketchPic6: "data/2006/sketch/photos/purpleB1_2.jpg",
                                sketchPic7: "data/2006/sketch/photos/purpleB2_1.jpg",
                                sketchPic8: "data/2006/sketch/photos/purpleB2_2.jpg",
                                sketchMov1: "data/2004/sketch/movies/purpleA1.mov",
                                sketchMov2: "data/2004/sketch/movies/purpleA2.mov",
                                sketchMov3: "data/2004/sketch/movies/purpleB1.mov",
                                sketchMov4: "data/2004/sketch/movies/purpleB2.mov",
                                sketchSlide1: "data/2004/sketch/slides/purpleA1.pdf",
                                sketchSlide2: "data/2004/sketch/slides/purpleA2.pdf",
                                sketchSlide3: "data/2004/sketch/slides/purpleB1.pdf",
                                sketchSlide4: "data/2004/sketch/slides/purpleB2.pdf",

                                mockName1: "MP4ever",
                                mockName2: "Cyc-light",
                                mockPic1: "data/2004/mockup/photos/purpleA1.gif",
                                mockPic2: "data/2004/mockup/photos/purpleA2.gif",
                                mockPic3: "data/2004/mockup/photos/purpleB1.gif",
                                mockPic4: "data/2004/mockup/photos/purpleB2.gif",
                                mockMov1: "data/2004/mockup/movies/purpleA.mov",
                                mockMov2: "data/2004/mockup/movies/purpleB.mov",
                                mockSlide1: "data/2004/mockup/slides/purpleA.pdf",
                                mockSlide2: "data/2004/mockup/slides/purpleB.pdf",

                                assemblyPic1: "data/2004/assembly/purple1.gif",
                                assemblyContract1: "data/2004/assembly/purpleContract.pdf",

                                techPic1: "data/2004/tech/photos/purple1.gif",
                                techPic2: "data/2004/tech/photos/purple2.gif",
                                techMov1: "data/2004/tech/movies/purple.mov",
                                techContract1: null,

                                finalPic1: "data/2004/final/photos/purple1.gif",
                                finalPic2: "data/2004/final/photos/purple2.gif",
                                finalMov1: "data/2004/final/movies/purple.mov",
                                finalSlide1: "data/2004/final/slides/purple.pdf",
                                finalBrochure1: "data/2004/final/extras/purpleBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Vac-pack", // folder name
                                projName: "Vac pack",
                                projDesc: "a vaccine cooler",
                                projColor: "orange",
                                projTeam: "Christopher Possinger, Dan Walker, Ethan Crumlin, Emily Smith, Geoff Becker, Gabriel Sanchez, Jonathan Hopkins, Amy Wong, Curtis Vanderpuije, Shauna Jin, Kabir Mukaddam, Myraida Vega, Matthew Carvey, Olumuyiwa Oni, Nathan Ball, Peter Augenbergs, Ryan Roberts, Aparna Jonnalagadda",
                                projCode: "data/2004/homepage/codeOfEthics/orangeEthics.html",

                                ideasPic1: "data/2004/ideas/OrangeA1.gif",
                                ideasPic2: "data/2004/ideas/OrangeA2.gif",
                                ideasPic3: "data/2004/ideas/OrangeA3.gif",
                                ideasPic4: "data/2004/ideas/OrangeB1.gif",
                                ideasPic5: "data/2004/ideas/OrangeB2.gif",
                                ideasPic6: "data/2004/ideas/OrangeB3.gif",

                                sketchName1: "Vaccine refrigerator",
                                sketchName2: "Modify existing refrigerator",
                                sketchName3: "Absorption refrigerator",
                                sketchName4: "On-the-spot cooling",
                                sketchPic1: "data/2006/sketch/photos/orangeA1_1.jpg",
                                sketchPic2: "data/2006/sketch/photos/orangeA1_2.jpg",
                                sketchPic3: "data/2006/sketch/photos/orangeA2_1.jpg",
                                sketchPic4: "data/2006/sketch/photos/orangeA2_2.jpg",
                                sketchPic5: "data/2006/sketch/photos/orangeB1_1.jpg",
                                sketchPic6: "data/2006/sketch/photos/orangeB1_2.jpg",
                                sketchPic7: "data/2006/sketch/photos/orangeB2_1.jpg",
                                sketchPic8: "data/2006/sketch/photos/orangeB2_2.jpg",
                                sketchMov1: "data/2004/sketch/movies/orangeA1.mov",
                                sketchMov2: "data/2004/sketch/movies/orangeA2.mov",
                                sketchMov3: "data/2004/sketch/movies/orangeB1.mov",
                                sketchMov4: "data/2004/sketch/movies/orangeB2.mov",
                                sketchSlide1: "data/2004/sketch/slides/orangeA1.pdf",
                                sketchSlide2: "data/2004/sketch/slides/orangeA2.pdf",
                                sketchSlide3: "data/2004/sketch/slides/orangeB1.pdf",
                                sketchSlide4: "data/2004/sketch/slides/orangeB2.pdf",

                                mockName1: "Vac-pac",
                                mockName2: "Absorption Refrigerator",
                                mockPic1: "data/2004/mockup/photos/orangeA1.gif",
                                mockPic2: "data/2004/mockup/photos/orangeA2.gif",
                                mockPic3: "data/2004/mockup/photos/orangeB1.gif",
                                mockPic4: "data/2004/mockup/photos/orangeB2.gif",
                                mockMov1: "data/2004/mockup/movies/orangeA.mov",
                                mockMov2: "data/2004/mockup/movies/orangeB.mov",
                                mockSlide1: "data/2004/mockup/slides/orangeA.pdf",
                                mockSlide2: "data/2004/mockup/slides/orangeB.pdf",

                                assemblyPic1: "data/2004/assembly/orange1.gif",
                                assemblyContract1: "data/2004/assembly/orangeContract.pdf",

                                techPic1: "data/2004/tech/photos/orange1.gif",
                                techPic2: "data/2004/tech/photos/orange2.gif",
                                techMov1: "data/2004/tech/movies/orange.mov",
                                techContract1: null,

                                finalPic1: "data/2004/final/photos/orange1.gif",
                                finalPic2: "data/2004/final/photos/orange2.gif",
                                finalMov1: "data/2004/final/movies/orange.mov",
                                finalSlide1: "data/2004/final/slides/orange.pdf",
                                finalBrochure1: "data/2004/final/extras/orangeBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Sonic-Seesaw", // folder name
                                projName: "Sonic Seesaw",
                                projDesc: "see-saw pipe organ",
                                projColor: "green",
                                projTeam: "Jacob Bourgeois, Jeremy Schwartz, Jessica Vechakul, Joaquin Ruiz, Matthew Socks, Aaron Sokoloski, Kathleen Barron, Douglas Hwang, Christina Laskowski, Meghan Gibbons, Joseph Audette, Zachary Traina, Matthew Sorge, Marissa Jacovich, Ross Hatton",
                                projCode: "data/2004/homepage/codeOfEthics/greenEthics.html",

                                ideasPic1: "data/2004/ideas/GreenA1.gif",
                                ideasPic2: "data/2004/ideas/GreenA2.gif",
                                ideasPic3: "data/2004/ideas/GreenA3.gif",
                                ideasPic4: "data/2004/ideas/GreenB1.gif",
                                ideasPic5: "data/2004/ideas/GreenB2.gif",
                                ideasPic6: "data/2004/ideas/GreenB3.gif",

                                sketchName1: "Baby bouncer",
                                sketchName2: "Corrective erg machine",
                                sketchName3: "Laser tag",
                                sketchName4: "Interactive playground equipment",
                                sketchPic1: "data/2006/sketch/photos/greenA1_1.jpg",
                                sketchPic2: "data/2006/sketch/photos/greenA1_2.jpg",
                                sketchPic3: "data/2006/sketch/photos/greenA2_1.jpg",
                                sketchPic4: "data/2006/sketch/photos/greenA2_2.jpg",
                                sketchPic5: "data/2006/sketch/photos/greenB1_1.jpg",
                                sketchPic6: "data/2006/sketch/photos/greenB1_2.jpg",
                                sketchPic7: "data/2006/sketch/photos/greenB2_1.jpg",
                                sketchPic8: "data/2006/sketch/photos/greenB2_2.jpg",
                                sketchMov1: "data/2004/sketch/movies/greenA1.mov",
                                sketchMov2: "data/2004/sketch/movies/greenA2.mov",
                                sketchMov3: "data/2004/sketch/movies/greenB1.mov",
                                sketchMov4: "data/2004/sketch/movies/greenB2.mov",
                                sketchSlide1: "data/2004/sketch/slides/greenA1.pdf",
                                sketchSlide2: "data/2004/sketch/slides/greenA2.pdf",
                                sketchSlide3: "data/2004/sketch/slides/greenB1.pdf",
                                sketchSlide4: "data/2004/sketch/slides/greenB2.pdf",

                                mockName1: "Sonic See-saw",
                                mockName2: "Water Works",
                                mockPic1: "data/2004/mockup/photos/greenA1.gif",
                                mockPic2: "data/2004/mockup/photos/greenA2.gif",
                                mockPic3: "data/2004/mockup/photos/greenB1.gif",
                                mockPic4: "data/2004/mockup/photos/greenB2.gif",
                                mockMov1: "data/2004/mockup/movies/greenA.mov",
                                mockMov2: "data/2004/mockup/movies/greenB.mov",
                                mockSlide1: "data/2004/mockup/slides/greenA.pdf",
                                mockSlide2: "data/2004/mockup/slides/greenB.pdf",

                                assemblyPic1: "data/2004/assembly/green1.gif",
                                assemblyContract1: "data/2004/assembly/greenContract.pdf",

                                techPic1: "data/2004/tech/photos/green1.gif",
                                techPic2: "data/2004/tech/photos/green2.gif",
                                techMov1: "data/2004/tech/movies/green.mov",
                                techContract1: null,

                                finalPic1: "data/2004/final/photos/green1.gif",
                                finalPic2: "data/2004/final/photos/green2.gif",
                                finalMov1: "data/2004/final/movies/green.mov",
                                finalSlide1: "data/2004/final/slides/green.pdf",
                                finalBrochure1: "data/2004/final/extras/greenBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Sol-pump", // folder name
                                projName: "Sol pump",
                                projDesc: "a solar steam-powered pump",
                                projColor: "red",
                                projTeam: "Jessica Chiafair, Beth Baniszewski, Jennifer DeBoer, Kyle McKenney, Tom Hennesey, Nicholas Fahey, Moses Heyward, Meredith Silberstein, Edward Sharp, Javier Echenique, Jorge Padilla, Toni Ferreira, Kirk Samaroo, Christina Bonebreak, Laura Nichols, Headley Jacobus",
                                projCode: "data/2004/homepage/codeOfEthics/redEthics.html",

                                ideasPic1: "data/2004/ideas/RedA1.gif",
                                ideasPic2: "data/2004/ideas/RedA2.gif",
                                ideasPic3: "data/2004/ideas/RedA3.gif",
                                ideasPic4: "data/2004/ideas/RedB1.gif",
                                ideasPic5: "data/2004/ideas/RedB2.gif",
                                ideasPic6: "data/2004/ideas/RedB3.gif",

                                sketchName1: "Solar trough 1",
                                sketchName2: "Solar trough 2",
                                sketchName3: "Tracking solar trough",
                                sketchName4: "Solar thermal power",
                                sketchPic1: "data/2006/sketch/photos/redA1_1.jpg",
                                sketchPic2: "data/2006/sketch/photos/redA1_2.jpg",
                                sketchPic3: "data/2006/sketch/photos/redA2_1.jpg",
                                sketchPic4: "data/2006/sketch/photos/redA2_2.jpg",
                                sketchPic5: "data/2006/sketch/photos/redB1_1.jpg",
                                sketchPic6: "data/2006/sketch/photos/redB1_2.jpg",
                                sketchPic7: "data/2006/sketch/photos/redB2_1.jpg",
                                sketchPic8: "data/2006/sketch/photos/redB2_2.jpg",
                                sketchMov1: "data/2004/sketch/movies/redA1.mov",
                                sketchMov2: "data/2004/sketch/movies/redA2.mov",
                                sketchMov3: "data/2004/sketch/movies/redB1.mov",
                                sketchMov4: "data/2004/sketch/movies/redB2.mov",
                                sketchSlide1: "data/2004/sketch/slides/redA1.pdf",
                                sketchSlide2: "data/2004/sketch/slides/redA2.pdf",
                                sketchSlide3: "data/2004/sketch/slides/redB1.pdf",
                                sketchSlide4: "data/2004/sketch/slides/redB2.pdf",

                                mockName1: "Parabolic Tracker",
                                mockName2: "Steam Generation",
                                mockPic1: "data/2004/mockup/photos/redA1.gif",
                                mockPic2: "data/2004/mockup/photos/redA2.gif",
                                mockPic3: "data/2004/mockup/photos/redB1.gif",
                                mockPic4: "data/2004/mockup/photos/redB2.gif",
                                mockMov1: "data/2004/mockup/movies/redA.mov",
                                mockMov2: "data/2004/mockup/movies/redB.mov",
                                mockSlide1: "data/2004/mockup/slides/redA.pdf",
                                mockSlide2: "data/2004/mockup/slides/redB.pdf",

                                assemblyPic1: "data/2004/assembly/red1.gif",
                                assemblyContract1: "data/2004/assembly/redContract.pdf",

                                techPic1: "data/2004/tech/photos/red1.gif",
                                techPic2: "data/2004/tech/photos/red2.gif",
                                techMov1: "data/2004/tech/movies/red.mov",
                                techContract1: null,

                                finalPic1: "data/2004/final/photos/red1.gif",
                                finalPic2: "data/2004/final/photos/red2.gif",
                                finalMov1: "data/2004/final/movies/red.mov",
                                finalSlide1: "data/2004/final/slides/red.pdf",
                                finalBrochure1: "data/2004/final/extras/redBrochure.pdf",
                                finalBrochure2: null,
                        ],
                ],
        ],
]