[
        "2012": [
                themeYear: "2012", // folder name
                themeName: "Outdoors",
                themeDesc: "Any viable, meaningful product idea related to the 'outdoors' is a potential candidate&mdash;transportation, mobility and assistive technology, computing, medical devices, food-related products, sports and recreation, play, and travel all might touch upon the theme.",
                highlights: [
                        [ linkLabel: "Home page and slide show", linkUrl: "data/2012/homepage/index.html" ],
                        [ linkLabel: "Student tribute", linkUrl: "data/2012/highlights/student_tribute_2012.mov", onClick: "window.open('data/2012/highlights/student_tribute_2012.mov', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Final presentation program", linkUrl: "data/2012/highlights/program2012.pdf" ],
                        [ linkLabel: "Final presentation: 3-min compendium", linkUrl: "data/2012/highlights/3min_web_fs.mov", onClick: "window.open('data/2012/highlights/3min_hr_fs.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Final presentation: full show", linkUrl: "data/2012/highlights/ShowForPublic.mov", onClick: "window.open('data/2012/highlights/ShowForPublic.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Polar Bears!", linkUrl: "data/2012/highlights/challenge_2012.mov", onClick: "window.open('data/2012/highlights/challenge_2012.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Orange team: How did they get there?", linkUrl: "data/2012/highlights/orange_team_2012.mov", onClick: "window.open('data/2012/highlights/orange_team_2012.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Project theme of 2012", linkUrl: "data/2012/homepage/project/projectTheme.html" ],
                        [ linkLabel: "Course Syllabus", linkUrl: "data/2012/highlights/syllabus.mov", onClick: "window.open('data/2012/highlights/syllabus.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Product teardown exercise", linkUrl: "data/2012/highlights/Teardown2012Small.mov", onClick: "window.open('data/2012/highlights/Teardown2012Small.mov', 'movieWin', 'width=720,height=480,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Thank you, Prof. Wallace!", linkUrl: "data/2012/highlights/WallaceThankYou2012.mov", onClick: "window.open('data/2012/highlights/WallaceThankYou2012.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "2.009 on The Tech", linkUrl: "http://tech.mit.edu/V131/N59/2.009.html" ],
                        [ linkLabel: "2.009 on The Boston Globe", linkUrl: "http://www.boston.com/news/local/massachusetts/articles/2012/12/31/mit_students_design_vending_machine_to_provide_bike_renters_with_helmets/?page=1" ],
                ],
                highlightDividerIndexes: [1, 11],
                sketchMovWidth: 320,
                sketchMovHeight: 180,
                mockMovWidth: 320,
                mockMovHeight: 180, //changed from 195
                techMovWidth: 320,
                techMovHeight: 180, //changed from 195
                finalMovWidth: 640,
                finalMovHeight: 376,
                picWidth: 240, // picHeight is determined dynamically
                projects: [
                        [
                                projId: "StormShield", // folder name
                                projName: "StormShield",
                                projDesc: "bicycle rain shield",
                                projColor: "blue",
                                projTeam: "Evie Adams, Jacob Bailey, Matt Barron, Felipe Carrillo, Alex Clayton, Phillip Daniel, Eric Del Castillo, Majid Linjawi, Kenya Mejia, Cindy Oh, Ben Pyle, Sam Reineman, Margie Trevino-Garrido, Wanni Tsai, Jack Wanderman, Shuo Wang, Sam Whittermore, Andrew Yang",
                                projCode: "data/2012/homepage/codeOfEthics/codeOfEthics.html#blue",
                                
                                ideasPic1: "data/2012/ideas/BlueA1.jpg",
                                ideasPic2: "data/2012/ideas/BlueA2.jpg",
                                ideasPic3: "data/2012/ideas/BlueA3.jpg",
                                ideasPic4: "data/2012/ideas/BlueB1.jpg",
                                ideasPic5: "data/2012/ideas/BlueB2.jpg",
                                ideasPic6: "data/2012/ideas/BlueB3.jpg",

                                sketchName1: "Collapsi-fin",
                                sketchName2: "Quick Rinse",
                                sketchName3: "RainDrop",
                                sketchName4: "SportShare",
                                sketchPic1: "data/2012/sketch/photos/blueA1_1.jpg",
                                sketchPic2: "data/2012/sketch/photos/blueA1_2.jpg",
                                sketchPic3: "data/2012/sketch/photos/blueA2_1.jpg",
                                sketchPic4: "data/2012/sketch/photos/blueA2_2.jpg",
                                sketchPic5: "data/2012/sketch/photos/blueB1_1.jpg",
                                sketchPic6: "data/2012/sketch/photos/blueB1_2.jpg",
                                sketchPic7: "data/2012/sketch/photos/blueB2_1.jpg",
                                sketchPic8: "data/2012/sketch/photos/blueB2_2.jpg",
                                sketchMov1: "data/2012/sketch/movies/blueA1.mov",
                                sketchMov2: "data/2012/sketch/movies/blueA2.mov",
                                sketchMov3: "data/2012/sketch/movies/blueB1.mov",
                                sketchMov4: "data/2012/sketch/movies/blueB2.mov",
                                sketchSlide1: "data/2012/sketch/slides/blueA1.pdf",
                                sketchSlide2: "data/2012/sketch/slides/blueA2.pdf",
                                sketchSlide3: "data/2012/sketch/slides/blueB1.pdf",
                                sketchSlide4: "data/2012/sketch/slides/blueB2.pdf",

                                mockName1: "BreakPoint Fin",
                                mockName2: "RainDrop",
                                mockPic1: "data/2012/mockup/photos/blueA1.jpg",
                                mockPic2: "data/2012/mockup/photos/blueA2.jpg",
                                mockPic3: "data/2012/mockup/photos/blueB1.jpg",
                                mockPic4: "data/2012/mockup/photos/blueB2.jpg",
                                mockMov1: "data/2012/mockup/movies/blueAs.mov",
                                mockMov2: "data/2012/mockup/movies/blueBs.mov",
                                mockMovWebM1: "data/2012/mockup/movies/blueAs.mov", 
                                mockMovWebM2: "data/2012/mockup/movies/blueBs.mov",

                                mockSlide1: "data/2012/mockup/slides/blueA.pdf",
                                mockSlide2: "data/2012/mockup/slides/blueB.pdf",

                                assemblyPic1: "data/2012/assembly/blueAssembly.jpg",
                                assemblyContract1: "data/2012/assembly/blueContract.pdf",

                                techPic1: "data/2012/tech/photos/Blue1.jpg",
                                techPic2: "data/2012/tech/photos/Blue2.jpg",
                                techMov1: "data/2012/tech/movies/Blue.mov",

                                finalPic1: "data/2012/final/photos/original/blue1.jpg",
                                finalPic1Thumb: "data/2012/final/photos/small/blue1.jpg",
                                finalPic2: "data/2012/final/photos/original/blue2.jpg",
                                finalPic2Thumb: "data/2012/final/photos/small/blue2.jpg",
                                finalMov1: "data/2012/final/movies/blue.mov",
                                finalSlide1: "data/2012/final/slides/blue.pdf",
                                finalBrochure1: "data/2012/final/extras/blueBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Sproutacus", // folder name
                                projName: "Sproutacus",
                                projDesc: "greens harvesting system",
                                projColor: "yellow",
                                projTeam: "Conrad Bastable, Ranjeetha Bharath, Steven Carreno, Justin Colt, Steph Cooke, Carolyn Coyle, Philip Crain, Geoff Dawson, Aaron Fittery, Blair Gagnon, Steven Huynh, Kathleen Kraines, Leslie Meyer, Keneth Pinera, Eduardo Russian, Fareeha Safir, Jay Sircar, Daisy Yan Yuen",
                                projCode: "data/2012/homepage/codeOfEthics/codeOfEthics.html#orange",
                                
                                ideasPic1: "data/2012/ideas/YellowA1.jpg",
                                ideasPic2: "data/2012/ideas/YellowA2.jpg",
                                ideasPic3: "data/2012/ideas/YellowA3.jpg",
                                ideasPic4: "data/2012/ideas/YellowB1.jpg",
                                ideasPic5: "data/2012/ideas/YellowB2.jpg",
                                ideasPic6: "data/2012/ideas/YellowB3.jpg",

                                sketchName1: "Tilt-2-O",
                                sketchName2: "Gathering Greens",
                                sketchName3: "Root Rover",
                                sketchName4: "Tomato Trekker",
                                sketchPic1: "data/2012/sketch/photos/yellowA1_1.jpg",
                                sketchPic2: "data/2012/sketch/photos/yellowA1_2.jpg",
                                sketchPic3: "data/2012/sketch/photos/yellowA2_1.jpg",
                                sketchPic4: "data/2012/sketch/photos/yellowA2_2.jpg",
                                sketchPic5: "data/2012/sketch/photos/yellowB1_1.jpg",
                                sketchPic6: "data/2012/sketch/photos/yellowB1_2.jpg",
                                sketchPic7: "data/2012/sketch/photos/yellowB2_1.jpg",
                                sketchPic8: "data/2012/sketch/photos/yellowB2_2.jpg",
                                sketchMov1: "data/2012/sketch/movies/yellowA1.mov",
                                sketchMov2: "data/2012/sketch/movies/yellowA2.mov",
                                sketchMov3: "data/2012/sketch/movies/yellowB1.mov",
                                sketchMov4: "data/2012/sketch/movies/yellowB2.mov",
                                sketchSlide1: "data/2012/sketch/slides/yellowA1.pdf",
                                sketchSlide2: "data/2012/sketch/slides/yellowA2.pdf",
                                sketchSlide3: "data/2012/sketch/slides/yellowB1.pdf",
                                sketchSlide4: "data/2012/sketch/slides/yellowB2.pdf",

                                mockName1: "Tilt-2-O",
                                mockName2: "Gathering Greens",
                                mockPic1: "data/2012/mockup/photos/yellowA1.jpg",
                                mockPic2: "data/2012/mockup/photos/yellowA2.jpg",
                                mockPic3: "data/2012/mockup/photos/yellowB1.jpg",
                                mockPic4: "data/2012/mockup/photos/yellowB2.jpg",
                                mockMov1: "data/2012/mockup/movies/yellowAs.mov",
                                mockMov2: "data/2012/mockup/movies/yellowBs.mov",
                                mockSlide1: "data/2012/mockup/slides/yellowA.pdf",
                                mockSlide2: "data/2012/mockup/slides/yellowB.pdf",

                                assemblyPic1: "data/2012/assembly/yellowAssembly.jpg",
                                assemblyContract1: "data/2012/assembly/yellowContract.pdf",

                                techPic1: "data/2012/tech/photos/Yellow1.jpg",
                                techPic2: "data/2012/tech/photos/Yellow2.jpg",
                                techMov1: "data/2012/tech/movies/Yellow.mov",
                                techContract1: "data/2012/tech/extras/yellowContract.pdf",

                                finalPic1: "data/2012/final/photos/original/yellow1.jpg",
                                finalPic2: "data/2012/final/photos/original/yellow2.jpg",
                                finalPic1Thumb: "data/2012/final/photos/small/yellow1.jpg",
                                finalPic2Thumb: "data/2012/final/photos/small/yellow2.jpg",
                                finalMov1: "data/2012/final/movies/yellow.mov",
                                finalSlide1: "data/2012/final/slides/yellow.pdf",
                                finalBrochure1: "data/2012/final/extras/yellowBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [

                                projId: "SkyBeacon", // folder name
                                projName: "Sky Beacon",
                                projDesc: "emergency beacon balloon",
                                projColor: "purple",
                                projTeam: "Alejandro Aguirre, Kuljot Anand, Cecilia Cantu, Jeremy deGuzman, Nifer Fasman, Angela Hojnaki, Elina Hu, Laura Matloff, Frederick Moore, Jill Oliveira, Chase Olle, Jason Pier, Nathan Porter, Madeline Salazar, Sarah Southerland, Nick Torgerson",
                                projCode: "data/2012/homepage/codeOfEthics/codeOfEthics.html#purple",
                                
                                ideasPic1: "data/2012/ideas/PurpleA1.jpg",
                                ideasPic2: "data/2012/ideas/PurpleA2.jpg",
                                ideasPic3: "data/2012/ideas/PurpleA3.jpg",
                                ideasPic4: "data/2012/ideas/PurpleB1.jpg",
                                ideasPic5: "data/2012/ideas/PurpleB2.jpg",
                                ideasPic6: "data/2012/ideas/PurpleB3.jpg",

                                sketchName1: "Blind Spotter",
                                sketchName2: "Crusher Trike",
                                sketchName3: "KnapSack",
                                sketchName4: "Sky Beacon",
                                sketchPic1: "data/2012/sketch/photos/purpleA1_1.jpg",
                                sketchPic2: "data/2012/sketch/photos/purpleA1_2.jpg",
                                sketchPic3: "data/2012/sketch/photos/purpleA2_1.jpg",
                                sketchPic4: "data/2012/sketch/photos/purpleA2_2.jpg",
                                sketchPic5: "data/2012/sketch/photos/purpleB1_1.jpg",
                                sketchPic6: "data/2012/sketch/photos/purpleB1_2.jpg",
                                sketchPic7: "data/2012/sketch/photos/purpleB2_1.jpg",
                                sketchPic8: "data/2012/sketch/photos/purpleB2_2.jpg",
                                sketchMov1: "data/2012/sketch/movies/purpleA1.mov",
                                sketchMov2: "data/2012/sketch/movies/purpleA2.mov",
                                sketchMov3: "data/2012/sketch/movies/purpleB1.mov",
                                sketchMov4: "data/2012/sketch/movies/purpleB2.mov",
                                sketchSlide1: "data/2012/sketch/slides/purpleA1.pdf",
                                sketchSlide2: "data/2012/sketch/slides/purpleA2.pdf",
                                sketchSlide3: "data/2012/sketch/slides/purpleB1.pdf",
                                sketchSlide4: "data/2012/sketch/slides/purpleB2.pdf",

                                mockName1: "Blind Spotter",
                                mockName2: "Sky Beacon",
                                mockPic1: "data/2012/mockup/photos/purpleA1.jpg",
                                mockPic2: "data/2012/mockup/photos/purpleA2.jpg",
                                mockPic3: "data/2012/mockup/photos/purpleB1.jpg",
                                mockPic4: "data/2012/mockup/photos/purpleB2.jpg",
                                mockMov1: "data/2012/mockup/movies/purpleAs.mov",
                                mockMov2: "data/2012/mockup/movies/purpleBs.mov",
                                mockSlide1: "data/2012/mockup/slides/purpleA.pdf",
                                mockSlide2: "data/2012/mockup/slides/purpleB.pdf",

                                assemblyPic1: "data/2012/assembly/purpleAssembly.jpg",
                                assemblyContract1: "data/2012/assembly/purpleContract.pdf",

                                techPic1: "data/2012/tech/photos/Purple1.jpg",
                                techPic2: "data/2012/tech/photos/Purple2.jpg",
                                techMov1: "data/2012/tech/movies/Purple.mov",
                                techContract1: "data/2012/tech/extras/purpleContract.pdf",

                                finalPic1: "data/2012/final/photos/original/purple1.jpg",
                                finalPic2: "data/2012/final/photos/original/purple2.jpg",
                                finalPic1Thumb: "data/2012/final/photos/small/purple1.jpg",
                                finalPic2Thumb: "data/2012/final/photos/small/purple2.jpg",
                                finalMov1: "data/2012/final/movies/purple.mov",
                                finalSlide1: "data/2012/final/slides/purple.pdf",
                                finalBrochure1: "data/2012/final/extras/purpleBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [

                                projId: "Ferno", // folder name
                                projName: "Ferno",
                                projDesc: "compact recreational camping stove",
                                projColor: "orange",
                                projTeam: "Kelsey Brigance, Peter Britton, Anna Christensen, Sara Comis, Michelle Deng, Rachel Fernandes, Emi Ferreira-Yang, Rustem Feyzkhanov, Hannah Gramling, Katie Inman, Bethany Lemanski, Daniel de Paula Lopes, Ryan Madson, Janille Maragh, Nate Robert, Ron Rosenberg, Melvin Salinas, Alex Teuffer, Jesse Toapanta",
                                projCode: "data/2012/homepage/codeOfEthics/codeOfEthics.html#orange",

                                ideasPic1: "data/2012/ideas/OrangeA1.jpg",
                                ideasPic2: "data/2012/ideas/OrangeA2.jpg",
                                ideasPic3: "data/2012/ideas/OrangeA3.jpg",
                                ideasPic4: "data/2012/ideas/OrangeB1.jpg",
                                ideasPic5: "data/2012/ideas/OrangeB2.jpg",
                                ideasPic6: "data/2012/ideas/OrangeB3.jpg",

                                sketchName1: "Clip-N-Snow",
                                sketchName2: "Comfort Carrier",
                                sketchName3: "FlexFerno",
                                sketchName4: "EasyPak",
                                sketchPic1: "data/2012/sketch/photos/orangeA1_1.jpg",
                                sketchPic2: "data/2012/sketch/photos/orangeA1_2.jpg",
                                sketchPic3: "data/2012/sketch/photos/orangeA2_1.jpg",
                                sketchPic4: "data/2012/sketch/photos/orangeA2_2.jpg",
                                sketchPic5: "data/2012/sketch/photos/orangeB1_1.jpg",
                                sketchPic6: "data/2012/sketch/photos/orangeB1_2.jpg",
                                sketchPic7: "data/2012/sketch/photos/orangeB2_1.jpg",
                                sketchPic8: "data/2012/sketch/photos/orangeB2_2.jpg",
                                sketchMov1: "data/2012/sketch/movies/orangeA1.mov",
                                sketchMov2: "data/2012/sketch/movies/orangeA2.mov",
                                sketchMov3: "data/2012/sketch/movies/orangeB1.mov",
                                sketchMov4: "data/2012/sketch/movies/orangeB2.mov",
                                sketchSlide1: "data/2012/sketch/slides/orangeA1.pdf",
                                sketchSlide2: "data/2012/sketch/slides/orangeA2.pdf",
                                sketchSlide3: "data/2012/sketch/slides/orangeB1.pdf",
                                sketchSlide4: "data/2012/sketch/slides/orangeB2.pdf",

                                mockName1: "SnapNSnow",
                                mockName2: "FlexFerno",
                                mockPic1: "data/2012/mockup/photos/orangeA1.jpg",
                                mockPic2: "data/2012/mockup/photos/orangeA2.jpg",
                                mockPic3: "data/2012/mockup/photos/orangeB1.jpg",
                                mockPic4: "data/2012/mockup/photos/orangeB2.jpg",
                                mockMov1: "data/2012/mockup/movies/orangeAs.mov",
                                mockMov2: "data/2012/mockup/movies/orangeBs.mov",
                                mockSlide1: "data/2012/mockup/slides/orangeA.pdf",
                                mockSlide2: "data/2012/mockup/slides/orangeB.pdf",

                                assemblyPic1: "data/2012/assembly/orangeAssembly.jpg",
                                assemblyContract1: "data/2012/assembly/orangeContract.pdf",

                                techPic1: "data/2012/tech/photos/Orange1.jpg",
                                techPic2: "data/2012/tech/photos/Orange2.jpg",
                                techMov1: "data/2012/tech/movies/Orange.mov",
                                techContract1: "data/2012/tech/extras/orangeContract.pdf",

                                finalPic1: "data/2012/final/photos/original/orange1.jpg",
                                finalPic2: "data/2012/final/photos/original/orange2.jpg",
                                finalPic1Thumb: "data/2012/final/photos/small/orange1.jpg",
                                finalPic2Thumb: "data/2012/final/photos/small/orange2.jpg",
                                finalMov1: "data/2012/final/movies/orange.mov",
                                finalSlide1: "data/2012/final/slides/orange.pdf",
                                finalBrochure1: "data/2012/final/extras/orangeBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [

                                projId: "Clydesdale", // folder name
                                projName: "Clydesdale",
                                projDesc: "ergonomic keg-dolly",
                                projColor: "silver",
                                projTeam: "Sareena Avadhany, Veronica Barrera, Casandra Ceri, Lia DiGiovanna, Kathryn Greskoff, Eric Hernandez, Matt Hohenberger, Lauren Lo, Molly McShane, Michael Olague, Greg Puzko, John Reynolds, Chris Rullan, Ray Tilden, Bee Vang, Wyatt Ubellacker, Ari Umans",
                                projCode: "data/2012/homepage/codeOfEthics/codeOfEthics.html#silver",

                                ideasPic1: "data/2012/ideas/SilverA1.jpg",
                                ideasPic2: "data/2012/ideas/SilverA2.jpg",
                                ideasPic3: "data/2012/ideas/SilverA3.jpg",
                                ideasPic4: "data/2012/ideas/SilverB1.jpg",
                                ideasPic5: "data/2012/ideas/SilverB2.jpg",
                                ideasPic6: "data/2012/ideas/SilverB3.jpg",

                                sketchName1: "Steered Stroller",
                                sketchName2: "Easy-barrow",
                                sketchName3: "Linus",
                                sketchName4: "Sprout",
                                sketchPic1: "data/2012/sketch/photos/silverA1_1.jpg",
                                sketchPic2: "data/2012/sketch/photos/silverA1_2.jpg",
                                sketchPic3: "data/2012/sketch/photos/silverA2_1.jpg",
                                sketchPic4: "data/2012/sketch/photos/silverA2_2.jpg",
                                sketchPic5: "data/2012/sketch/photos/silverB1_1.jpg",
                                sketchPic6: "data/2012/sketch/photos/silverB1_2.jpg",
                                sketchPic7: "data/2012/sketch/photos/silverB2_1.jpg",
                                sketchPic8: "data/2012/sketch/photos/silverB2_2.jpg",
                                sketchMov1: "data/2012/sketch/movies/silverA1.mov",
                                sketchMov2: "data/2012/sketch/movies/silverA2.mov",
                                sketchMov3: "data/2012/sketch/movies/silverB1.mov",
                                sketchMov4: "data/2012/sketch/movies/silverB2.mov",
                                sketchSlide1: "data/2012/sketch/slides/silverA1.pdf",
                                sketchSlide2: "data/2012/sketch/slides/silverA2.pdf",
                                sketchSlide3: "data/2012/sketch/slides/silverB1.pdf",
                                sketchSlide4: "data/2012/sketch/slides/silverB2.pdf",

                                mockName1: "the keg chute",
                                mockName2: "Linus",
                                mockPic1: "data/2012/mockup/photos/silverA1.jpg",
                                mockPic2: "data/2012/mockup/photos/silverA2.jpg",
                                mockPic3: "data/2012/mockup/photos/silverB1.jpg",
                                mockPic4: "data/2012/mockup/photos/silverB2.jpg",
                                mockMov1: "data/2012/mockup/movies/silverAs.mov",
                                mockMov2: "data/2012/mockup/movies/silverBs.mov",
                                mockSlide1: "data/2012/mockup/slides/silverA.pdf",
                                mockSlide2: "data/2012/mockup/slides/silverB.pdf",

                                assemblyPic1: "data/2012/assembly/silverAssembly.jpg",
                                assemblyContract1: "data/2012/assembly/silverContract.pdf",

                                techPic1: "data/2012/tech/photos/Silver1.jpg",
                                techPic2: "data/2012/tech/photos/Silver2.jpg",
                                techMov1: "data/2012/tech/movies/Silver.mov",
                                techContract1: "data/2012/tech/extras/silverContract.pdf",

                                finalPic1: "data/2012/final/photos/original/silver1.jpg",
                                finalPic2: "data/2012/final/photos/original/silver2.jpg",
                                finalPic1Thumb: "data/2012/final/photos/small/silver1.jpg",
                                finalPic2Thumb: "data/2012/final/photos/small/silver2.jpg",
                                finalMov1: "data/2012/final/movies/silver.mov",
                                finalSlide1: "data/2012/final/slides/silver.pdf",
                                finalBrochure1: "data/2012/final/extras/silverBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "riderguider", // folder name
                                projName: "riderguider",
                                projDesc: "on-bicycle navigation system",
                                projColor: "green",
                                projTeam: "Ahmed Alnemer, Audrey Bosquet, Princess Len Carlos, Devin Dee, Stephen Frost, Chris Gerber, Dan Goodman, Chris Hammond, Charlotte Herhold, Tim Jenks, Arash Kani, Julia Kimmerly, Lauren Kuntz, Paul Lazarescu, Paulina Mustafa, Vahe Taamazyan, Megan Uberti, Jackson Wirekoh, Trevor Zinser",
                                projCode: "data/2012/homepage/codeOfEthics/codeOfEthics.html#green",
                                //pickup here
                                ideasPic1: "data/2012/ideas/GreenA1.jpg",
                                ideasPic2: "data/2012/ideas/GreenA2.jpg",
                                ideasPic3: "data/2012/ideas/GreenA3.jpg",
                                ideasPic4: "data/2012/ideas/GreenB1.jpg",
                                ideasPic5: "data/2012/ideas/GreenB2.jpg",
                                ideasPic6: "data/2012/ideas/GreenB3.jpg",

                                sketchName1: "Bike +",
                                sketchName2: "Search and Rescue Bridge",
                                sketchName3: "Blood Plasma Freeze Dryer",
                                sketchName4: "Foam Bricks",
                                sketchPic1: "data/2012/sketch/photos/greenA1_1.jpg",
                                sketchPic2: "data/2012/sketch/photos/greenA1_2.jpg",
                                sketchPic3: "data/2012/sketch/photos/greenA2_1.jpg",
                                sketchPic4: "data/2012/sketch/photos/greenA2_2.jpg",
                                sketchPic5: "data/2012/sketch/photos/greenB1_1.jpg",
                                sketchPic6: "data/2012/sketch/photos/greenB1_2.jpg",
                                sketchPic7: "data/2012/sketch/photos/greenB2_1.jpg",
                                sketchPic8: "data/2012/sketch/photos/greenB2_2.jpg",
                                sketchMov1: "data/2012/sketch/movies/greenA1.mov",
                                sketchMov2: "data/2012/sketch/movies/greenA2.mov",
                                sketchMov3: "data/2012/sketch/movies/greenB1.mov",
                                sketchMov4: "data/2012/sketch/movies/greenB2.mov",
                                sketchSlide1: "data/2012/sketch/slides/greenA1.pdf",
                                sketchSlide2: "data/2012/sketch/slides/greenA2.pdf",
                                sketchSlide3: "data/2012/sketch/slides/greenB1.pdf",
                                sketchSlide4: "data/2012/sketch/slides/greenB2.pdf",

                                mockName1: "Bike+",
                                mockName2: "Blood Plasma Dehydrator",
                                mockPic1: "data/2012/mockup/photos/greenA1.jpg",
                                mockPic2: "data/2012/mockup/photos/greenA2.jpg",
                                mockPic3: "data/2012/mockup/photos/greenB1.jpg",
                                mockPic4: "data/2012/mockup/photos/greenB2.jpg",
                                mockMov1: "data/2012/mockup/movies/greenAs.mov",
                                mockMov2: "data/2012/mockup/movies/greenBs.mov",
                                mockSlide1: "data/2012/mockup/slides/greenA.pdf",
                                mockSlide2: "data/2012/mockup/slides/greenB.pdf",

                                assemblyPic1: "data/2012/assembly/greenAssembly.jpg",
                                assemblyContract1: "data/2012/assembly/greenContract.pdf",

                                techPic1: "data/2012/tech/photos/Green1.jpg",
                                techPic2: "data/2012/tech/photos/Green2.jpg",
                                techMov1: "data/2012/tech/movies/Green.mov",
                                techContract1: "data/2012/tech/extras/greenContract.pdf",

                                finalPic1: "data/2012/final/photos/original/green1.jpg",
                                finalPic2: "data/2012/final/photos/original/green2.jpg",
                                finalPic1Thumb: "data/2012/final/photos/small/green1.jpg",
                                finalPic2Thumb: "data/2012/final/photos/small/green2.jpg",
                                finalMov1: "data/2012/final/movies/green.mov",
                                finalSlide1: "data/2012/final/slides/green.pdf",
                                finalBrochure1: "data/2012/final/extras/greenBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [

                                projId: "Heatware", // folder name
                                projName: "Heatware",
                                projDesc: "flameless camp stove",
                                projColor: "red",
                                projTeam: "Xenia Antipova, Gabriel Blanchet, Daniel Bloch, Michael Buchman, Sebastian Denault, Sean Fannin, Rachel Fraunhoffer, Monica Isava, Brigitte Morales, Ernesto Reza, Oscar Rojas, Julia Titarelli, Vanessa Trevino, Anne Warren, Shannon Yang",
                                projCode: "data/2012/homepage/codeOfEthics/codeOfEthics.html#red",

                                ideasPic1: "data/2012/ideas/RedA1.jpg",
                                ideasPic2: "data/2012/ideas/RedA2.jpg",
                                ideasPic3: "data/2012/ideas/RedA3.jpg",
                                ideasPic4: "data/2012/ideas/RedB1.jpg",
                                ideasPic5: "data/2012/ideas/RedB2.jpg",
                                ideasPic6: "data/2012/ideas/RedB3.jpg",

                                sketchName1: "Qook",
                                sketchName2: "Qook To Go",
                                sketchName3: "Lumenbrella",
                                sketchName4: "Duo Seat",
                                sketchPic1: "data/2012/sketch/photos/redA1_1.jpg",
                                sketchPic2: "data/2012/sketch/photos/redA1_2.jpg",
                                sketchPic3: "data/2012/sketch/photos/redA2_1.jpg",
                                sketchPic4: "data/2012/sketch/photos/redA2_2.jpg",
                                sketchPic5: "data/2012/sketch/photos/redB1_1.jpg",
                                sketchPic6: "data/2012/sketch/photos/redB1_2.jpg",
                                sketchPic7: "data/2012/sketch/photos/redB2_1.jpg",
                                sketchPic8: "data/2012/sketch/photos/redB2_2.jpg",
                                sketchMov1: "data/2012/sketch/movies/redA1.mov",
                                sketchMov2: "data/2012/sketch/movies/redA2.mov",
                                sketchMov3: "data/2012/sketch/movies/redB1.mov",
                                sketchMov4: "data/2012/sketch/movies/redB2.mov",
                                sketchSlide1: "data/2012/sketch/slides/redA1.pdf",
                                sketchSlide2: "data/2012/sketch/slides/redA2.pdf",
                                sketchSlide3: "data/2012/sketch/slides/redB1.pdf",
                                sketchSlide4: "data/2012/sketch/slides/redB2.pdf",

                                mockName1: "Qook",
                                mockName2: "Duoseat",
                                mockPic1: "data/2012/mockup/photos/redA1.jpg",
                                mockPic2: "data/2012/mockup/photos/redA2.jpg",
                                mockPic3: "data/2012/mockup/photos/redB1.jpg",
                                mockPic4: "data/2012/mockup/photos/redB2.jpg",
                                mockMov1: "data/2012/mockup/movies/redAs.mov",
                                mockMov2: "data/2012/mockup/movies/redBs.mov",
                                mockSlide1: "data/2012/mockup/slides/redA.pdf",
                                mockSlide2: "data/2012/mockup/slides/redB.pdf",

                                assemblyPic1: "data/2012/assembly/redAssembly.jpg",
                                assemblyContract1: "data/2012/assembly/redContract.pdf",

                                techPic1: "data/2012/tech/photos/Red1.jpg",
                                techPic2: "data/2012/tech/photos/Red2.jpg",
                                techMov1: "data/2012/tech/movies/Red.mov",
                                techContract1: "data/2012/tech/extras/redContract.pdf",

                                finalPic1: "data/2012/final/photos/original/red1.jpg",
                                finalPic2: "data/2012/final/photos/original/red2.jpg",
                                finalPic1Thumb: "data/2012/final/photos/small/red1.jpg",
                                finalPic2Thumb: "data/2012/final/photos/small/red2.jpg",
                                finalMov1: "data/2012/final/movies/red.mov",
                                finalSlide1: "data/2012/final/slides/red.pdf",
                                finalBrochure1: "data/2012/final/extras/redBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Herc", // folder name
                                projName: "Herc",
                                projDesc: "hygenic efficient receptacle cleaning",
                                projColor: "pink",
                                projTeam: "Kameron Chan, Camille Everhart, Grant Iwamoto, Manuel Legrand, Jeffrey Lin, Bridger Maxwell, Franco Montalvo, Icy Morozova, Nanc Ouyang, Thao Phan, Cory Robinson, Andrew Sommer, Anastasia Uryasheva, Dmitriy Vasilev, Hui Xia, Richard Yoon, Irina Zhelavskaya",
                                projCode: "data/2012/homepage/codeOfEthics/codeOfEthics.html#pink",

                                ideasPic1: "data/2012/ideas/PinkA1.jpg",
                                ideasPic2: "data/2012/ideas/PinkA2.jpg",
                                ideasPic3: "data/2012/ideas/PinkA3.jpg",
                                ideasPic4: "data/2012/ideas/PinkB1.jpg",
                                ideasPic5: "data/2012/ideas/PinkB2.jpg",
                                ideasPic6: "data/2012/ideas/PinkB3.jpg",

                                sketchName1: "Cargo Assist",
                                sketchName2: "Jamclam",
                                sketchName3: "Waste Washer",
                                sketchName4: "Parcel Pro",
                                sketchPic1: "data/2012/sketch/photos/pinkA1_1.jpg",
                                sketchPic2: "data/2012/sketch/photos/pinkA1_2.jpg",
                                sketchPic3: "data/2012/sketch/photos/pinkA2_1.jpg",
                                sketchPic4: "data/2012/sketch/photos/pinkA2_2.jpg",
                                sketchPic5: "data/2012/sketch/photos/pinkB1_1.jpg",
                                sketchPic6: "data/2012/sketch/photos/pinkB1_2.jpg",
                                sketchPic7: "data/2012/sketch/photos/pinkB2_1.jpg",
                                sketchPic8: "data/2012/sketch/photos/pinkB2_2.jpg",
                                sketchMov1: "data/2012/sketch/movies/pinkA1.mov",
                                sketchMov2: "data/2012/sketch/movies/pinkA2.mov",
                                sketchMov3: "data/2012/sketch/movies/pinkB1.mov",
                                sketchMov4: "data/2012/sketch/movies/pinkB2.mov",
                                sketchSlide1: "data/2012/sketch/slides/pinkA1.pdf",
                                sketchSlide2: "data/2012/sketch/slides/pinkA2.pdf",
                                sketchSlide3: "data/2012/sketch/slides/pinkB1.pdf",
                                sketchSlide4: "data/2012/sketch/slides/pinkB2.pdf",

                                mockName1: "JamPack",
                                mockName2: "Parcel Pro",
                                mockPic1: "data/2012/mockup/photos/pinkA1.jpg",
                                mockPic2: "data/2012/mockup/photos/pinkA2.jpg",
                                mockPic3: "data/2012/mockup/photos/pinkB1.jpg",
                                mockPic4: "data/2012/mockup/photos/pinkB2.jpg",
                                mockMov1: "data/2012/mockup/movies/pinkAs.mov",
                                mockMov2: "data/2012/mockup/movies/pinkBs.mov",
                                mockSlide1: "data/2012/mockup/slides/pinkA.pdf",
                                mockSlide2: "data/2012/mockup/slides/pinkB.pdf",

                                assemblyPic1: "data/2012/assembly/pinkAssembly.jpg",
                                assemblyContract1: "data/2012/assembly/pinkContract.pdf",

                                techPic1: "data/2012/tech/photos/Pink1.jpg",
                                techPic2: "data/2012/tech/photos/Pink2.jpg",
                                techMov1: "data/2012/tech/movies/Pink.mov",
                                techContract1: "data/2012/tech/extras/pinkContract.pdf",

                                finalPic1: "data/2012/final/photos/original/pink1.jpg",
                                finalPic2: "data/2012/final/photos/original/pink2.jpg",
                                finalPic1Thumb: "data/2012/final/photos/small/pink1.jpg",
                                finalPic2Thumb: "data/2012/final/photos/small/pink2.jpg",
                                finalMov1: "data/2012/final/movies/pink.mov",
                                finalSlide1: "data/2012/final/slides/pink.pdf",
                                finalBrochure1: "data/2012/final/extras/pinkBrochure.pdf",
                                finalBrochure2: null,
                        ],
                ],
        ],
]