[
        "2013": [
                themeYear: "2013", // folder name
                themeName: "Be Well",
                themeDesc: "Any viable, meaningful product idea related to 'be well' is a potential candidate&mdash;medicine, mental health and wellness, recreation, entertainment, sport, agriculture, ranching, manufacturing, family, global heath and sustainability might touch upon the theme.",
                highlights: [
                        [ linkLabel: "Home page and slide show", linkUrl: "data/2013/homepage/index.html" ],
                        [ linkLabel: "Student tribute", linkUrl: "data/2013/highlights/student_tribute_2013.mov", onClick: "window.open('data/2013/highlights/student_tribute_2013.mov', 'movieWin', 'width=340,height=280,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Final presentation program", linkUrl: "data/2013/highlights/program2013.pdf" ],
                        [ linkLabel: "Final presentation: 4-min compendium", linkUrl: "data/2013/highlights/4_min_web_360p.mov", onClick: "window.open('data/2013/highlights/4_min_web_360p.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Final presentation: full show", linkUrl: "data/2013/highlights/full_show_2013.mov", onClick: "window.open('data/2013/highlights/full_show_2013.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Final Presentation Day", linkUrl: "data/2013/highlights/finalPresentationDay_2013.mov", onClick: "window.open('data/2013/highlights/finalPresentationDay_2013.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Human-Powered Vehicles!", linkUrl: "data/2013/highlights/challenge_2013mov", onClick: "window.open('data/2013/highlights/challenge_2013.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Orange team: How did they get there?", linkUrl: "data/2013/highlights/orange_team_2013.mov", onClick: "window.open('data/2013/highlights/orange_team_2013.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Project theme of 2013", linkUrl: "data/2013/homepage/project/projectTheme.html" ],
                        [ linkLabel: "Course Syllabus", linkUrl: "data/2013/highlights/syllabus.mov", onClick: "window.open('data/2013/highlights/syllabus.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Product teardown exercise", linkUrl: "data/2013/highlights/teardown_2013.mov", onClick: "window.open('data/2013/highlights/teardown_2013.mov', 'movieWin', 'width=720,height=480,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "Thank you, Prof. Wallace!", linkUrl: "data/2013/highlights/thankyou_2013mov", onClick: "window.open('data/2013/highlights/thankyou_2013.mov', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false"  ],
                        [ linkLabel: "2.009 in The Tech", linkUrl: "http://tech.mit.edu/V133/N60/two009.html" ],
                        [ linkLabel: "2.009 in MIT News", linkUrl: "http://newsoffice.mit.edu/2013/engineering-students-demonstrate-product-prototypes-1211" ],
                ],
                highlightDividerIndexes: [1, 11],
                sketchMovWidth: 320,
                sketchMovHeight: 180,
                mockMovWidth: 320,
                mockMovHeight: 180, //changed from 195
                techMovWidth: 320,
                techMovHeight: 180, //changed from 195
                finalMovWidth: 640,
                finalMovHeight: 360, //changed from 376
                useNewVideoPlayer: true,
                picWidth: 240, // picHeight is determined dynamically
                projects: [
                        [
                                projId: "San-X", // folder name
                                projName: "San-X",
                                projDesc: "exercise mat cleaner",
                                projColor: "blue",
                                projTeam: "Raad Alshareef, Evelyn Tio, Will Dominas, Taylor Farnham, Miho Kitagawa, Curtis Wu, Mariah Hake, Philine Huizing, Ting-Ting Liu, Alexandra Taylor, Betsy Soukup, Brandon Holloway, Sarah Ritter, Ishaan Kumar, Kristine Bunker, John Kongoletos, Michael Nackoul, Phillip Marmolejo",
                                projCode: "data/2013/homepage/codeOfEthics/codeOfEthics.html#blue",
                                
                                ideasPic1: "data/2013/ideas/BlueA1.jpg",
                                ideasPic2: "data/2013/ideas/BlueA2.jpg",
                                ideasPic3: "data/2013/ideas/BlueA3.jpg",
                                ideasPic4: "data/2013/ideas/BlueB1.jpg",
                                ideasPic5: "data/2013/ideas/BlueB2.jpg",
                                ideasPic6: "data/2013/ideas/BlueB3.jpg",

                                sketchName1: "Toy Wash",
                                sketchName2: "Handy Hippo",
                                sketchName3: "SaniSurf",
                                sketchName4: "PoliShine",
                                sketchPic1: "data/2013/sketch/photos/blueA1_1.jpg",
                                sketchPic2: "data/2013/sketch/photos/blueA1_2.jpg",
                                sketchPic3: "data/2013/sketch/photos/blueA2_1.jpg",
                                sketchPic4: "data/2013/sketch/photos/blueA2_2.jpg",
                                sketchPic5: "data/2013/sketch/photos/blueB1_1.jpg",
                                sketchPic6: "data/2013/sketch/photos/blueB1_2.jpg",
                                sketchPic7: "data/2013/sketch/photos/blueB2_1.jpg",
                                sketchPic8: "data/2013/sketch/photos/blueB2_2.jpg",
                                sketchMov1: "data/2013/sketch/movies/blueA1",
                                sketchMov2: "data/2013/sketch/movies/blueA2",
                                sketchMov3: "data/2013/sketch/movies/blueB1",
                                sketchMov4: "data/2013/sketch/movies/blueB2",
                                sketchSlide1: "data/2013/sketch/slides/blueA1.pdf",
                                sketchSlide2: "data/2013/sketch/slides/blueA2.pdf",
                                sketchSlide3: "data/2013/sketch/slides/blueB1.pdf",
                                sketchSlide4: "data/2013/sketch/slides/blueB2.pdf",

                                mockName1: "spray",
                                mockName2: "matmate",
                                mockPic1: "data/2013/mockup/photos/blueA1.jpg",
                                mockPic2: "data/2013/mockup/photos/blueA2.jpg",
                                mockPic3: "data/2013/mockup/photos/blueB1.jpg",
                                mockPic4: "data/2013/mockup/photos/blueB2.jpg",
                                mockMov1: "data/2013/mockup/movies/blueAs",
                                mockMov2: "data/2013/mockup/movies/blueBs",
                                mockSlide1: "data/2013/mockup/slides/blueA.pdf",
                                mockSlide2: "data/2013/mockup/slides/blueB.pdf",

                                assemblyPic1: "data/2013/assembly/blueAssembly.jpg",
                                assemblyContract1: "data/2013/assembly/blueContract.pdf",

                                techPic1: "data/2013/tech/photos/Blue1.jpg",
                                techPic2: "data/2013/tech/photos/Blue2.jpg",
                                techMov1: "data/2013/tech/movies/Blue",

                                finalPic1: "data/2013/final/photos/original/blue1.jpg",
                                finalPic1Thumb: "data/2013/final/photos/small/blue1.jpg",
                                finalPic2: "data/2013/final/photos/original/blue2.jpg",
                                finalPic2Thumb: "data/2013/final/photos/small/blue2.jpg",
                                finalMov1: "data/2013/final/movies/blue",
                                finalSlide1: "data/2013/final/slides/blue.pdf",
                                finalBrochure1: "data/2013/final/extras/blueBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Glow", // folder name
                                projName: "Glow",
                                projDesc: "light-up yoga mat",
                                projColor: "yellow",
                                projTeam: "David Christoff, Demetra Sklaviadis, Jeff Corothers, Jon Rea, Kojo Acquah, Patrick Dayton, Molly Duffy, PJ Buddhari, Tanya Liu, Tom Burrow, Abbey Bethel, Alex McCarthy, Caleb Jones, Erin Meyer, Ian Martin, Julia Ellermeier, Toks Fifo, Youyou Li",
                                projCode: "data/2013/homepage/codeOfEthics/codeOfEthics.html#orange",
                                
                                ideasPic1: "data/2013/ideas/YellowA1.jpg",
                                ideasPic2: "data/2013/ideas/YellowA2.jpg",
                                ideasPic3: "data/2013/ideas/YellowA3.jpg",
                                ideasPic4: "data/2013/ideas/YellowB1.jpg",
                                ideasPic5: "data/2013/ideas/YellowB2.jpg",
                                ideasPic6: "data/2013/ideas/YellowB3.jpg",

                                sketchName1: "glow",
                                sketchName2: "U-brella",
                                sketchName3: "Fold and Hold",
                                sketchName4: "SkyStow",
                                sketchPic1: "data/2013/sketch/photos/yellowA1_1.jpg",
                                sketchPic2: "data/2013/sketch/photos/yellowA1_2.jpg",
                                sketchPic3: "data/2013/sketch/photos/yellowA2_1.jpg",
                                sketchPic4: "data/2013/sketch/photos/yellowA2_2.jpg",
                                sketchPic5: "data/2013/sketch/photos/yellowB1_1.jpg",
                                sketchPic6: "data/2013/sketch/photos/yellowB1_2.jpg",
                                sketchPic7: "data/2013/sketch/photos/yellowB2_1.jpg",
                                sketchPic8: "data/2013/sketch/photos/yellowB2_2.jpg",
                                sketchMov1: "data/2013/sketch/movies/yellowA1",
                                sketchMov2: "data/2013/sketch/movies/yellowA2",
                                sketchMov3: "data/2013/sketch/movies/yellowB1",
                                sketchMov4: "data/2013/sketch/movies/yellowB2",
                                sketchSlide1: "data/2013/sketch/slides/yellowA1.pdf",
                                sketchSlide2: "data/2013/sketch/slides/yellowA2.pdf",
                                sketchSlide3: "data/2013/sketch/slides/yellowB1.pdf",
                                sketchSlide4: "data/2013/sketch/slides/yellowB2.pdf",

                                mockName1: "glow",
                                mockName2: "Hold & Fold",
                                mockPic1: "data/2013/mockup/photos/yellowA1.jpg",
                                mockPic2: "data/2013/mockup/photos/yellowA2.jpg",
                                mockPic3: "data/2013/mockup/photos/yellowB1.jpg",
                                mockPic4: "data/2013/mockup/photos/yellowB2.jpg",
                                mockMov1: "data/2013/mockup/movies/yellowAs",
                                mockMov2: "data/2013/mockup/movies/yellowBs",
                                mockSlide1: "data/2013/mockup/slides/yellowA.pdf",
                                mockSlide2: "data/2013/mockup/slides/yellowB.pdf",

                                assemblyPic1: "data/2013/assembly/yellowAssembly.jpg",
                                assemblyContract1: "data/2013/assembly/yellowContract.pdf",

                                techPic1: "data/2013/tech/photos/Yellow1.jpg",
                                techPic2: "data/2013/tech/photos/Yellow2.jpg",
                                techMov1: "data/2013/tech/movies/Yellow",
                                techContract1: "data/2013/tech/extras/yellowContract.pdf",

                                finalPic1: "data/2013/final/photos/original/yellow1.jpg",
                                finalPic2: "data/2013/final/photos/original/yellow2.jpg",
                                finalPic1Thumb: "data/2013/final/photos/small/yellow1.jpg",
                                finalPic2Thumb: "data/2013/final/photos/small/yellow2.jpg",
                                finalMov1: "data/2013/final/movies/yellow",
                                finalSlide1: "data/2013/final/slides/yellow.pdf",
                                finalBrochure1: "data/2013/final/extras/yellowBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [

                                projId: "EquiTemp", // folder name
                                projName: "EquiTemp",
                                projDesc: "horse temperature sensor",
                                projColor: "purple",
                                projTeam: "Ayman AbuShirbi, David Alfonso, Holly Jamerson, Kaitlyn Nealon, Katie Chasins, Matt Metlitz, Oscar Salgado, Ramya Swamy, Saul Lopez, Viveka Mishra, Ben Lewis, Chacha Durazo, Daniel Meza, Eddie Carrillo, Julia Hsu, Lucy Du, Ovie Orieka, Rachel Dias Carlson, Steven Jens Jorgensen, Victor Rodriguez",
                                projCode: "data/2013/homepage/codeOfEthics/codeOfEthics.html#purple",
                                
                                ideasPic1: "data/2013/ideas/PurpleA1.jpg",
                                ideasPic2: "data/2013/ideas/PurpleA2.jpg",
                                ideasPic3: "data/2013/ideas/PurpleA3.jpg",
                                ideasPic4: "data/2013/ideas/PurpleB1.jpg",
                                ideasPic5: "data/2013/ideas/PurpleB2.jpg",
                                ideasPic6: "data/2013/ideas/PurpleB3.jpg",

                                sketchName1: "TerraStretch",
                                sketchName2: "EquiSense",
                                sketchName3: "Firevention!",
                                sketchName4: "SafeCut",
                                sketchPic1: "data/2013/sketch/photos/purpleA1_1.jpg",
                                sketchPic2: "data/2013/sketch/photos/purpleA1_2.jpg",
                                sketchPic3: "data/2013/sketch/photos/purpleA2_1.jpg",
                                sketchPic4: "data/2013/sketch/photos/purpleA2_2.jpg",
                                sketchPic5: "data/2013/sketch/photos/purpleB1_1.jpg",
                                sketchPic6: "data/2013/sketch/photos/purpleB1_2.jpg",
                                sketchPic7: "data/2013/sketch/photos/purpleB2_1.jpg",
                                sketchPic8: "data/2013/sketch/photos/purpleB2_2.jpg",
                                sketchMov1: "data/2013/sketch/movies/purpleA1",
                                sketchMov2: "data/2013/sketch/movies/purpleA2",
                                sketchMov3: "data/2013/sketch/movies/purpleB1",
                                sketchMov4: "data/2013/sketch/movies/purpleB2",
                                sketchSlide1: "data/2013/sketch/slides/purpleA1.pdf",
                                sketchSlide2: "data/2013/sketch/slides/purpleA2.pdf",
                                sketchSlide3: "data/2013/sketch/slides/purpleB1.pdf",
                                sketchSlide4: "data/2013/sketch/slides/purpleB2.pdf",

                                mockName1: "EquiSense",
                                mockName2: "SafeCut",
                                mockPic1: "data/2013/mockup/photos/purpleA1.jpg",
                                mockPic2: "data/2013/mockup/photos/purpleA2.jpg",
                                mockPic3: "data/2013/mockup/photos/purpleB1.jpg",
                                mockPic4: "data/2013/mockup/photos/purpleB2.jpg",
                                mockMov1: "data/2013/mockup/movies/purpleAs",
                                mockMov2: "data/2013/mockup/movies/purpleBs",
                                mockSlide1: "data/2013/mockup/slides/purpleA.pdf",
                                mockSlide2: "data/2013/mockup/slides/purpleB.pdf",

                                assemblyPic1: "data/2013/assembly/purpleAssembly.jpg",
                                assemblyContract1: "data/2013/assembly/purpleContract.pdf",

                                techPic1: "data/2013/tech/photos/Purple1.jpg",
                                techPic2: "data/2013/tech/photos/Purple2.jpg",
                                techMov1: "data/2013/tech/movies/Purple",
                                techContract1: "data/2013/tech/extras/purpleContract.pdf",

                                finalPic1: "data/2013/final/photos/original/purple1.jpg",
                                finalPic2: "data/2013/final/photos/original/purple2.jpg",
                                finalPic1Thumb: "data/2013/final/photos/small/purple1.jpg",
                                finalPic2Thumb: "data/2013/final/photos/small/purple2.jpg",
                                finalMov1: "data/2013/final/movies/purple",
                                finalSlide1: "data/2013/final/slides/purple.pdf",
                                finalBrochure1: "data/2013/final/extras/purpleBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [

                                projId: "Mira", // folder name
                                projName: "Mira",
                                projDesc: "motorcycle navigation display",
                                projColor: "orange",
                                projTeam: "Candace Chen, Andre Negrao Costa, Ricardo Reyna Fernadez, Matt Times, Michael Farid, Louise van den Heuvel, Brian Foley, Keenan Sunderwirth, Bruno Flores dos Santos Mattos, Veronica Newlin",
                                projCode: "data/2013/homepage/codeOfEthics/codeOfEthics.html#orange",

                                ideasPic1: "data/2013/ideas/OrangeA1.jpg",
                                ideasPic2: "data/2013/ideas/OrangeA2.jpg",
                                ideasPic3: "data/2013/ideas/OrangeA3.jpg",
                                ideasPic4: "data/2013/ideas/OrangeB1.jpg",
                                ideasPic5: "data/2013/ideas/OrangeB2.jpg",
                                ideasPic6: "data/2013/ideas/OrangeB3.jpg",

                                sketchName1: "HUD Helmet",
                                sketchName2: "Portable CNC Router",
                                sketchName3: "FallSafe",
                                sketchName4: "BreatheEasy",
                                sketchPic1: "data/2013/sketch/photos/orangeA1_1.jpg",
                                sketchPic2: "data/2013/sketch/photos/orangeA1_2.jpg",
                                sketchPic3: "data/2013/sketch/photos/orangeA2_1.jpg",
                                sketchPic4: "data/2013/sketch/photos/orangeA2_2.jpg",
                                sketchPic5: "data/2013/sketch/photos/orangeB1_1.jpg",
                                sketchPic6: "data/2013/sketch/photos/orangeB1_2.jpg",
                                sketchPic7: "data/2013/sketch/photos/orangeB2_1.jpg",
                                sketchPic8: "data/2013/sketch/photos/orangeB2_2.jpg",
                                sketchMov1: "data/2013/sketch/movies/orangeA1",
                                sketchMov2: "data/2013/sketch/movies/orangeA2",
                                sketchMov3: "data/2013/sketch/movies/orangeB1",
                                sketchMov4: "data/2013/sketch/movies/orangeB2",
                                sketchSlide1: "data/2013/sketch/slides/orangeA1.pdf",
                                sketchSlide2: "data/2013/sketch/slides/orangeA2.pdf",
                                sketchSlide3: "data/2013/sketch/slides/orangeB1.pdf",
                                sketchSlide4: "data/2013/sketch/slides/orangeB2.pdf",

                                mockName1: "HUDs up!",
                                mockName2: "PUX Router Pro",
                                mockPic1: "data/2013/mockup/photos/orangeA1.jpg",
                                mockPic2: "data/2013/mockup/photos/orangeA2.jpg",
                                mockPic3: "data/2013/mockup/photos/orangeB1.jpg",
                                mockPic4: "data/2013/mockup/photos/orangeB2.jpg",
                                mockMov1: "data/2013/mockup/movies/orangeAs",
                                mockMov2: "data/2013/mockup/movies/orangeBs",
                                mockSlide1: "data/2013/mockup/slides/orangeA.pdf",
                                mockSlide2: "data/2013/mockup/slides/orangeB.pdf",

                                assemblyPic1: "data/2013/assembly/orangeAssembly.jpg",
                                assemblyContract1: "data/2013/assembly/orangeContract.pdf",

                                techPic1: "data/2013/tech/photos/Orange1.jpg",
                                techPic2: "data/2013/tech/photos/Orange2.jpg",
                                techMov1: "data/2013/tech/movies/Orange",
                                techContract1: "data/2013/tech/extras/orangeContract.pdf",

                                finalPic1: "data/2013/final/photos/original/orange1.jpg",
                                finalPic2: "data/2013/final/photos/original/orange2.jpg",
                                finalPic1Thumb: "data/2013/final/photos/small/orange1.jpg",
                                finalPic2Thumb: "data/2013/final/photos/small/orange2.jpg",
                                finalMov1: "data/2013/final/movies/orange",
                                finalSlide1: "data/2013/final/slides/orange.pdf",
                                finalBrochure1: "data/2013/final/extras/orangeBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [

                                projId: "BitDex", // folder name
                                projName: "BitDex",
                                projDesc: "drill bit measuring device",
                                projColor: "silver",
                                projTeam: "Christina Rosales, Katarina Struckmann, Guille Mirandes, Bridget Hunter-Jones, Katy Evans, Austin Gutierrez, Emily Dunne, Josh Sibblies, Eric Crespo-Lezama, Kaitlyn Bailey, Krista Nordin, Shaka Thornhill, Angela Chu, Christopher Kelly, Immanuel Madukauwa-David, Isaac Fenta, Juliana Wu",
                                projCode: "data/2013/homepage/codeOfEthics/codeOfEthics.html#silver",

                                ideasPic1: "data/2013/ideas/SilverA1.jpg",
                                ideasPic2: "data/2013/ideas/SilverA2.jpg",
                                ideasPic3: "data/2013/ideas/SilverA3.jpg",
                                ideasPic4: "data/2013/ideas/SilverB1.jpg",
                                ideasPic5: "data/2013/ideas/SilverB2.jpg",
                                ideasPic6: "data/2013/ideas/SilverB3.jpg",

                                sketchName1: "the Ultimate Frisbee",
                                sketchName2: "Bit Bot",
                                sketchName3: "Mini-Load",
                                sketchName4: "Lift Ladder",
                                sketchPic1: "data/2013/sketch/photos/silverA1_1.jpg",
                                sketchPic2: "data/2013/sketch/photos/silverA1_2.jpg",
                                sketchPic3: "data/2013/sketch/photos/silverA2_1.jpg",
                                sketchPic4: "data/2013/sketch/photos/silverA2_2.jpg",
                                sketchPic5: "data/2013/sketch/photos/silverB1_1.jpg",
                                sketchPic6: "data/2013/sketch/photos/silverB1_2.jpg",
                                sketchPic7: "data/2013/sketch/photos/silverB2_1.jpg",
                                sketchPic8: "data/2013/sketch/photos/silverB2_2.jpg",
                                sketchMov1: "data/2013/sketch/movies/silverA1",
                                sketchMov2: "data/2013/sketch/movies/silverA2",
                                sketchMov3: "data/2013/sketch/movies/silverB1",
                                sketchMov4: "data/2013/sketch/movies/silverB2",
                                sketchSlide1: "data/2013/sketch/slides/silverA1.pdf",
                                sketchSlide2: "data/2013/sketch/slides/silverA2.pdf",
                                sketchSlide3: "data/2013/sketch/slides/silverB1.pdf",
                                sketchSlide4: "data/2013/sketch/slides/silverB2.pdf",

                                mockName1: "BitBot",
                                mockName2: "Ulti-LIT",
                                mockPic1: "data/2013/mockup/photos/silverA1.jpg",
                                mockPic2: "data/2013/mockup/photos/silverA2.jpg",
                                mockPic3: "data/2013/mockup/photos/silverB1.jpg",
                                mockPic4: "data/2013/mockup/photos/silverB2.jpg",
                                mockMov1: "data/2013/mockup/movies/silverAs",
                                mockMov2: "data/2013/mockup/movies/silverBs",
                                mockSlide1: "data/2013/mockup/slides/silverA.pdf",
                                mockSlide2: "data/2013/mockup/slides/silverB.pdf",

                                assemblyPic1: "data/2013/assembly/silverAssembly.jpg",
                                assemblyContract1: "data/2013/assembly/silverContract.pdf",

                                techPic1: "data/2013/tech/photos/Silver1.jpg",
                                techPic2: "data/2013/tech/photos/Silver2.jpg",
                                techMov1: "data/2013/tech/movies/Silver",
                                techContract1: "data/2013/tech/extras/silverContract.pdf",

                                finalPic1: "data/2013/final/photos/original/silver1.jpg",
                                finalPic2: "data/2013/final/photos/original/silver2.jpg",
                                finalPic1Thumb: "data/2013/final/photos/small/silver1.jpg",
                                finalPic2Thumb: "data/2013/final/photos/small/silver2.jpg",
                                finalMov1: "data/2013/final/movies/silver",
                                finalSlide1: "data/2013/final/slides/silver.pdf",
                                finalBrochure1: "data/2013/final/extras/silverBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Poseiden", // folder name
                                projName: "Poseiden",
                                projDesc: "laser pacer for swimming",
                                projColor: "green",
                                projTeam: "Ben Potash, Jad El Khoury, Emily Hupf, Ignacio Bachiller, Marcos Grochowski Mattana, Natalie Dostie, Onsi Sawiris, Sean Cockey, Carolyn Zhang, Devin Cornish, Daniel Gillund, Kerry Nicholson, Matt White, Ronald Chan, Sidhanth Rao, Tom Peleg",
                                projCode: "data/2013/homepage/codeOfEthics/codeOfEthics.html#green",
                                //pickup here
                                ideasPic1: "data/2013/ideas/GreenA1.jpg",
                                ideasPic2: "data/2013/ideas/GreenA2.jpg",
                                ideasPic3: "data/2013/ideas/GreenA3.jpg",
                                ideasPic4: "data/2013/ideas/GreenB1.jpg",
                                ideasPic5: "data/2013/ideas/GreenB2.jpg",
                                ideasPic6: "data/2013/ideas/GreenB3.jpg",

                                sketchName1: "pacer laser",
                                sketchName2: "step analyzer",
                                sketchName3: "smart spot",
                                sketchName4: "broccoli bike",
                                sketchPic1: "data/2013/sketch/photos/greenA1_1.jpg",
                                sketchPic2: "data/2013/sketch/photos/greenA1_2.jpg",
                                sketchPic3: "data/2013/sketch/photos/greenA2_1.jpg",
                                sketchPic4: "data/2013/sketch/photos/greenA2_2.jpg",
                                sketchPic5: "data/2013/sketch/photos/greenB1_1.jpg",
                                sketchPic6: "data/2013/sketch/photos/greenB1_2.jpg",
                                sketchPic7: "data/2013/sketch/photos/greenB2_1.jpg",
                                sketchPic8: "data/2013/sketch/photos/greenB2_2.jpg",
                                sketchMov1: "data/2013/sketch/movies/greenA1",
                                sketchMov2: "data/2013/sketch/movies/greenA2",
                                sketchMov3: "data/2013/sketch/movies/greenB1",
                                sketchMov4: "data/2013/sketch/movies/greenB2",
                                sketchSlide1: "data/2013/sketch/slides/greenA1.pdf",
                                sketchSlide2: "data/2013/sketch/slides/greenA2.pdf",
                                sketchSlide3: "data/2013/sketch/slides/greenB1.pdf",
                                sketchSlide4: "data/2013/sketch/slides/greenB2.pdf",

                                mockName1: "Pacer Laser",
                                mockName2: "InstaPump",
                                mockPic1: "data/2013/mockup/photos/greenA1.jpg",
                                mockPic2: "data/2013/mockup/photos/greenA2.jpg",
                                mockPic3: "data/2013/mockup/photos/greenB1.jpg",
                                mockPic4: "data/2013/mockup/photos/greenB2.jpg",
                                mockMov1: "data/2013/mockup/movies/greenAs",
                                mockMov2: "data/2013/mockup/movies/greenBs",
                                mockSlide1: "data/2013/mockup/slides/greenA.pdf",
                                mockSlide2: "data/2013/mockup/slides/greenB.pdf",

                                assemblyPic1: "data/2013/assembly/greenAssembly.jpg",
                                assemblyContract1: "data/2013/assembly/greenContract.pdf",

                                techPic1: "data/2013/tech/photos/Green1.jpg",
                                techPic2: "data/2013/tech/photos/Green2.jpg",
                                techMov1: "data/2013/tech/movies/Green",
                                techContract1: "data/2013/tech/extras/greenContract.pdf",

                                finalPic1: "data/2013/final/photos/original/green1.jpg",
                                finalPic2: "data/2013/final/photos/original/green2.jpg",
                                finalPic1Thumb: "data/2013/final/photos/small/green1.jpg",
                                finalPic2Thumb: "data/2013/final/photos/small/green2.jpg",
                                finalMov1: "data/2013/final/movies/green",
                                finalSlide1: "data/2013/final/slides/green.pdf",
                                finalBrochure1: "data/2013/final/extras/greenBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [

                                projId: "Ollie", // folder name
                                projName: "Ollie",
                                projDesc: "affordable therapeutic companion",
                                projColor: "red",
                                projTeam: "Kristina Johnson, Will Kalb, Luke O'Malley, David Orozco, Patricia P Pezzi, Luke Plummer, Doug Sanchez, Andrew Stratton, Emily Yang, Rick Zang, Alix de Monts, Anders Rasmussen, Carrie Liang, Chris Haid, Hazel Zengeni, Jose Lara, Kate O'Connor, Mateo Pena Doll, Nilu Zhao, Tim Wilczynski",
                                projCode: "data/2013/homepage/codeOfEthics/codeOfEthics.html#red",

                                ideasPic1: "data/2013/ideas/RedA1.jpg",
                                ideasPic2: "data/2013/ideas/RedA2.jpg",
                                ideasPic3: "data/2013/ideas/RedA3.jpg",
                                ideasPic4: "data/2013/ideas/RedB1.jpg",
                                ideasPic5: "data/2013/ideas/RedB2.jpg",
                                ideasPic6: "data/2013/ideas/RedB3.jpg",

                                sketchName1: "Herobo",
                                sketchName2: "MotoThresher",
                                sketchName3: "MagneGlasses",
                                sketchName4: "PEF Water Purifier",
                                sketchPic1: "data/2013/sketch/photos/redA1_1.jpg",
                                sketchPic2: "data/2013/sketch/photos/redA1_2.jpg",
                                sketchPic3: "data/2013/sketch/photos/redA2_1.jpg",
                                sketchPic4: "data/2013/sketch/photos/redA2_2.jpg",
                                sketchPic5: "data/2013/sketch/photos/redB1_1.jpg",
                                sketchPic6: "data/2013/sketch/photos/redB1_2.jpg",
                                sketchPic7: "data/2013/sketch/photos/redB2_1.jpg",
                                sketchPic8: "data/2013/sketch/photos/redB2_2.jpg",
                                sketchMov1: "data/2013/sketch/movies/redA1",
                                sketchMov2: "data/2013/sketch/movies/redA2",
                                sketchMov3: "data/2013/sketch/movies/redB1",
                                sketchMov4: "data/2013/sketch/movies/redB2",
                                sketchSlide1: "data/2013/sketch/slides/redA1.pdf",
                                sketchSlide2: "data/2013/sketch/slides/redA2.pdf",
                                sketchSlide3: "data/2013/sketch/slides/redB1.pdf",
                                sketchSlide4: "data/2013/sketch/slides/redB2.pdf",

                                mockName1: "Herobo",
                                mockName2: "MotoThresher",
                                mockPic1: "data/2013/mockup/photos/redA1.jpg",
                                mockPic2: "data/2013/mockup/photos/redA2.jpg",
                                mockPic3: "data/2013/mockup/photos/redB1.jpg",
                                mockPic4: "data/2013/mockup/photos/redB2.jpg",
                                mockMov1: "data/2013/mockup/movies/redAs",
                                mockMov2: "data/2013/mockup/movies/redBs",
                                mockSlide1: "data/2013/mockup/slides/redA.pdf",
                                mockSlide2: "data/2013/mockup/slides/redB.pdf",

                                assemblyPic1: "data/2013/assembly/redAssembly.jpg",
                                assemblyContract1: "data/2013/assembly/redContract.pdf",

                                techPic1: "data/2013/tech/photos/Red1.jpg",
                                techPic2: "data/2013/tech/photos/Red2.jpg",
                                techMov1: "data/2013/tech/movies/Red",
                                techContract1: "data/2013/tech/extras/redContract.pdf",

                                finalPic1: "data/2013/final/photos/original/red1.jpg",
                                finalPic2: "data/2013/final/photos/original/red2.jpg",
                                finalPic1Thumb: "data/2013/final/photos/small/red1.jpg",
                                finalPic2Thumb: "data/2013/final/photos/small/red2.jpg",
                                finalMov1: "data/2013/final/movies/red",
                                finalSlide1: "data/2013/final/slides/red.pdf",
                                finalBrochure1: "data/2013/final/extras/redBrochure.pdf",
                                finalBrochure2: null,
                        ],
                        [
                                projId: "Verda", // folder name
                                projName: "Verda",
                                projDesc: "mobile bicycle farm stand",
                                projColor: "pink",
                                projTeam: "Shirley Mao, Stephanie Ku, Fernando Rivera Gonzalez, Khalid Alqahtani, Bruce Arensen, Katherine Ferreira Martinez, Tarun Malik, Jorge Colmenero, Ben Hessels, Abdulrahman Khayyat, Ahmed Madani, Adrian Grossman, C.J. Munroe, Emma Benjaminson, Cheetiri Smith, Katie Spies, Hana Khalil, Kojo Welbeck",
                                projCode: "data/2013/homepage/codeOfEthics/codeOfEthics.html#pink",

                                ideasPic1: "data/2013/ideas/PinkA1.jpg",
                                ideasPic2: "data/2013/ideas/PinkA2.jpg",
                                ideasPic3: "data/2013/ideas/PinkA3.jpg",
                                ideasPic4: "data/2013/ideas/PinkB1.jpg",
                                ideasPic5: "data/2013/ideas/PinkB2.jpg",
                                ideasPic6: "data/2013/ideas/PinkB3.jpg",

                                sketchName1: "AFM 9000",
                                sketchName2: "Phold-It!",
                                sketchName3: "The MC2",
                                sketchName4: "iGarden",
                                sketchPic1: "data/2013/sketch/photos/pinkA1_1.jpg",
                                sketchPic2: "data/2013/sketch/photos/pinkA1_2.jpg",
                                sketchPic3: "data/2013/sketch/photos/pinkA2_1.jpg",
                                sketchPic4: "data/2013/sketch/photos/pinkA2_2.jpg",
                                sketchPic5: "data/2013/sketch/photos/pinkB1_1.jpg",
                                sketchPic6: "data/2013/sketch/photos/pinkB1_2.jpg",
                                sketchPic7: "data/2013/sketch/photos/pinkB2_1.jpg",
                                sketchPic8: "data/2013/sketch/photos/pinkB2_2.jpg",
                                sketchMov1: "data/2013/sketch/movies/pinkA1",
                                sketchMov2: "data/2013/sketch/movies/pinkA2",
                                sketchMov3: "data/2013/sketch/movies/pinkB1",
                                sketchMov4: "data/2013/sketch/movies/pinkB2",
                                sketchSlide1: "data/2013/sketch/slides/pinkA1.pdf",
                                sketchSlide2: "data/2013/sketch/slides/pinkA2.pdf",
                                sketchSlide3: "data/2013/sketch/slides/pinkB1.pdf",
                                sketchSlide4: "data/2013/sketch/slides/pinkB2.pdf",

                                mockName1: "AFM 9000",
                                mockName2: "G2G: Greens To Go",
                                mockPic1: "data/2013/mockup/photos/pinkA1.jpg",
                                mockPic2: "data/2013/mockup/photos/pinkA2.jpg",
                                mockPic3: "data/2013/mockup/photos/pinkB1.jpg",
                                mockPic4: "data/2013/mockup/photos/pinkB2.jpg",
                                mockMov1: "data/2013/mockup/movies/pinkAs",
                                mockMov2: "data/2013/mockup/movies/pinkBs",
                                mockSlide1: "data/2013/mockup/slides/pinkA.pdf",
                                mockSlide2: "data/2013/mockup/slides/pinkB.pdf",

                                assemblyPic1: "data/2013/assembly/pinkAssembly.jpg",
                                assemblyContract1: "data/2013/assembly/pinkContract.pdf",

                                techPic1: "data/2013/tech/photos/Pink1.jpg",
                                techPic2: "data/2013/tech/photos/Pink2.jpg",
                                techMov1: "data/2013/tech/movies/Pink",
                                techContract1: "data/2013/tech/extras/pinkContract.pdf",

                                finalPic1: "data/2013/final/photos/original/pink1.jpg",
                                finalPic2: "data/2013/final/photos/original/pink2.jpg",
                                finalPic1Thumb: "data/2013/final/photos/small/pink1.jpg",
                                finalPic2Thumb: "data/2013/final/photos/small/pink2.jpg",
                                finalMov1: "data/2013/final/movies/pink",
                                finalSlide1: "data/2013/final/slides/pink.pdf",
                                finalBrochure1: "data/2013/final/extras/pinkBrochure.pdf",
                                finalBrochure2: null,
                        ],
                ],
        ],
]