DATA = {
    "2015": {
        themeYear: "2015", // folder name
        themeName: "Magic",
        themeDesc: "Any viable, meaningful product idea related to 'magic' is a potential candidate&mdash;compelling products that afford new memorable experiences or feelings fit under the theme.",
        highlights: [
            {
                linkLabel: "Home page and slide show",
                linkUrl: "data/2015/homepage/index.html"
            },
            {
                linkLabel: "Student tribute",
                linkUrl: "data/2015/highlights/student_tribute_2015.mp4"
            },
            {
                linkLabel: "Final Presentation: Program",
                linkUrl: "data/2015/highlights/program2015.pdf"
            },
            {
                linkLabel: "Final Presentation: 5-min Compendium",
                linkUrl: "data/2015/highlights/5_min_web_360p.mp4"
            },
            {
                linkLabel: "Final Presentation: Quadcopter and Intro",
                linkUrl: "data/2015/highlights/quad_2015.mp4"
            },
            {
                linkLabel: "Final Presentation: Full Show",
                linkUrl: "data/2015/highlights/full_show_2015.mp4"
            },
            {
                linkLabel: "Final Presentation: Timelapse",
                linkUrl: "data/2015/highlights/timelapse_setup_2015.mp4"
            },
            {
                linkLabel: "Balloon Challenge 2015",
                linkUrl: "data/2015/highlights/balloon_2015.mp4"
            },
            {
                linkLabel: "Build Challenge 2015: Once Upon an Idea",
                linkUrl: "data/2015/highlights/challenge_2015.mov"
            },

            {
                linkLabel: "Yellow team: How did they get there?",
                linkUrl: "data/2015/highlights/yellow_team_2015.mp4",
                onClick: "window.open('data/2015/highlights/yellow_team_2015.mp4', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false",
            },
            {
                linkLabel: "Project theme of 2015",
                linkUrl: "data/2015/homepage/project/projectTheme.html",
            },
            {
                linkLabel: "Thank you, Prof. Wallace!",
                linkUrl: "data/2015/highlights/thankyou_2015.mp4",
                onClick: "window.open('data/2015/highlights/thankyou_2015.mp4', 'movieWin', 'width=640,height=360,scrollbars=no,resizable=no');return false",
            },

        ],
        sketchMovWidth: 320,
        sketchMovHeight: 180,
        mockMovWidth: 320,
        mockMovHeight: 180, //changed from 195
        techMovWidth: 320,
        techMovHeight: 180, //changed from 195
        finalMovWidth: 640,
        finalMovHeight: 360, //changed from 376
        useNewVideoPlayer: true,
        picWidth: 240, // picHeight is determined dynamically
        projects: [{
                projId: "Laser Kites", // folder name
                projName: "Laser Kites",
                projDesc: "kite game",
                projColor: "blue",
                projTeam: "Ben Mattinson, Dabin Choe, Isaac LaJoie, Jack Greenfield, Manny Simpri Elimbi, Marie Moudio, Melody Liu, Mustafa Almuallim, Raudel Hernandez, Brady Enstad, Clare Zhang, Grace Connors, Kale Rogers, Kath Xu, Luis Gasca, Max Molina, Patrick Lowe, Rachel Reed, Rodrigo Marques",
                projCode: "data/2015/homepage/codeOfEthics/codeOfEthics.html#blue",

                teamSections: {
                    A: {
                        numIdeas: 3,
                        numSketches: 3,
                        sketchNames: ["Walk and Roll", "Earsight", "Watchful"],
                        sketchVimeoIds: ["185915828", "185915828", "185915828"],
                        numMocks: 2,
                        mockNames: ["Walk & Roll", "Watchful"],
                        mockVimeoIds: ["185915828", "185915828"],
                    },
                    B: {
                        numIdeas: 3,
                        numSketches: 3,
                        sketchNames: ["Polaris", "Sky Cab", "Kite Racer"],
                        sketchVimeoIds: ["185915828", "185915828", "185915828"],
                        numMocks: 2,
                        mockNames: ["Polaris", "Laser Kite"],
                        mockVimeoIds: ["185915828", "185915828"],
                    },
                },

                ideasPicA1: "data/2015/ideas/blueA1.jpg",
                ideasPicA2: "data/2015/ideas/blueA2.jpg",
                ideasPicA3: "data/2015/ideas/blueA3.jpg",
                ideasPicB1: "data/2015/ideas/blueB1.jpg",
                ideasPicB2: "data/2015/ideas/blueB2.jpg",
                ideasPicB3: "data/2015/ideas/blueB3.jpg",

                sketchNameA1: "Walk and Roll",
                sketchNameA2: "Earsight",
                sketchNameA3: "Watchful",
                sketchNameB1: "Polaris",
                sketchNameB2: "Sky Cab",
                sketchNameB3: "Kite Racer",
                sketchPicA1_1: "data/2015/sketch/photos/blueA1_1.jpg",
                sketchPicA1_2: "data/2015/sketch/photos/blueA1_2.jpg",
                sketchPicA2_1: "data/2015/sketch/photos/blueA2_1.jpg",
                sketchPicA2_2: "data/2015/sketch/photos/blueA2_2.jpg",
                sketchPicA3_1: "data/2015/sketch/photos/blueA3_1.jpg",
                sketchPicA3_2: "data/2015/sketch/photos/blueA3_2.jpg",
                sketchPicB1_1: "data/2015/sketch/photos/blueB1_1.jpg",
                sketchPicB1_2: "data/2015/sketch/photos/blueB1_2.jpg",
                sketchPicB2_1: "data/2015/sketch/photos/blueB2_1.jpg",
                sketchPicB2_2: "data/2015/sketch/photos/blueB2_2.jpg",
                sketchPicB3_1: "data/2015/sketch/photos/blueB3_1.jpg",
                sketchPicB3_2: "data/2015/sketch/photos/blueB3_2.jpg",

                sketchMovA1: "data/2015/sketch/movies/blueA1",
                sketchMovA2: "data/2015/sketch/movies/blueA2",
                sketchMovA3: "data/2015/sketch/movies/blueA3",
                sketchMovB1: "data/2015/sketch/movies/blueB1",
                sketchMovB2: "data/2015/sketch/movies/blueB2",
                sketchMovB3: "data/2015/sketch/movies/blueB3",
                sketchSlideA1: "data/2015/sketch/slides/blueA1.pdf",
                sketchSlideA2: "data/2015/sketch/slides/blueA2.pdf",
                sketchSlideA3: "data/2015/sketch/slides/blueA3.pdf",
                sketchSlideB1: "data/2015/sketch/slides/blueB1.pdf",
                sketchSlideB2: "data/2015/sketch/slides/blueB2.pdf",
                sketchSlideB3: "data/2015/sketch/slides/blueB3.pdf",

                mockName1: "Walk & Roll",
                mockName2: "Watchful",
                mockName3: "Polaris",
                mockName4: "Laser Kite",
                mockPicA1_1: "data/2015/mockup/photos/blueA1_1.jpg",
                mockPicA1_2: "data/2015/mockup/photos/blueA1_2.jpg",
                mockPicA2_1: "data/2015/mockup/photos/blueA2_1.jpg",
                mockPicA2_2: "data/2015/mockup/photos/blueA2_2.jpg",
                mockPicB1_1: "data/2015/mockup/photos/blueB1_1.jpg",
                mockPicB1_2: "data/2015/mockup/photos/blueB1_2.jpg",
                mockPicB2_1: "data/2015/mockup/photos/blueB2_1.jpg",
                mockPicB2_2: "data/2015/mockup/photos/blueB2_2.jpg",
                mockMovA1: "data/2015/mockup/movies/blueA1",
                mockMovA2: "data/2015/mockup/movies/blueA2",
                mockMovB1: "data/2015/mockup/movies/blueB1",
                mockMovB2: "data/2015/mockup/movies/blueB2",
                mockSlideA1: "data/2015/mockup/slides/blueA1.pdf",
                mockSlideA2: "data/2015/mockup/slides/blueA2.pdf",
                mockSlideB1: "data/2015/mockup/slides/blueB1.pdf",
                mockSlideB2: "data/2015/mockup/slides/blueB2.pdf",

                assemblyPic1: "data/2015/assembly/blueAssembly.jpg",
                assemblyContract1: "data/2015/assembly/blueContract.pdf",

                techPic1: "data/2015/tech/photos/Blue1.jpg",
                techPic2: "data/2015/tech/photos/Blue2.jpg",
                techMov1: "data/2015/tech/movies/blue",

                finalPic1: "data/2015/final/photos/original/blue1.jpg",
                finalPic1Thumb: "data/2015/final/photos/small/blue1.jpg",
                finalPic2: "data/2015/final/photos/original/blue2.jpg",
                finalPic2Thumb: "data/2015/final/photos/small/blue2.jpg",
                finalMov1: "data/2015/final/movies/blue",
                finalSlide1: "data/2015/final/slides/blue.pdf",
                finalBrochure1: "data/2015/final/extras/blue_brochure.pdf",
                finalBrochure2: null,
            },
            {
                 // folder name
                projId: "Petra",
                projName: "Petra",
                projDesc: "repelling device",
                projColor: "yellow",
                projTeam: "Faisal Alaskar, Graham Francis, Isabella DiDio, Jonah Hessels, Kate Tatar, Langston Fitts, Lauren St. Hilaire, Milly Helmick, Paul Cohen, Skyler Adams, Tony DiBlasi, Abdulrahman Alhabaidi, Christopher Chapman, Danny Joh, Deron Browne, Emma Steinhardt, James Tsao, Julia Huang, Lena Yang, Paige Grody, Tobi Rudoltz, Victoria Tam",
                projCode: "data/2015/homepage/codeOfEthics/codeOfEthics.html#yellow",

                ideasPic1: "data/2015/ideas/YellowA1.jpg",
                ideasPic2: "data/2015/ideas/YellowA2.jpg",
                ideasPic3: "data/2015/ideas/YellowA3.jpg",
                ideasPic4: "data/2015/ideas/YellowB1.jpg",
                ideasPic5: "data/2015/ideas/YellowB2.jpg",
                ideasPic6: "data/2015/ideas/YellowB3.jpg",

                sketchName1: "AscendAble",
                sketchName2: "Smooth Operator",
                sketchName3: "Simple Solar",
                sketchName4: "UniMask",
                sketchName5: "Simul-Climber",
                sketchName6: "Unfoltable",
                sketchPic1: "data/2015/sketch/photos/yellowA1_1.jpg",
                sketchPic2: "data/2015/sketch/photos/yellowA1_2.jpg",
                sketchPic3: "data/2015/sketch/photos/yellowA2_1.jpg",
                sketchPic4: "data/2015/sketch/photos/yellowA2_2.jpg",
                sketchPic5: "data/2015/sketch/photos/yellowA3_1.jpg",
                sketchPic6: "data/2015/sketch/photos/yellowA3_2.jpg",
                sketchPic7: "data/2015/sketch/photos/yellowB1_1.jpg",
                sketchPic8: "data/2015/sketch/photos/yellowB1_2.jpg",
                sketchPic9: "data/2015/sketch/photos/yellowB2_1.jpg",
                sketchPic10: "data/2015/sketch/photos/yellowB2_2.jpg",
                sketchPic11: "data/2015/sketch/photos/yellowB3_1.jpg",
                sketchPic12: "data/2015/sketch/photos/yellowB3_2.jpg",
                sketchMov1: "data/2015/sketch/movies/yellowA1",
                sketchMov2: "data/2015/sketch/movies/yellowA2",
                sketchMov3: "data/2015/sketch/movies/yellowA3",
                sketchMov4: "data/2015/sketch/movies/yellowB1",
                sketchMov5: "data/2015/sketch/movies/yellowB2",
                sketchMov6: "data/2015/sketch/movies/yellowB3",
                sketchSlide1: "data/2015/sketch/slides/yellowA1.pdf",
                sketchSlide2: "data/2015/sketch/slides/yellowA2.pdf",
                sketchSlide2: "data/2015/sketch/slides/yellowA3.pdf",
                sketchSlide3: "data/2015/sketch/slides/yellowB1.pdf",
                sketchSlide4: "data/2015/sketch/slides/yellowB2.pdf",
                sketchSlide4: "data/2015/sketch/slides/yellowB3.pdf",

                mockName1: "FallNot",
                mockName2: "Smooth Operator",
                mockName3: "Caravan",
                mockName4: "Simul",
                mockPic1: "data/2015/mockup/photos/yellowA1_1.jpg",
                mockPic2: "data/2015/mockup/photos/yellowA1_2.jpg",
                mockPic3: "data/2015/mockup/photos/yellowA2_1.jpg",
                mockPic4: "data/2015/mockup/photos/yellowA2_2.jpg",
                mockPic5: "data/2015/mockup/photos/yellowB1_1.jpg",
                mockPic6: "data/2015/mockup/photos/yellowB1_2.jpg",
                mockPic7: "data/2015/mockup/photos/yellowB2_1.jpg",
                mockPic8: "data/2015/mockup/photos/yellowB2_2.jpg",
                mockMov1: "data/2015/mockup/movies/yellowA1",
                mockMov2: "data/2015/mockup/movies/yellowA2",
                mockMov3: "data/2015/mockup/movies/yellowB1",
                mockMov4: "data/2015/mockup/movies/yellowB2",
                mockSlide1: "data/2015/mockup/slides/yellowA1.pdf",
                mockSlide2: "data/2015/mockup/slides/yellowA2.pdf",
                mockSlide3: "data/2015/mockup/slides/yellowB1.pdf",
                mockSlide4: "data/2015/mockup/slides/yellowB2.pdf",

                assemblyPic1: "data/2015/assembly/yellowAssembly.jpg",
                assemblyContract1: "data/2015/assembly/yellowContract.pdf",

                techPic1: "data/2015/tech/photos/Yellow1.jpg",
                techPic2: "data/2015/tech/photos/Yellow2.jpg",
                techMov1: "data/2015/tech/movies/yellow",

                finalPic1: "data/2015/final/photos/original/yellow1.jpg",
                finalPic1Thumb: "data/2015/final/photos/small/yellow1.jpg",
                finalPic2: "data/2015/final/photos/original/yellow2.jpg",
                finalPic2Thumb: "data/2015/final/photos/small/yellow2.jpg",
                finalMov1: "data/2015/final/movies/yellow",
                finalSlide1: "data/2015/final/slides/yellow.pdf",
                finalBrochure1: "data/2015/final/extras/yellow_brochure.pdf",
                finalBrochure2: null,
            },
            {
                projId: "Trellis", // folder name
                projName: "Trellis",
                projDesc: "IV pole",
                projColor: "red",
                projTeam: "Amando Antonini, Amy Ishiguro, Chris McPherson, Christine Jiang, Josh Acosta, Kira Street, McCall Huston, Meaghan Fitzgerald, Paige Kennedy, States Lee, Sunnie Lampl, Tori Jensen, Alex Konradi, Beth Cholst, Claire Patterson, Katy Kem, Michael Wymer, Morgan Gilliver, Negin Abdolrahim Poorheravi, Rachel Nations, Sophia Jaffe, Teddy Ort",
                projCode: "data/2015/homepage/codeOfEthics/codeOfEthics.html#red",

                ideasPic1: "data/2015/ideas/RedA1.jpg",
                ideasPic2: "data/2015/ideas/RedA2.jpg",
                ideasPic3: "data/2015/ideas/RedA3.jpg",
                ideasPic4: "data/2015/ideas/RedB1.jpg",
                ideasPic5: "data/2015/ideas/RedB2.jpg",
                ideasPic6: "data/2015/ideas/RedB3.jpg",

                sketchName1: "Fresherizer",
                sketchName2: "Trellis",
                sketchName3: "Harmonius",
                sketchName4: "Snail Express",
                sketchName5: "Pocket Knob",
                sketchName6: "Tatsu",
                sketchPic1: "data/2015/sketch/photos/redA1_1.jpg",
                sketchPic2: "data/2015/sketch/photos/redA1_2.jpg",
                sketchPic3: "data/2015/sketch/photos/redA2_1.jpg",
                sketchPic4: "data/2015/sketch/photos/redA2_2.jpg",
                sketchPic5: "data/2015/sketch/photos/redA3_1.jpg",
                sketchPic6: "data/2015/sketch/photos/redA3_2.jpg",
                sketchPic7: "data/2015/sketch/photos/redB1_1.jpg",
                sketchPic8: "data/2015/sketch/photos/redB1_2.jpg",
                sketchPic9: "data/2015/sketch/photos/redB2_1.jpg",
                sketchPic10: "data/2015/sketch/photos/redB2_2.jpg",
                sketchPic11: "data/2015/sketch/photos/redB3_1.jpg",
                sketchPic12: "data/2015/sketch/photos/redB3_2.jpg",
                sketchMov1: "data/2015/sketch/movies/redA1",
                sketchMov2: "data/2015/sketch/movies/redA2",
                sketchMov3: "data/2015/sketch/movies/redA3",
                sketchMov4: "data/2015/sketch/movies/redB1",
                sketchMov5: "data/2015/sketch/movies/redB2",
                sketchMov6: "data/2015/sketch/movies/redB3",
                sketchSlide1: "data/2015/sketch/slides/redA1.pdf",
                sketchSlide2: "data/2015/sketch/slides/redA2.pdf",
                sketchSlide2: "data/2015/sketch/slides/redA3.pdf",
                sketchSlide3: "data/2015/sketch/slides/redB1.pdf",
                sketchSlide4: "data/2015/sketch/slides/redB2.pdf",
                sketchSlide4: "data/2015/sketch/slides/redB3.pdf",

                mockName1: "Trellis",
                mockName2: "Fresherizer",
                mockName3: "Cool Baby",
                mockName4: "Tatsu",
                mockPic1: "data/2015/mockup/photos/redA1_1.jpg",
                mockPic2: "data/2015/mockup/photos/redA1_2.jpg",
                mockPic3: "data/2015/mockup/photos/redA2_1.jpg",
                mockPic4: "data/2015/mockup/photos/redA2_2.jpg",
                mockPic5: "data/2015/mockup/photos/redB1_1.jpg",
                mockPic6: "data/2015/mockup/photos/redB1_2.jpg",
                mockPic7: "data/2015/mockup/photos/redB2_1.jpg",
                mockPic8: "data/2015/mockup/photos/redB2_2.jpg",
                mockMov1: "data/2015/mockup/movies/redA1",
                mockMov2: "data/2015/mockup/movies/redA2",
                mockMov3: "data/2015/mockup/movies/redB1",
                mockMov4: "data/2015/mockup/movies/redB2",
                mockSlide1: "data/2015/mockup/slides/redA1.pdf",
                mockSlide2: "data/2015/mockup/slides/redA2.pdf",
                mockSlide3: "data/2015/mockup/slides/redB1.pdf",
                mockSlide4: "data/2015/mockup/slides/redB2.pdf",

                assemblyPic1: "data/2015/assembly/redAssembly.jpg",
                assemblyContract1: "data/2015/assembly/redContract.pdf",

                techPic1: "data/2015/tech/photos/Red1.jpg",
                techPic2: "data/2015/tech/photos/Red2.jpg",
                techMov1: "data/2015/tech/movies/red",

                finalPic1: "data/2015/final/photos/original/red1.jpg",
                finalPic1Thumb: "data/2015/final/photos/small/red1.jpg",
                finalPic2: "data/2015/final/photos/original/red2.jpg",
                finalPic2Thumb: "data/2015/final/photos/small/red2.jpg",
                finalMov1: "data/2015/final/movies/red",
                finalSlide1: "data/2015/final/slides/red.pdf",
                finalBrochure1: "data/2015/final/extras/red_brochure.pdf",
                finalBrochure2: null,
            },
            {
                projId: "Vantage", // folder name
                projName: "Vantage",
                projDesc: "camera toy",
                projColor: "orange",
                projTeam: "Akash Salgado-Agarwal, Andres Bierman, Ben Spiro, Brady Knight, Connie Liu, Ife Bakare, Jacob Tims, Lucas Moura Santana, Michael Portas, Michelle Navarro, Russell Johnson, Yi Zhong, Alex Lednev, Anthony Pennes, Jacob Rothman, Jenny Kim, Kalin Malouf Mestres, Lucas Mendes, Luke Schlueter, Roala Ruiz, Tyler Clayton, Yazir Alsharif",
                projCode: "data/2015/homepage/codeOfEthics/codeOfEthics.html#orange",

                ideasPic1: "data/2015/ideas/OrangeA1.jpg",
                ideasPic2: "data/2015/ideas/OrangeA2.jpg",
                ideasPic3: "data/2015/ideas/OrangeA3.jpg",
                ideasPic4: "data/2015/ideas/OrangeB1.jpg",
                ideasPic5: "data/2015/ideas/OrangeB2.jpg",
                ideasPic6: "data/2015/ideas/OrangeB3.jpg",

                sketchName1: "SpectR",
                sketchName2: "ImagiDome",
                sketchName3: "Bumble",
                sketchName4: "E-Strip",
                sketchName5: "Taply",
                sketchName6: "Cool Couch",
                sketchPic1: "data/2015/sketch/photos/orangeA1_1.jpg",
                sketchPic2: "data/2015/sketch/photos/orangeA1_2.jpg",
                sketchPic3: "data/2015/sketch/photos/orangeA2_1.jpg",
                sketchPic4: "data/2015/sketch/photos/orangeA2_2.jpg",
                sketchPic5: "data/2015/sketch/photos/orangeA3_1.jpg",
                sketchPic6: "data/2015/sketch/photos/orangeA3_2.jpg",
                sketchPic7: "data/2015/sketch/photos/orangeB1_1.jpg",
                sketchPic8: "data/2015/sketch/photos/orangeB1_2.jpg",
                sketchPic9: "data/2015/sketch/photos/orangeB2_1.jpg",
                sketchPic10: "data/2015/sketch/photos/orangeB2_2.jpg",
                sketchPic11: "data/2015/sketch/photos/orangeB3_1.jpg",
                sketchPic12: "data/2015/sketch/photos/orangeB3_2.jpg",
                sketchMov1: "data/2015/sketch/movies/orangeA1",
                sketchMov2: "data/2015/sketch/movies/orangeA2",
                sketchMov3: "data/2015/sketch/movies/orangeA3",
                sketchMov4: "data/2015/sketch/movies/orangeB1",
                sketchMov5: "data/2015/sketch/movies/orangeB2",
                sketchMov6: "data/2015/sketch/movies/orangeB3",
                sketchSlide1: "data/2015/sketch/slides/orangeA1.pdf",
                sketchSlide2: "data/2015/sketch/slides/orangeA2.pdf",
                sketchSlide2: "data/2015/sketch/slides/orangeA3.pdf",
                sketchSlide3: "data/2015/sketch/slides/orangeB1.pdf",
                sketchSlide4: "data/2015/sketch/slides/orangeB2.pdf",
                sketchSlide4: "data/2015/sketch/slides/orangeB3.pdf",

                mockName1: "doodle dome",
                mockName2: "bumble",
                mockName3: "taply",
                mockName4: "e-strip",
                mockPic1: "data/2015/mockup/photos/orangeA1_1.jpg",
                mockPic2: "data/2015/mockup/photos/orangeA1_2.jpg",
                mockPic3: "data/2015/mockup/photos/orangeA2_1.jpg",
                mockPic4: "data/2015/mockup/photos/orangeA2_2.jpg",
                mockPic5: "data/2015/mockup/photos/orangeB1_1.jpg",
                mockPic6: "data/2015/mockup/photos/orangeB1_2.jpg",
                mockPic7: "data/2015/mockup/photos/orangeB2_1.jpg",
                mockPic8: "data/2015/mockup/photos/orangeB2_2.jpg",
                mockMov1: "data/2015/mockup/movies/orangeA1",
                mockMov2: "data/2015/mockup/movies/orangeA2",
                mockMov3: "data/2015/mockup/movies/orangeB1",
                mockMov4: "data/2015/mockup/movies/orangeB2",
                mockSlide1: "data/2015/mockup/slides/orangeA1.pdf",
                mockSlide2: "data/2015/mockup/slides/orangeA2.pdf",
                mockSlide3: "data/2015/mockup/slides/orangeB1.pdf",
                mockSlide4: "data/2015/mockup/slides/orangeB2.pdf",

                assemblyPic1: "data/2015/assembly/orangeAssembly.jpg",
                assemblyContract1: "data/2015/assembly/orangeContract.pdf",

                techPic1: "data/2015/tech/photos/Orange1.jpg",
                techPic2: "data/2015/tech/photos/Orange2.jpg",
                techMov1: "data/2015/tech/movies/orange",

                finalPic1: "data/2015/final/photos/original/orange1.jpg",
                finalPic1Thumb: "data/2015/final/photos/small/orange1.jpg",
                finalPic2: "data/2015/final/photos/original/orange2.jpg",
                finalPic2Thumb: "data/2015/final/photos/small/orange2.jpg",
                finalMov1: "data/2015/final/movies/orange",
                finalSlide1: "data/2015/final/slides/orange.pdf",
                finalBrochure1: "data/2015/final/extras/orange_brochure.pdf",
                finalBrochure2: null,
            },
            {
                projId: "Letter Bug", // folder name
                projName: "Letter Bug",
                projDesc: "Braille teacher",
                projColor: "green",
                projTeam: "Alex Romero Gomez, David Afolabi, Guilherme Mello, Kristen Manning, Lucien Morales, Rachel Lathe, Reko Ahmed, Rhyse Bendell, Scott McDonald, Colt Richter, Fernando Cunha, Jessica Anderson, Joe Sandoval, John Bolaji, Mario Prado, Nihala Thanikkal, Silvia Vazquez, Stephen Rodan",
                projCode: "data/2015/homepage/codeOfEthics/codeOfEthics.html#green",

                ideasPic1: "data/2015/ideas/GreenA1.jpg",
                ideasPic2: "data/2015/ideas/GreenA2.jpg",
                ideasPic3: "data/2015/ideas/GreenA3.jpg",
                ideasPic4: "data/2015/ideas/GreenB1.jpg",
                ideasPic5: "data/2015/ideas/GreenB2.jpg",
                ideasPic6: "data/2015/ideas/GreenB3.jpg",

                sketchName1: "MagneTrain",
                sketchName2: "Ball Buddy",
                sketchName3: "VibraTunes",
                sketchName4: "NorthPull",
                sketchName5: "Phanhaptic",
                sketchName6: "Master Mixer",
                sketchPic1: "data/2015/sketch/photos/greenA1_1.jpg",
                sketchPic2: "data/2015/sketch/photos/greenA1_2.jpg",
                sketchPic3: "data/2015/sketch/photos/greenA2_1.jpg",
                sketchPic4: "data/2015/sketch/photos/greenA2_2.jpg",
                sketchPic5: "data/2015/sketch/photos/greenA3_1.jpg",
                sketchPic6: "data/2015/sketch/photos/greenA3_2.jpg",
                sketchPic7: "data/2015/sketch/photos/greenB1_1.jpg",
                sketchPic8: "data/2015/sketch/photos/greenB1_2.jpg",
                sketchPic9: "data/2015/sketch/photos/greenB2_1.jpg",
                sketchPic10: "data/2015/sketch/photos/greenB2_2.jpg",
                sketchPic11: "data/2015/sketch/photos/greenB3_1.jpg",
                sketchPic12: "data/2015/sketch/photos/greenB3_2.jpg",
                sketchMov1: "data/2015/sketch/movies/greenA1",
                sketchMov2: "data/2015/sketch/movies/greenA2",
                sketchMov3: "data/2015/sketch/movies/greenA3",
                sketchMov4: "data/2015/sketch/movies/greenB1",
                sketchMov5: "data/2015/sketch/movies/greenB2",
                sketchMov6: "data/2015/sketch/movies/greenB3",
                sketchSlide1: "data/2015/sketch/slides/greenA1.pdf",
                sketchSlide2: "data/2015/sketch/slides/greenA2.pdf",
                sketchSlide2: "data/2015/sketch/slides/greenA3.pdf",
                sketchSlide3: "data/2015/sketch/slides/greenB1.pdf",
                sketchSlide4: "data/2015/sketch/slides/greenB2.pdf",
                sketchSlide4: "data/2015/sketch/slides/greenB3.pdf",

                mockName1: "MagneTrain",
                mockName2: "VibraTunes",
                mockName3: "NorthSense",
                mockName4: "InstaBraille",
                mockPic1: "data/2015/mockup/photos/greenA1_1.jpg",
                mockPic2: "data/2015/mockup/photos/greenA1_2.jpg",
                mockPic3: "data/2015/mockup/photos/greenA2_1.jpg",
                mockPic4: "data/2015/mockup/photos/greenA2_2.jpg",
                mockPic5: "data/2015/mockup/photos/greenB1_1.jpg",
                mockPic6: "data/2015/mockup/photos/greenB1_2.jpg",
                mockPic7: "data/2015/mockup/photos/greenB2_1.jpg",
                mockPic8: "data/2015/mockup/photos/greenB2_2.jpg",
                mockMov1: "data/2015/mockup/movies/greenA1",
                mockMov2: "data/2015/mockup/movies/greenA2",
                mockMov3: "data/2015/mockup/movies/greenB1",
                mockMov4: "data/2015/mockup/movies/greenB2",
                mockSlide1: "data/2015/mockup/slides/greenA1.pdf",
                mockSlide2: "data/2015/mockup/slides/greenA2.pdf",
                mockSlide3: "data/2015/mockup/slides/greenB1.pdf",
                mockSlide4: "data/2015/mockup/slides/greenB2.pdf",

                assemblyPic1: "data/2015/assembly/greenAssembly.jpg",
                assemblyContract1: "data/2015/assembly/greenContract.pdf",

                techPic1: "data/2015/tech/photos/Green1.jpg",
                techPic2: "data/2015/tech/photos/Green2.jpg",
                techMov1: "data/2015/tech/movies/green",

                finalPic1: "data/2015/final/photos/original/green1.jpg",
                finalPic1Thumb: "data/2015/final/photos/small/green1.jpg",
                finalPic2: "data/2015/final/photos/original/green2.jpg",
                finalPic2Thumb: "data/2015/final/photos/small/green2.jpg",
                finalMov1: "data/2015/final/movies/green",
                finalSlide1: "data/2015/final/slides/green.pdf",
                finalBrochure1: "data/2015/final/extras/green_brochure.pdf",
                finalBrochure2: null,
            },
            {
                projId: "Orion", // folder name
                projName: "Orion",
                projDesc: "light tracking system",
                projColor: "pink",
                projTeam: "Abdullah Alomari, Alana Peters, Conrad Sanborn, Jacqueline Kuo, Joy Park, Justin Pedley, Katie Ward, Laura Standley, Meiji Yue, Ronald Heisser, Bassey James, Chris Kwok, Emad Baata, Joe Corilla, Eurah Ko, Krithika Swaminathan, Lauren Wright, Matt Hole, Sammi Bray, Titan Hartono",
                projCode: "data/2015/homepage/codeOfEthics/codeOfEthics.html#pink",

                ideasPic1: "data/2015/ideas/PinkA1.jpg",
                ideasPic2: "data/2015/ideas/PinkA2.jpg",
                ideasPic3: "data/2015/ideas/PinkA3.jpg",
                ideasPic4: "data/2015/ideas/PinkB1.jpg",
                ideasPic5: "data/2015/ideas/PinkB2.jpg",
                ideasPic6: "data/2015/ideas/PinkB3.jpg",

                sketchName1: "AnySpace",
                sketchName2: "RightLight",
                sketchName3: "fLoorED",
                sketchName4: "ModCase",
                sketchName5: "Ziplite",
                sketchName6: "Synesthesia",
                sketchPic1: "data/2015/sketch/photos/pinkA1_1.jpg",
                sketchPic2: "data/2015/sketch/photos/pinkA1_2.jpg",
                sketchPic3: "data/2015/sketch/photos/pinkA2_1.jpg",
                sketchPic4: "data/2015/sketch/photos/pinkA2_2.jpg",
                sketchPic5: "data/2015/sketch/photos/pinkA3_1.jpg",
                sketchPic6: "data/2015/sketch/photos/pinkA3_2.jpg",
                sketchPic7: "data/2015/sketch/photos/pinkB1_1.jpg",
                sketchPic8: "data/2015/sketch/photos/pinkB1_2.jpg",
                sketchPic9: "data/2015/sketch/photos/pinkB2_1.jpg",
                sketchPic10: "data/2015/sketch/photos/pinkB2_2.jpg",
                sketchPic11: "data/2015/sketch/photos/pinkB3_1.jpg",
                sketchPic12: "data/2015/sketch/photos/pinkB3_2.jpg",

                sketchMov1: "data/2015/sketch/movies/pinkA1",
                sketchMov2: "data/2015/sketch/movies/pinkA2",
                sketchMov3: "data/2015/sketch/movies/pinkA3",
                sketchMov4: "data/2015/sketch/movies/pinkB1",
                sketchMov5: "data/2015/sketch/movies/pinkB2",
                sketchMov6: "data/2015/sketch/movies/pinkB3",
                sketchSlide1: "data/2015/sketch/slides/pinkA1.pdf",
                sketchSlide2: "data/2015/sketch/slides/pinkA2.pdf",
                sketchSlide2: "data/2015/sketch/slides/pinkA3.pdf",
                sketchSlide3: "data/2015/sketch/slides/pinkB1.pdf",
                sketchSlide4: "data/2015/sketch/slides/pinkB2.pdf",
                sketchSlide4: "data/2015/sketch/slides/pinkB3.pdf",

                mockName1: "Rubble Ready",
                mockName2: "AnySpace",
                mockName3: "Synesthesia",
                mockName4: "ZipLite",
                mockPic1: "data/2015/mockup/photos/pinkA1_1.jpg",
                mockPic2: "data/2015/mockup/photos/pinkA1_2.jpg",
                mockPic3: "data/2015/mockup/photos/pinkA2_1.jpg",
                mockPic4: "data/2015/mockup/photos/pinkA2_2.jpg",
                mockPic5: "data/2015/mockup/photos/pinkB1_1.jpg",
                mockPic6: "data/2015/mockup/photos/pinkB1_2.jpg",
                mockPic7: "data/2015/mockup/photos/pinkB2_1.jpg",
                mockPic8: "data/2015/mockup/photos/pinkB2_2.jpg",
                mockMov1: "data/2015/mockup/movies/pinkA1",
                mockMov2: "data/2015/mockup/movies/pinkA2",
                mockMov3: "data/2015/mockup/movies/pinkB1",
                mockMov4: "data/2015/mockup/movies/pinkB2",
                mockSlide1: "data/2015/mockup/slides/pinkA1.pdf",
                mockSlide2: "data/2015/mockup/slides/pinkA2.pdf",
                mockSlide3: "data/2015/mockup/slides/pinkB1.pdf",
                mockSlide4: "data/2015/mockup/slides/pinkB2.pdf",

                assemblyPic1: "data/2015/assembly/pinkAssembly.jpg",
                assemblyContract1: "data/2015/assembly/pinkContract.pdf",

                techPic1: "data/2015/tech/photos/Pink1.jpg",
                techPic2: "data/2015/tech/photos/Pink2.jpg",
                techMov1: "data/2015/tech/movies/pink",

                finalPic1: "data/2015/final/photos/original/pink1.jpg",
                finalPic1Thumb: "data/2015/final/photos/small/pink1.jpg",
                finalPic2: "data/2015/final/photos/original/pink2.jpg",
                finalPic2Thumb: "data/2015/final/photos/small/pink2.jpg",
                finalMov1: "data/2015/final/movies/pink",
                finalSlide1: "data/2015/final/slides/pink.pdf",
                finalBrochure1: "data/2015/final/extras/pink_brochure.pdf",
                finalBrochure2: null,
            },
            {
                projId: "SleepTight", // folder name
                projName: "SleepTight",
                projDesc: "back brace",
                projColor: "silver",
                projTeam: "Alex Breton, Anna Leonard, Christina Sung, Ian Tolan, Louis Segall, Luther Banner III, Matt Tancik, Natasha Gunther, Noam Buckman, Pedro Brito, Brian Wilcox, Chrystal Chern, Jow Schuman, Joyce Zhang, Lucas Lancellotti Sanches, Mohammed Aljuzayri, Morgan Moroi, Neil Borja, Sergio Falcon, Sydney Carter, Zach Mikaya",
                projCode: "data/2015/homepage/codeOfEthics/codeOfEthics.html#silver",

                ideasPic1: "data/2015/ideas/SilverA1.jpg",
                ideasPic2: "data/2015/ideas/SilverA2.jpg",
                ideasPic3: "data/2015/ideas/SilverA3.jpg",
                ideasPic4: "data/2015/ideas/SilverB1.jpg",
                ideasPic5: "data/2015/ideas/SilverB2.jpg",
                ideasPic6: "data/2015/ideas/SilverB3.jpg",

                sketchName1: "Epilepsy Detector",
                sketchName2: "Interactive Countertop",
                sketchName3: "Water Washer Recycling Unit",
                sketchName4: "Smart Brace for Scoliosis",
                sketchName5: "Worldly Window",
                sketchName6: "Sweet Spotter",
                sketchPic1: "data/2015/sketch/photos/silverA1_1.jpg",
                sketchPic2: "data/2015/sketch/photos/silverA1_2.jpg",
                sketchPic3: "data/2015/sketch/photos/silverA2_1.jpg",
                sketchPic4: "data/2015/sketch/photos/silverA2_2.jpg",
                sketchPic5: "data/2015/sketch/photos/silverA3_1.jpg",
                sketchPic6: "data/2015/sketch/photos/silverA3_2.jpg",
                sketchPic7: "data/2015/sketch/photos/silverB1_1.jpg",
                sketchPic8: "data/2015/sketch/photos/silverB1_2.jpg",
                sketchPic9: "data/2015/sketch/photos/silverB2_1.jpg",
                sketchPic10: "data/2015/sketch/photos/silverB2_2.jpg",
                sketchPic11: "data/2015/sketch/photos/silverB3_1.jpg",
                sketchPic12: "data/2015/sketch/photos/silverB3_2.jpg",
                sketchMov1: "data/2015/sketch/movies/silverA1",
                sketchMov2: "data/2015/sketch/movies/silverA2",
                sketchMov3: "data/2015/sketch/movies/silverA3",
                sketchMov4: "data/2015/sketch/movies/silverB1",
                sketchMov5: "data/2015/sketch/movies/silverB2",
                sketchMov6: "data/2015/sketch/movies/silverB3",
                sketchSlide1: "data/2015/sketch/slides/silverA1.pdf",
                sketchSlide2: "data/2015/sketch/slides/silverA2.pdf",
                sketchSlide2: "data/2015/sketch/slides/silverA3.pdf",
                sketchSlide3: "data/2015/sketch/slides/silverB1.pdf",
                sketchSlide4: "data/2015/sketch/slides/silverB2.pdf",
                sketchSlide4: "data/2015/sketch/slides/silverB3.pdf",

                mockName1: "Hotpause",
                mockName2: "RecyClean",
                mockName3: "Sweet Spotter",
                mockName4: "Smart Back Brace for Scoliosis",
                mockPic1: "data/2015/mockup/photos/silverA1_1.jpg",
                mockPic2: "data/2015/mockup/photos/silverA1_2.jpg",
                mockPic3: "data/2015/mockup/photos/silverA2_1.jpg",
                mockPic4: "data/2015/mockup/photos/silverA2_2.jpg",
                mockPic5: "data/2015/mockup/photos/silverB1_1.jpg",
                mockPic6: "data/2015/mockup/photos/silverB1_2.jpg",
                mockPic7: "data/2015/mockup/photos/silverB2_1.jpg",
                mockPic8: "data/2015/mockup/photos/silverB2_2.jpg",
                mockMov1: "data/2015/mockup/movies/silverA1",
                mockMov2: "data/2015/mockup/movies/silverA2",
                mockMov3: "data/2015/mockup/movies/silverB1",
                mockMov4: "data/2015/mockup/movies/silverB2",
                mockSlide1: "data/2015/mockup/slides/silverA1.pdf",
                mockSlide2: "data/2015/mockup/slides/silverA2.pdf",
                mockSlide3: "data/2015/mockup/slides/silverB1.pdf",
                mockSlide4: "data/2015/mockup/slides/silverB2.pdf",

                assemblyPic1: "data/2015/assembly/silverAssembly.jpg",
                assemblyContract1: "data/2015/assembly/silverContract.pdf",

                techPic1: "data/2015/tech/photos/Sivler1.jpg",
                techPic2: "data/2015/tech/photos/Silver2.jpg",
                techMov1: "data/2015/tech/movies/silver",

                finalPic1: "data/2015/final/photos/original/silver1.jpg",
                finalPic1Thumb: "data/2015/final/photos/small/silver1.jpg",
                finalPic2: "data/2015/final/photos/original/silver2.jpg",
                finalPic2Thumb: "data/2015/final/photos/small/silver2.jpg",
                finalMov1: "data/2015/final/movies/silver",
                finalSlide1: "data/2015/final/slides/silver.pdf",
                finalBrochure1: "data/2015/final/extras/silver_brochure.pdf",
                finalBrochure2: null,
            },
            {
                projId: "touchLess", // folder name
                projName: "touchLess",
                projDesc: "door opener",
                projColor: "purple",
                projTeam: "Adrian Samsel, Aquil Fannis, Camilo Ruiz, Eric Kline, Eric Shirley, Isabella Stuopis, Jarrod Smith, Max Malinowski, Roger Hartman II, Sally Miller, Sophia Wu, Carrington Motley, Eric Johnson, Hannah Hoffman, Joshua Born, Kristen Augdahl, Lesley Wang, Michael Cheung, Nathan Varady, Serena Pan, Valentina Chamorro",
                projCode: "data/2015/homepage/codeOfEthics/codeOfEthics.html#purple",

                ideasPic1: "data/2015/ideas/PurpleA1.jpg",
                ideasPic2: "data/2015/ideas/PurpleA2.jpg",
                ideasPic3: "data/2015/ideas/PurpleA3.jpg",
                ideasPic4: "data/2015/ideas/PurpleB1.jpg",
                ideasPic5: "data/2015/ideas/PurpleB2.jpg",
                ideasPic6: "data/2015/ideas/PurpleB3.jpg",

                sketchName1: "RUSTore",
                sketchName2: "Kontrol",
                sketchName3: "Virtual Flyer",
                sketchName4: "Word and Seek",
                sketchName5: "Touchless Handle",
                sketchName6: "Tidy Table",
                sketchPic1: "data/2015/sketch/photos/purpleA1_1.jpg",
                sketchPic2: "data/2015/sketch/photos/purpleA1_2.jpg",
                sketchPic3: "data/2015/sketch/photos/purpleA2_1.jpg",
                sketchPic4: "data/2015/sketch/photos/purpleA2_2.jpg",
                sketchPic5: "data/2015/sketch/photos/purpleA3_1.jpg",
                sketchPic6: "data/2015/sketch/photos/purpleA3_2.jpg",
                sketchPic7: "data/2015/sketch/photos/purpleB1_1.jpg",
                sketchPic8: "data/2015/sketch/photos/purpleB1_2.jpg",
                sketchPic9: "data/2015/sketch/photos/purpleB2_1.jpg",
                sketchPic10: "data/2015/sketch/photos/purpleB2_2.jpg",
                sketchPic11: "data/2015/sketch/photos/purpleB3_1.jpg",
                sketchPic12: "data/2015/sketch/photos/purpleB3_2.jpg",
                sketchMov1: "data/2015/sketch/movies/purpleA1",
                sketchMov2: "data/2015/sketch/movies/purpleA2",
                sketchMov3: "data/2015/sketch/movies/purpleA3",
                sketchMov4: "data/2015/sketch/movies/purpleB1",
                sketchMov5: "data/2015/sketch/movies/purpleB2",
                sketchMov6: "data/2015/sketch/movies/purpleB3",
                sketchSlide1: "data/2015/sketch/slides/purpleA1.pdf",
                sketchSlide2: "data/2015/sketch/slides/purpleA2.pdf",
                sketchSlide2: "data/2015/sketch/slides/purpleA3.pdf",
                sketchSlide3: "data/2015/sketch/slides/purpleB1.pdf",
                sketchSlide4: "data/2015/sketch/slides/purpleB2.pdf",
                sketchSlide4: "data/2015/sketch/slides/purpleB3.pdf",

                mockName1: "RUSTore",
                mockName2: "Rock'em Reality",
                mockName3: "Wordie",
                mockName4: "Touchless Handle",
                mockPic1: "data/2015/mockup/photos/purpleA1_1.jpg",
                mockPic2: "data/2015/mockup/photos/purpleA1_2.jpg",
                mockPic3: "data/2015/mockup/photos/purpleA2_1.jpg",
                mockPic4: "data/2015/mockup/photos/purpleA2_2.jpg",
                mockPic5: "data/2015/mockup/photos/purpleB1_1.jpg",
                mockPic6: "data/2015/mockup/photos/purpleB1_2.jpg",
                mockPic7: "data/2015/mockup/photos/purpleB2_1.jpg",
                mockPic8: "data/2015/mockup/photos/purpleB2_2.jpg",
                mockMov1: "data/2015/mockup/movies/purpleA1",
                mockMov2: "data/2015/mockup/movies/purpleA2",
                mockMov3: "data/2015/mockup/movies/purpleB1",
                mockMov4: "data/2015/mockup/movies/purpleB2",
                mockSlide1: "data/2015/mockup/slides/purpleA1.pdf",
                mockSlide2: "data/2015/mockup/slides/purpleA2.pdf",
                mockSlide3: "data/2015/mockup/slides/purpleB1.pdf",
                mockSlide4: "data/2015/mockup/slides/purpleB2.pdf",

                assemblyPic1: "data/2015/assembly/purpleAssembly.jpg",
                assemblyContract1: "data/2015/assembly/purpleContract.pdf",

                techPic1: "data/2015/tech/photos/Purple1.jpg",
                techPic2: "data/2015/tech/photos/Purple2.jpg",
                techMov1: "data/2015/tech/movies/purple",

                finalPic1: "data/2015/final/photos/original/purple1.jpg",
                finalPic1Thumb: "data/2015/final/photos/small/purple1.jpg",
                finalPic2: "data/2015/final/photos/original/purple2.jpg",
                finalPic2Thumb: "data/2015/final/photos/small/purple2.jpg",
                finalMov1: "data/2015/final/movies/purple",
                finalSlide1: "data/2015/final/slides/purple.pdf",
                finalBrochure1: "data/2015/final/extras/purple_brochure.pdf",
                finalBrochure2: null,
            },
        ],
    },
}
